src/reducers/entities/general.js
Summary
Preserve the device token id after the user has logged out.
Ticket Link
https://mattermost.atlassian.net/browse/PLT-5898
Test Information
This PR was tested on: [iPhone 6s IOS 10.2.1, Samsung J5 Android 6.0.1]
=> PLT-5898 preserve device token after logout (master)

src/reducers/entities/general.js
Preserve the device token id after the user has logged out.
https://mattermost.atlassian.net/browse/PLT-5898
This PR was tested on: [iPhone 6s IOS 10.2.1, Samsung J5 Android 6.0.1]
=> PLT-5898 preserve device token after logout backported to 3.7

src/actions/posts.js, src/actions/preferences.js, src/constants/index.js, src/utils/post_utils.js, test/actions/posts.test.js
This PR adds the actions to flag and unflag posts
https://mattermost.atlassian.net/browse/PLT-5511
This PR was tested on: IOS 10.2.1 iPhone 6s, Android 6.0.1 Samsung J5
=> PLT-5511 Ability to flag and unflag posts (release-3.7)

src/actions/files.js
This PR reworks the `uploadFile` action to merge the returned uploaded files with the returned client ids. It also removes the requestId tracking and the `cancelUploadFileRequest` action. 
https://mattermost.atlassian.net/browse/PLT-6033
@jarredwitt
=> PLT-6033 Add loading spinner to image previewer

src/actions/posts.js, src/actions/teams.js, src/actions/users.js, src/actions/websocket.js
Preventing the request for the profile of the current user and exclude the current user from requests that returns the user as part of it.
This is done because some requests for profiles return the user sanitized which in the case of the current user we don't want that.
https://mattermost.atlassian.net/browse/PLT-5968
=> PLT-5968 prevent profile request to update current user in the store

src/selectors/entities/channels.js
When loading the app and the current channel has new messages the unread indicators show, this PR won't count the unread messages for the current channel as is the one you are viewing
=> discard unread messages for the current channel

src/actions/users.js, src/reducers/entities/typing.js
The Android polyfill reports error on weakmaps when the values are undefined or null, this will get rid of that, at least in the two places identified.
https://mattermost.atlassian.net/browse/PLT-6087
=> PLT-6087 Fixing WeakMaps

src/selectors/entities/posts.js
This ticket adds a makeGetCommentCountForPost for posts.
https://mattermost.atlassian.net/browse/PLT-5716
@jarredwitt
=> Add comment count selector

src/utils/channel_utils.js
In android the sort behaves differently so caps were before this fixes it
=> Fix sort channels

src/actions/websocket.js, src/reducers/entities/posts.js, src/selectors/entities/posts.js, test/actions/posts.test.js, test/actions/users.test.js, test/actions/websocket.test.js, test/selectors/posts.test.js
Rename postsByChannel to postsInChannel to use consistent naming (such as profilesInTeam, etc.).
https://mattermost.atlassian.net/browse/PLT-5951
=> Rename postsByChannel entity to postsInChannel to use consistent naming

package.json, src/action_types/admin.js, src/action_types/index.js, src/actions/admin.js, src/actions/general.js, src/client/client4.js, src/reducers/entities/admin.js, src/reducers/entities/emojis.js, src/reducers/entities/index.js, src/reducers/entities/integrations.js, src/reducers/requests/admin.js, src/reducers/requests/index.js, test/actions/admin.test.js, test/actions/emojis.test.js, test/actions/files.test.js, test/actions/general.test.js, test/actions/integrations.test.js
Add admin entities for config, logs and audits. I'm using `nock` for mocking the server, it's really simple. Currently I'll only use it for admin endpoints that need to be mocked but I think long term we should move towards using it for all the action tests so that we can run them without having to stand-up and configure an MM server
https://mattermost.atlassian.net/browse/PLT-5960
=> PLT-5960 Add admin entities for config, logs and audits (part1) 

NOTICE.txt, package.json, src/store/configureStore.dev.js, src/store/configureStore.prod.js
This PR adds the ability to create an offline redux store using the redux-offline library.
https://mattermost.atlassian.net/browse/PLT-6173
@jarredwitt
=> PLT-6173: Offline redux store

src/actions/websocket.js
This sets a flag to follow the reconnection path if the WebSocket was closed manually and also fixes a issue when fetching the posts for a channel when reconnecting
=> Create flag for WS reconnection and fix loadPostHelper (3.7)

src/actions/websocket.js, src/reducers/entities/posts.js, src/utils/post_utils.js
Fixes the posts reducer to mark deleted posts as deleted when using getPostsSince and getPostsBefore.
Also uses the latests update_at that we have for getPostsSince when the WebSocket reconnects
=> Posts reducer and getPostsSince

src/client/client.js
Add a timestamp to ping request to prevent cached responses
=> Ping timestamp

src/store/configureStore.prod.js
When building the webapp for production it was erroring out because the third argument was undefined. Related to the redux-offline changes I assume
=> Fix broken offlineCompose invocation

.npmignore, src/action_types/channels.js, src/actions/channels.js, src/actions/preferences.js, src/reducers/entities/channels.js, src/reducers/requests/channels.js, test/actions/channels.test.js, test/test_store.js
Makes leave channel action optimistic
also fixes a constant typo in preferences actions and adds `.babelrc` to `.npmignore` so whoever implements the library can transpile the lib using its own `.babelrc` file
https://mattermost.atlassian.net/browse/RN-54
This PR was tested on: 
* IOS 10.3.1 iPhone 6s
* Android 7.1.1 Nexus 7
* Android 6.0.1 Samsung J5
=> RN-54 Make leave channel optimistic

package.json
Postinstall scripts delete `.babelrc` file to make sure is not there, this is cause `yarn` does not honor `.npmignore` files
=> Make sure postinstall runs without .babelrc

src/actions/posts.js, src/actions/users.js, src/client/client4.js, test/actions/posts.test.js, test/actions/users.test.js
This adds the `/users/usernames` added in https://github.com/mattermost/platform/pull/6218 and uses it to get the profiles for any users that were mentioned in the post. There's also some logic to attempt to capture usernames ending in periods as well as ones that don't which just end a sentence.
https://mattermost.atlassian.net/browse/PLT-4457
- All new/modified APIs include changes to the drivers
=> PLT-4457 Changed getProfilesAndStatusesForPosts to get at mentioned users

src/store/configureStore.dev.js, test/test_store.js
To make sure the tests do not fail because of the action buffers a flag was added to disable the buffer during test runs
=> Disable action buffers during tests

src/actions/channels.js, src/reducers/entities/channels.js, test/actions/channels.test.js
Add getMyChannelMember action and don't wipe channel members on team switch.
=> Add getMyChannelMember action and don't wipe channel members on team switch

src/actions/posts.js
This PR ensures that posts submitted when offline will be marked as failed instead of added to the outbox to retry at a later time.
=> Fail optimistic post when offline

src/store/configureStore.prod.js
Having buffering on the webapp was causing issues since we need to have the current user and some other entities before rendering some components. So need the ability to disable the buffer like we do for the tests
=> Add option for disabling action buffer to prod store

Makefile
When running `make pre-run` we forgot to include the `action_types` folder
=> Include cleaning action_types folder

src/actions/preferences.js, src/actions/websocket.js
This PR fixes a bug in `makeGroupMessageVisibleIfNecessary` where it wasn't using the `entities` and that was causing an error to be thrown. Also replaced getChannel with getChannelsAndMyMembers when we need to get a channel for the current user
https://mattermost.atlassian.net/browse/RN-144
=> RN-144 Properly show GM's and channels when user is added or messaged

src/selectors/entities/channels.js, test/selectors/channels.test.js
Adds a selector to get the unread messages and mentions for the current team only
=> Get unread messages and mentions for the current team

src/selectors/entities/preferences.js, src/selectors/entities/users.js, test/selectors/preferences.test.js, test/selectors/users.test.js
Add DM selectors to preference and user entities.
=> Add DM selectors

src/selectors/entities/teams.js
When click on the leave team in the mattermost ui it cause an issue and the user is not redirect to logout or select a new team.
JIRA: https://mattermost.atlassian.net/browse/PLT-6644
=> [PLT-6644] fix which causes error when click in leave team

src/client/websocket_client.js, src/selectors/entities/channels.js
Somehow in android the websocket is being authenticated using the cookies and because of a [server bug](https://mattermost.atlassian.net/browse/PLT-6653) that registers a connection every time the websocket authenticates we were receiving twice each WS message.
Also this PR fixes getUnreadsInCurrentTeam that was not considering DM's and GM's for the unread messages and mentions
https://mattermost.atlassian.net/browse/RN-141
=> RN-141 Do not authenticate WS for android (is using the cookies)

src/selectors/entities/users.js
When leaving a Team the `currentTeamMembership` and `currentChannelMembership` in the selector are **undefined**, this PR fixes the issue
=> Fix getCurrentUserRoles selector

src/actions/websocket.js
On a previous PR we remove the `getMyTeams` from the WS reconnection, this adds it back as well as calling `getTeams` to be sure we are getting the open teams from the server
=> on reconnect always get myTeams

src/action_types/admin.js, src/actions/admin.js, src/client/client4.js, src/reducers/requests/admin.js, test/actions/admin.test.js
Add action for uploading brand image. @enahum this endpoint is available in 3.8 https://github.com/mattermost/platform/blob/release-3.8/api4/brand.go#L19
=> Add action for uploading brand image

src/action_types/users.js, src/actions/users.js, src/client/client4.js, src/reducers/requests/users.js, test/actions/users.test.js
Add action for generating MFA secret. Don't need to store anything for this because it should be used one-time by the caller and thrown away.
=> Action for generating MFA secret

src/action_types/preferences.js, src/actions/preferences.js, src/actions/websocket.js, src/reducers/entities/preferences.js
Because the preferences object is stored offline and they are not sync'ed across devices there's a need to set the whole object once we get it from the server as they might be deleted preferences that will not get deleted.
In addition to this for the WebSocket event that get triggers when a user leave or is removed from a channel we are going to emit an Event so the client can handle some internal state.
=> Reset Preferences

src/action_types/index.js, src/action_types/internal.js, src/actions/posts.js, src/actions/websocket.js, src/reducers/index.js, src/reducers/internal/index.js
Instead of using the last update_at from the posts that we have in the store, this creates an internal store that has the last time a channel fetched posts and that timestamp will be used to `getPostSince` that way we can avoid to miss messages.
=> Add an internal reducer to store the last time a channel fetched posts

src/actions/users.js, src/client/client4.js, test/actions/users.test.js
Remove unused LDAP ID from ldap to email action. Email is used to identify the user and LDAP account so we don't need the ID.
=> Remove unused LDAP ID from ldap to email action

src/actions/channels.js, src/reducers/entities/channels.js, test/actions/channels.test.js
Changed the ADD_CHANNEL_MEMBER_SUCCESS action to work like the REMOVE_CHANNEL_MEMBER_SUCCESS
https://mattermost.atlassian.net/browse/RN-198
=> RN-198 Fixed adding members to channel not incrementing member count

src/client/client4.js, test/actions/integrations.test.js, test/test_helper.js
On the webapp, if someone changes something in the system console then the `X-Version-Id` header will change to let the client know it needs to reload. Responses cached by the browser might still hold the old version header. If we use an old version header to update the current version, and then a non-cached request gives us the new version then we can get stuck in a loop of changing the version (and causing a redirect loop on the webapp).
There is apparently no good way of telling if a response given to you from a browser is from the browser cache or actually from the server. The workaround I've added here is to ignore the version header from any response that has caching control. Most of our requests do not so this shouldn't affect much but it should prevent any cached responses …
=> Only use version response header when cache control not set

src/store/configureStore.dev.js, src/store/configureStore.prod.js, src/store/helpers.js, test/test_store.js
This PR adds the ability to add middleware from the client using the `additionalMiddleware` property of the `clientOptions` argument.
@jarredwitt
=> Add ability to add client middleware to redux lib

src/constants/general.js, src/selectors/entities/channels.js, src/selectors/entities/general.js, src/utils/channel_utils.js, src/utils/post_utils.js, test/utils/channel_utils.test.js
The previous version didn't take the RestrictPrivateChannelManageMembers setting into effect
https://mattermost.atlassian.net/browse/RN-215
=> RN-215 Fixed canManageChannelMembers selector to obey policy config

src/actions/integrations.js, src/client/client4.js, test/actions/integrations.test.js
Don't require team id in arguments for add command action.
=> Don't require team id in arguments for add command action

src/actions/channels.js, src/reducers/entities/channels.js
This was wiping out all the channel members for all users in all the channels the current user was in when doing a `getMyChannelMembers`. Changed it to only remove the current user's channel members.
=> Don't remove all channel members when receiving my channel members

src/actions/posts.js
Fix pending posts not getting overwritten properly by commit. We don't clear pending posts with RECEIVED_POST. I tried adding it to that but the logic there was confusing and I couldn't get it to work within a reasonable amount of time so I just started using RECEIVED_POSTS like we do in other places.
@enahum not sure if this affects RN but on the webapp it was causing flickering when replying to a post (regular posting was fine).
=> Fix pending posts not getting overwritten properly by commit

src/actions/websocket.js, src/reducers/entities/typing.js, test/reducers/typing.test.js
Instead of having any separate global state and having to deal with cancelling timeouts, for each typing event it now:
1. Fires a TYPING event with a new timestamp
2. After a delay, fires a STOP_TYPING event with the same timestamp
If the reducer receives a STOP_TYPING with a timestamp >= the stored one, it removes it from the store, but if it receives one with an outdated timestamp, it just ignores it (removing the need to cancel anything).
https://mattermost.atlassian.net/browse/RN-183
=> RN-183 Simplified 'user is typing' code to ensure stop events are fired

src/actions/channels.js, src/selectors/entities/channels.js, test/actions/channels.test.js, test/selectors/channels.test.js
Added a better error handling for `createDirectChannel`,  `joinChannel` and `deleteChannel`, now they return an object with `data` or `error` so we don't read the props from the requests (so far with this two actions).
Also modified the selectors for  `getDirectChannels` and `getGroupChannels` in a way that they include data like `display_name`
=> Better error handling for a couple of actions and more info in selectors

src/actions/users.js
Fixes the `EnableCustomEmoji` check in the `loadMe` action.
=> Fix getConfig for CustomEmoji check

src/selectors/entities/posts.js, test/selectors/posts.test.js
Fix regression: No mention highlight for reply threads I start or participate
Jira ticket: [PLT-6892](https://mattermost.atlassian.net/browse/PLT-6892)
This PR was tested on: [Chrome/FF, Mac OS]
=> [PLT-6892] Fix mention highlight for reply threads I start and/or participate

src/selectors/entities/users.js
This is needed so that `@here` is highlighted in posts in the web app
https://mattermost.atlassian.net/browse/PLT-6930
=> PLT-6930 Added at-here to getCurrentUserMentionKeys

src/actions/posts.js, src/actions/websocket.js, src/constants/general.js, test/actions/posts.test.js
I'm proposing this to go into 4.0. The first fix doesn't matter for the web app since it doesn't use this version of the websocket actions, but the second fix will help performance since it'll stop the client from making an unnecessary server call every time a special mention is used in a post
- Loads users that are at mentioned in posts received over the websocket
- Stops trying to get users named `all`, `channel`, or `here` when those mentions are used
This PR was tested on: Chrome/Win 10
=> Minor improvements when getting at mentioned users

src/actions/posts.js
When the server returns a `PostList` struct with no posts, it returns null instead of an empty object for posts
https://mattermost.atlassian.net/browse/PLT-7092
This PR was tested on: Chrome/Win 10
=> PLT-7092 Fixed getProfilesAndStatusesForPosts when passed null

src/actions/general.js, test/actions/general.test.js
Because we had some reports in RN that the server could not be found instead of requiring a server upgrade we are moving back to APIv3 ping in order to detect both scenarios
=> Use apiV3 for ping until we remove APIv3 completely

src/actions/channels.js, src/constants/general.js, src/selectors/entities/channels.js, src/utils/channel_utils.js, test/actions/channels.test.js
Mostly adds some exported functions, but also changes the return type of createGroupChannel so that we can handle it the same as createDirectChannel. This will need a followup PR in the platform repo to handle these correctly
https://mattermost.atlassian.net/browse/RN-152
- Updated unit tests
=> RN-152 Added constants and exported functions needed for creating GMs on mobile

src/selectors/entities/channels.js, src/utils/channel_utils.js
See report here: https://pre-release.mattermost.com/core/pl/p7nzhnqr9pdf887kwronq3kqzh
The repro steps from the ticket were not reproduced. However, when `user.locale` is empty (for whatever reason), JS errors occurred during login. As a result, user hanged up with loading screen.
Jira ticket: [PLT-7231](https://mattermost.atlassian.net/browse/PLT-7231)
This PR was tested on: [Mac/Chrome/FF]
=> [PLT-7231] Set language to en when user.locale is empty

src/selectors/entities/posts.js
Fix thread selector when postsInChannel does not have post Ids for a channel
https://mattermost.atlassian.net/browse/RN-290
=> Fix Thread selector

src/actions/channels.js, src/actions/search.js, src/actions/users.js, src/reducers/requests/search.js, src/utils/channel_utils.js
When searching for posts we need to make sure that we have all the channels profiles and statuses that are involved in the search results
=> Add missing channels, profiles and statuses for search results

src/selectors/entities/general.js, test/selectors/general.test.js
These are for the new settings I'm adding to enable/disable file uploads from the mobile apps. This is needed in the Mattermost Classic app so that's why this isn't in the RN repo
https://mattermost.atlassian.net/browse/PLT-6924
=> PLT-6924 Added selectors for mobile file uploads/downloads

src/actions/posts.js
Remove failed post if commenting on deleted parent post and also dispatch create post request failures to store so UI can access them.
https://mattermost.atlassian.net/browse/PLT-7237
=> PLT-7237 Remove failed post if commenting on deleted parent post

src/client/client4.js
No longer needed because the webapp will only refresh on explicit channel switches and some other special cases and not exactly when the server version changes. I don't think this will have any effect on RN as it's just reverting to old behavior.
https://mattermost.atlassian.net/browse/PLT-7184
=> PLT-7184 Remove special case version checking

src/actions/posts.js
Added a config value to make TownSquare read only for regular users. That means that when TownSquareIsReadOnly=true only admins will be able to post in Town Square. If a basic user posts to town square an error will be displayed: "Town Square is a read-only channel." and the post will be removed.
NOTE: PR for changes to platform: https://github.com/mattermost/platform/pull/7140 
Mac OSX El Capitan 10.11.6: Google Chrome 59, Firefox 54, Safari 10.1.2
=> Remove Post when error returns for TownSquareIsReadOnly=true

src/actions/posts.js, src/reducers/entities/posts.js, test/actions/posts.test.js
This was causing posts in old threads being added to the top of the post list on the webapp, which is noticeable and looks like missing messages without infinite scrolling. RN has infinite scrolling so this would be much more difficult to notice.
This fix just skips adding the posts from the getPostThread actions to the postsInChannel entity to prevent them being displayed in the channel. I spoke with EN about this and he was fine with it and pretty sure it wouldn't affect RN.
https://mattermost.atlassian.net/browse/PLT-7341
Webapp
=> PLT7341 When getting post thread, don't add posts to postsInChannel

src/utils/deep_freeze.js
Some object didn't have a `hasOwnProperty` method and I think it was some field of a field of a `Set`, but I don't think we care enough about debugging the store being mutated on IE11 to fix it
https://mattermost.atlassian.net/browse/PLT-7316
=> PLT-7316 Don't freeze in dev mode on IE11

src/utils/channel_utils.js
Use getUserLocale for getGroupDisplayNameFromUserIds function.
https://mattermost.atlassian.net/browse/PLT-7245
=> PLT-7245 Use getUserLocale for getGroupDisplayNameFromUserIds function

src/utils/post_utils.js
> Currently, when "Enable join/leave messages" is turned off, we don't hide the add/remove messages since they are used to let people know they were added to a channel. 
>
> Propose changing the behaviour to: 
> - Only show the add/remove messages if it is adding the specific user
> - Otherwise, all join/leave and add/remove messages should be hidden 
>
> Ideally, showing the message for the specific user should still trigger a mention, so they are notified about being added to the channel. 
I'm making all add/remove messages hidden when the setting is enabled. The server doesn't send enough information to reliably show only messages for the added / removed user (It doesn't send a user id for them.). This won't have any impact on notifications though since it only filters the display of …
=> PLT-6377: also filter add / remove messages when join / leave filtering is enabled

test/test_helper.js
this allows running the unit tests against a mattermost server running somewhere other than 127.0.0.1.
e.g. MATTERMOST_SERVER_URL="http://mattermost:8065" npm run test
[None]
[None]
This PR was tested on: [docker - node:alpine (node v8.2.1) against a linked mattermost-preview docker container]
=> allow test server to be set via env.

src/client/client4.js
Fixes the following error when making API requests via client4.js from a browser:
```
Fetch API cannot load http://127.0.0.1:8065/api/v4/users/me. Response to preflight request doesn't pass access control
check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the
request's credentials mode is 'include'. Origin 'http://127.0.0.1:8002' is therefore not allowed access.
```
Per `client.js`, don't set credentials to "include" if a bearer token has been provided.
[None]
This PR was tested on: Chromium 60 + Firefox 55 (client bundled for browser via webpack)
=> only set fetch's credentials:include option if no access token

src/client/websocket_client.js
this fixes an issue in some (all?) browser websocket implementations where null protocol
is cast to the string "null", which results in the following header being sent:
Sec-WebSocket-Protocol:null
The websocket spec says that an empty string should be treated as an empty array, and passing
an empty array seems to make both browser and node's 'ws' websocket implementation happy.
[none]
This PR was tested on: [node 8.4.0, chromium 60, firefox 55]
=> set websocket protocols to empty array instead of null

src/actions/posts.js
@jwilander added a flag to the posts reducer so it does not include some received posts in the postsInChannel list but it was causing issues with search on RN, so as a first step I moved that flag to be optional in the `getPostThread` action
This PR is needed for a following PR in RN.
=> Make getPostThread skipAddToChannel a parameter

src/utils/channel_utils.js
Filter out punctuations in sorting channel display name
Jira ticket: [PLT-7365](https://mattermost.atlassian.net/browse/PLT-7365)
=> [PLT-7365] Filter out punctuations in sorting channel display name

src/reducers/entities/posts.js, src/selectors/entities/posts.js, src/utils/post_utils.js
Does two things:
* Check all posts in thread selector (also created a utils function for sorting to support this)
* Check all posts when counting replies in post selector
https://mattermost.atlassian.net/browse/PLT-7498
=> PLT-7498 Fix reply threads not showing up unless loaded in to center channel

src/actions/posts.js, test/actions/posts.test.js
OpenGraph preview links are only shown if the OpenGraph data contains `description` this PR prevents saving the open graph data to the store if there is no need for it (meaning the description is empty)
https://mattermost.atlassian.net/browse/RN-338
=> RN-338 Only save open graph data if it has a description

src/actions/websocket.js
In order to make the RN app display the connected status faster we removed the awaits in the WebSocket reconnect cause they aren't actually needed
https://mattermost.atlassian.net/browse/RN-346
=> Remove awaits from websocket reconnect

src/actions/channels.js, test/actions/channels.test.js
Fun fact, `userIds.map((id) => {id})` returns an array of undefined values because `{id}` looks like an object with an id field, but it can also be a function with a single statement that does nothing and returns nothing.
https://mattermost.atlassian.net/browse/RN-298
=> RN-298 Set profilesInChannel when creating DMs and GMs

src/reducers/entities/posts.js
When we issue a `getPostSince` sometimes the result is empty cause there are no new posts, and we are creating a new object for the state triggering a state change and therefore updates every component that is listening to for that change unnecessarily.
=> Do not update state if no new post were received

src/actions/websocket.js
When reconnecting the WebSocket we always dispatch `WEBSOCKET_SUCCESS`.
Sometimes when reconnecting we won't have loaded the `defaultChannel` for a team yet, this avoids a fatal error
=> Fix WS reconnect flow

src/selectors/entities/preferences.js, test/selectors/preferences.test.js
Currently, it returns a new value when any preference changes, not just the ones that actually matter for the theme
=> Only recalculate getTheme when the actual theme changes

NOTICE.txt, package.json, src/selectors/entities/channels.js, src/selectors/entities/preferences.js, src/selectors/entities/teams.js, src/selectors/entities/users.js, src/utils/channel_utils.js, src/utils/helpers.js, test/selectors/channels.test.js, test/selectors/preferences.test.js, test/selectors/teams.test.js
In order to increase the performance unnecessary re-renders I've created other types of selectors that the regular `createSelector` those are:
* `createIdsSelector` this on is used to shallow compare all the arguments and memoize the result, try and use it only when the selector returns an array of ids.
* `createShallowSelector` shallow compare all the arguments but does not memoize the result.
* `createDeepSelector` use it when you need to deep compare all the arguments, this one won't memoize the result.
Also I've created a few selectors that make use of the above creators to get sorted team Ids, different type of channels, mentions count, teams count, etc..
https://mattermost.atlassian.net/browse/RN-415
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated …
=> Selectors to improve performance for listing channels

src/actions/channels.js
When logging in `markChannelAsRead` is looking for a channel but the store hasn't been filled yet, this will make sure that the channel exists before attempting to dispatch an action.
=> Fix markChannelAsRead on login

src/selectors/entities/files.js
Looks like sometimes when getting the files ids for a post it can be undefined cause we haven't retrieve the file from the server yet.
https://mattermost.atlassian.net/browse/RN-423
=> Only return existing file ids for post

src/action_types/posts.js, src/actions/posts.js, src/reducers/entities/posts.js
This allows us to add a post to the posts entity without affecting the postsInChannel. This fixes a bug previously fixed in the webapp where another user editing a post that your client doesn't have would cause it to appear at the bottom of the channel.
https://mattermost.atlassian.net/browse/PLT-7819
This PR was tested on: webapp
=> PLT-7819 Split RECEIVED_POST into RECEIVED_NEW_POST and RECEIVED_POST

src/actions/channels.js, src/client/client4.js, test/actions/channels.test.js
- Add post' root ID to APIv4 `addChannelMember` to render added user (as system post) at RHS. Feature is requested while testing `webapp` https://github.com/mattermost/mattermost-webapp/pull/149#pullrequestreview-72349879
Note: Only client4 was updated.
Jira ticket: [PLT-7362](https://mattermost.atlassian.net/browse/PLT-7362)
This PR was tested on: Chrome/FF(s), Mac OS Sierra]
=> [PLT-7362] Add post root ID to client4 addToChannel to render added user (as system post) at RHS

src/selectors/entities/channels.js, src/selectors/entities/posts.js
the getLastPostPerChannel selector was set as undefined when used in the channel selectors, by converting it to a function it no longer causes failures like
```bash
Error: Selector creators expect all input-selectors to be functions, instead received the following types: [function, function, function, function, function, function, undefined]
at getDependencies (/home/ubuntu/workspace/mattermost-mobile-pr/src/github.com/mattermost/mattermost-mobile/node_modules/reselect/lib/index.js:53:11)
at /home/ubuntu/workspace/mattermost-mobile-pr/src/github.com/mattermost/mattermost-mobile/node_modules/reselect/lib/index.js:71:24
at Object.<anonymous> (/home/ubuntu/workspace/mattermost-mobile-pr/src/github.com/mattermost/mattermost-mobile/node_modules/mattermost-redux/selectors/entities/channels.js:18 …
```
=> Switch getLastPostPerChannel from selector to function

README.md, package.json, src/actions/teams.js, src/actions/websocket.js, test/actions/admin.test.js, test/actions/channels.test.js, test/actions/emojis.test.js, test/actions/files.test.js, test/actions/general.test.js, test/actions/integrations.test.js, test/actions/jobs.test.js, test/actions/posts.test.js, test/actions/preferences.test.js, test/actions/search.test.js, test/actions/teams.test.js, test/actions/users.test.js, test/actions/websocket.test.js, test/test_helper.js, test/test_store.js
The tests are far from perfect and still need a lot of work but this is a good first step forward. Waiting on #265. 
`npm test` will now mock the server. To run against a real server `npm run test-no-mock` can be used (server must have a system admin user with the email `redux-admin@simulator.amazonses.com` and the password `password1`).
Still to do in this PR:
Still to do in a later PR:
https://mattermost.atlassian.net/browse/PLT-7799
=> PLT-7799 Mock server for all unit tests

src/selectors/entities/posts.js, test/selectors/posts.test.js
When I first wrote this I didn't know `postsInChannel` was sorted. So now instead of iterating through posts, this just iterates through channels.
N/A
This PR was tested on: `npm test`
=> dm autohiding optimization

Makefile
The command "command", doesn't exist in Linux (at least in Arch Linux), and
which works here for both operating systems. Anyway, this check is needed?
mattermost-webapp haven't this check, I'm 5/5 about it.
=> Fix .npminstall Makefile task in linux

src/selectors/entities/posts.js, test/selectors/posts.test.js
Added a new post selector that returns the most recent post in a channel, while respecting the user's join/leave setting
https://mattermost.atlassian.net/browse/PLT-7974
This PR was tested on: [Chrome, Mac OS]
=> PLT-7974: +:emoji: reactions are added to (hidden) system messages

src/utils/channel_utils.js
This goes along with my PR to reduce duplication between the web app and redux versions of ChannelUtils since I need these helper functions in the web app, and the sorting function was just bugging me since it was overly complicated
=> Clean up channel ordering logic and export some helpers

src/reducers/entities/teams.js
When marking a channel as read multiple times the team member message and/or mention count was able to go below 0, with this PR we are making sure that the lowest value is zero
=> Prevent team member message and mention count to go below 0

src/action_types/channels.js, src/actions/channels.js, src/actions/websocket.js, src/reducers/entities/channels.js
* When creating a post from the same client we already have the post so there is no need to replace the current post in the store nor we need to make the channel visible as the post was created from the same client meaning that the channel is already visible.
* If the post was made by the same user we don't need to fetch profiles or status for the current.
* Finally we want to make sure that if you receive a post and you are on the same channel marking the channel as read also sets the last_viewed_at of the channel that way we prevent the `new message indicator` to appear or to flash if later on you receive a `CHANNEL_VIEWED` websocket event
=> Improve new posts received through the WS

src/selectors/entities/channels.js
It's sometimes returning null instead of an empty array, causing the code using this to error out if it's not checking for null. I could fix it there too, but I'd rather be consistent with return types wherever possible
https://mattermost.atlassian.net/browse/RN-485
=> RN-485 Stopped returning null post ID arrays when not logged in

src/store/initial_state.js
Fixes postsInChannel initial_state key.
=> Fix postsInChannel key in initial_state

src/selectors/entities/preferences.js, test/selectors/preferences.test.js
Because the current version will always replace missing colours with the value from the Mattermost theme instead of finding the correct version for whichever system theme the user is using.
=> Improved getTheme to fix missing colours for other system themes

src/actions/channels.js, src/actions/websocket.js, src/constants/websocket.js, test/actions/channels.test.js
Currently we were using `markAsUnread` to just reset the *msg_count* and *mention_count*  from the channel and then subtract it from the team, but that was causing the channel to be marked as read only in the same client, and the `viewChannel` action was used to set the channel `last_viewed_at` in the client and to inform the server that the channel was actually viewed.
Now `markAsUnread` does reset the counts but also informs the server that the channel has been read and `viewChannel` will only update the `last_viewed_at` locally for the client that way we have better control for displaying or not the **new messages** indicator.
This PR also adds a missing WebSocket event to mark the channel as read when it was read in another device/window/tap/app/etc …
=> Improve marking the channel as read

src/client/client4.js
If a global analytics context is defined used that instead of the default context
https://mattermost.atlassian.net/browse/RN-526
=> Replace analytics context with global context

src/actions/general.js, src/client/client4.js
Need this to update https://github.com/mattermost/mattermost-mobile/pull/1192
Note: This will also ensure that the right diagnosticId aka `serverId`  is sent with every track event to segment on the webapp which was not the case.
=> Ensure serverId (diagnosticId) is always sent to segment

src/selectors/entities/posts.js
Fix selectors for initial load of create_post redux container as posts will not be available on the first call
=> Fix selectors for initial load of create_post redux container 

src/actions/channels.js
This is only part of the solution, the other part is in mattermost/mattermost-webapp#365
This is part of the fix for enter directly in the message when `/groupmsg` is executed (solve the same problem for `/msg` command)
[PLT-7111](https://mattermost.atlassian.net/browse/PLT-7111)
=> Allow to join group and direct messages

src/actions/users.js, src/selectors/entities/channels.js, src/utils/channel_utils.js, test/utils/channel_utils.test.js
This makes DMs auto-close when the other user is deactivated.
https://mattermost.atlassian.net/browse/PLT-7917?filter=14400
This PR was tested on: Chrome/Firefox on Mac
=> PLT-7917: Auto-close archived dms

test/actions/posts.test.js
Temporarily disable flaky test on "Actions.Posts retry failed post" due to optimistic actions being difficult to test. Further investigation and fix is required.
https://pre-release.mattermost.com/core/pl/rdfbpqdecjryjxst6h58qdxoac
=> Disable test on "Actions.Posts retry failed post"

src/actions/posts.js
Adds 2 properties that will be utilized by the mobile application for timing out API calls.
Here's the PR on the mobile side for more context.: https://github.com/mattermost/mattermost-mobile/pull/1242
@miguelespinoza
=> Add canTimeout flag for mobile

src/action_types/posts.js, src/actions/posts.js, src/reducers/requests/posts.js, test/actions/posts.test.js
Add resetCreatePost to make PostDeletedModal to show always after replying to a deleted post
Jira ticket: [PLT-7829](https://mattermost.atlassian.net/browse/PLT-7829)
This PR was tested on: Chrome/FF on Mac
=> [PLT-7829] Add resetCreatePost to make PostDeletedModal to show always after replying to a deleted post

src/actions/websocket.js, test/actions/websocket.test.js
Currently we are modifying the url to connect the WebSocket, we replace http(s) with ws(s) protocols, and it seems that is causing some issues were the server cannot validate the origin.
This PR removes the replacement and leave the url as is and lets the client underlying WebSocket library to handle it.
Closes mattermost/mattermost-mobile/issues/1263
This PR was tested on: Mobile app Android and iOS
=> Do not modify WS protocol

src/actions/channels.js, src/constants/preferences.js, src/selectors/entities/channels.js, src/utils/channel_utils.js
This makes channels always show up in the side-bar if they have unread messages.
To prevent them from disappearing immediately once you view those unread messages, it also makes channels stay around for approximately 7 days after you last viewed them.
See conversation here: https://pre-release.mattermost.com/core/pl/e4fjurdmcpd8783qx9q4t9573r
https://mattermost.atlassian.net/browse/PLT-8321
N/A
This PR was tested on: macOS, Chrome
=> PLT-8321: show channels if unread or recently viewed

.eslintrc.json, src/actions/channels.js, src/actions/search.js, src/actions/teams.js, src/actions/users.js, src/actions/websocket.js, src/client/client.js, test/actions/channels.test.js, test/actions/posts.test.js, test/actions/search.test.js, test/actions/websocket.test.js
I came a couple places where we're awaiting requests in sequence instead of doing them in parallel, so I took a pass over all of the actions to fix wherever I could find that we were doing it unnecessarily. There were also a few unnecessary awaits that I got rid of where we were awaiting on a value that had already been resolved (which is a noop)
=> Make requests run in parallel wherever possible

src/selectors/entities/posts.js
Select correctly the last user post (system and ephimeral messages are ignored)
[PLT-8532](https://mattermost.atlassian.net/browse/PLT-8532)
This PR was tested on: Linux Firefox 57.0.3
=> PLT-8532: Select correctly the last user post in a channel

src/actions/admin.js, src/actions/channels.js, src/actions/emojis.js, src/actions/files.js, src/actions/general.js, src/actions/helpers.js, src/actions/integrations.js, src/actions/posts.js, src/actions/search.js, src/actions/teams.js, src/actions/users.js
Ensure that logout is run only once if we get a 401 response, meaning that the user has to be logged in before performing the `forceLogoutIfNecessary` action
=> Only logout once if status code is 401

src/actions/emojis.js
There is a very strange case where trying to load more than 4K emoji's cause the "Android" app to crash but changing the action to dispatch all the emoji's at once seems to fix it.
found by @stephenkiers who can share the database and data folder to test it
https://mattermost.atlassian.net/browse/ICU-626
=> Fix load emojis into the store

src/selectors/entities/channels.js
Not add favorite channel when the channel is not accessible (It happens time to time because a race condition).
=> More robust favorite channel selection

src/selectors/entities/emojis.js, test/selectors/emojis.test.js
Add selector to get custom emoji ids sorted by name.
Part of https://mattermost.atlassian.net/browse/ABC-96
=> ABC-96 Add selector to get custom emoji ids sorted by name

src/actions/channels.js
When receiving a plain message and not a mention the app was crashing because `mentions` was undefined
=> Add defensive code for markChannelAsUnread

src/reducers/entities/teams.js, src/selectors/entities/users.js, test/selectors/users.test.js
This is needed since the web app has no idea which mention keys need to be case sensitive when highlighting them in the text. Before, it used to return an array of mention keys like `['@user', 'FirstName']` whereas it'll now return `[{key: '@user'}, {key: 'FirstName', caseSensitive: true}]`
https://mattermost.atlassian.net/browse/ICU-631
=> ICU-631 Added whether mention is case sensitive to getCurrentUserMentionKeys

src/selectors/entities/posts.js
This commit was applied into the webapp-4.6 branch (here #358), but never in the master
branch (maybe there are other commits with the same problem, generating
regressions).
[PLT-8532](https://mattermost.atlassian.net/browse/PLT-8532)
=> PLT-8532: Select correctly the last user post in a channel (#358)

src/selectors/entities/channels.js, test/selectors/channels.test.js
In order to comply with the spec and keep the channel in the unread section of the sidebar when the option is enabled, the UnreadChannelIds selector has been modified to receive an optional channelId to be kept in the list
https://mattermost.atlassian.net/browse/ICU-621
=> [ICU-621] Keep channel as unread

src/selectors/entities/channels.js, test/selectors/channels.test.js
Last time I added an option to the `getUnreadChannelIds` that included the last selected unread channel id that was being shown in the `UNREADS` section of the sidebar but it wasn't taking into account if the channel had a mention when sorting.
This PR uses the same selector and modifies `getSortedUnreadChannelIds` so if the last selected unread channel had a mention it now takes it into account to maintain the sorting.
https://mattermost.atlassian.net/browse/ICU-621
=> Sort unread channels taking into account if the last channel had a mention

src/reducers/entities/teams.js, test/reducers/entities/teams.test.js
- Remove team object from entities.teams.myMembers when team is deleted
Jira ticket: [PLT-8494](https://mattermost.atlassian.net/browse/PLT-8494)
This PR was tested on: [Chrome/FF browsers, MacOS]
=> [PLT-8494] Remove team object from entities.teams.myMembers when team is deleted

src/action_types/emojis.js, src/actions/emojis.js, src/actions/posts.js, src/reducers/entities/emojis.js, test/actions/emojis.test.js, test/actions/posts.test.js
When receiving posts, request custom emojis we might be missing, similar to how at-mentions are handled.
Two slightly odd aspects I should point out:
* mattermost-redux needs to know what system emojis are, so this exposes an action to set those. It's not being stored in state or a reducer because they're essentially a constant
* A new reducer `nonExistentEmoji` tracks any emojis we've tried to request but got a 404 response for.  This is needed to by the UI components to discover whether or not to show the original text instead of a placeholder but it also helps cut down on repeating requests to the server for emoji we know don't exist
https://mattermost.atlassian.net/browse/ABC-93
=> ABC-93 Load needed custom emojis for posts

src/actions/channels.js, src/client/client4.js, test/actions/channels.test.js, test/test_helper.js
See https://github.com/mattermost/mattermost-server/pull/8163
=> ABC-79: add autocomplete channels endpoint

src/constants/posts.js, src/utils/post_utils.js, test/utils/post_utils.test.js
I feel like there was a ticket for this, but I can't find it now. The messages for joining/leaving/being invited to/being removed from a team are always shown even if you turn off join/leave team messages in your settings.
=> Hid join/leave team messages based on user settings

src/reducers/entities/admin.js, src/reducers/entities/channels.js, src/reducers/entities/emojis.js, src/reducers/entities/integrations.js, src/reducers/entities/jobs.js, src/reducers/entities/search.js
I didn't like that we were using `const newState = {...state}` outside of case statements. That means that we are creating a copy of the state in memory for every one of those reducers for every reducer called, even when it will never be used.
I think this is better practice, better memory usage, and *very slightly* better js perf.
=> Remove unnecessary state duplications when reducers are fired

.eslintrc.json, src/utils/helpers.js
This adds a console.warn message in development mode when backwards compatible code is ready to be reverted.
Just to ensure we don't have unneeded code sitting in the project.
Also added arrow funcs to eslint
=> Is minimum server version expiration notification

src/actions/roles.js
Correctly store pending roles to ensure correctly loading after version is available.
This PR was tested on: [Firefox 58, Arch Linux]
=> Fix roles loading

src/selectors/entities/preferences.js, test/selectors/preferences.test.js
Uses the `DefaultTheme` from `config.json` if required and present.
[XYZ-71](https://mattermost.atlassian.net/browse/XYZ-71)
* Chrome browser, macOS
=> XYZ-71: Uses DefaultTheme from server-side config in some cases.

src/utils/emoji_utils.js, test/utils/emoji_utils.test.js
Emojis surrounded by other text are technically supported (see `asdf:goat:asdf` which renders as asdf:goat:asdf on GitHub and Slack) although it's difficult to get that to work on Mattermost because of our aggressive autolinking which should be going away in 5.0
https://mattermost.atlassian.net/browse/ICU-736
=> ICU-736 Try to load emojis surrounded by other text

src/actions/posts.js, src/reducers/entities/posts.js
In the mobile app we were using the `canTimeout` to track the effect of the optimistic action when creating new posts but this was causing some false/positives and then the post was created twice.
I'm removing the option to handle the timeouts and letting it fail if it actually fails without introducing a race condition by tracking the pending post ids.
When a new post is created we will add the pending post id to the list until the post is actually created.
In case we do not have a response from the server while the post is in a pending state and the app is sent to the background the pending post is cleared from the store and if in fact the post was created on the server it will be received with the next get posts request.
https://mattermost.atlassian.net/browse/ICU-680
mobile-PR: …
=> Track pending posts for removal

src/selectors/entities/general.js
This is temporary for development, when it code go into master must be using the 4.8.0 version as "cut" version for new permissions.
=> Reducing temporary the version to use new permissions to 4.6.0

src/actions/websocket.js
This adds alternate websocket URL support from: mattermost/mattermost-server#8307
=> Adding alternate websocket URL support.

src/client/websocket_client.js
Added an additional else statement for resolving `wsClient.initialize` returned promise when a `firstConnectCallback` doesn't exist. Will now call promise resolve if websocket connection hasn't failed and a `firstConnectCallback` function isn't specified.
Fixes unresolved promise when `wsClient.initialize` called without a `firstConnectCallback` set.
Added an additional else statement for resolving `wsClient.initialize` returned promise when a `firstConnectCallback` doesn't exist. Will now call promise resolve if websocket connection hasn't failed and a `firstConnectCallback` function isn't specified.
[A brief description of what this pull request does.]
closes #413 
Non-applicable
This PR was tested on: 2015 Macbook Pro 15, MacOS 10.13.3, Mattermost 4.7.1
=> Fixed unresolved returned promise from wsClient.initialize

src/actions/websocket.js
When you receive a notification post in your current channel, you must mark as
read in the client, but in the server too, because this notification must be
mark as unread in mobile devices.
Related the same problem fixed in mattermost/mattermost-webapp#869 but without dependency between PRs.
I haven't tested it manually because I haven't a development environment with
push notifications.
[MM-7188](https://mattermost.atlassian.net/browse/MM-7188)
=> MM-7188: Update unread on server when receive a notification on your channel

src/actions/general.js, src/actions/websocket.js, src/client/client.js, src/client/client4.js, src/constants/general.js, src/constants/websocket.js, test/actions/websocket.test.js
Respond to the new `config_changed` and `licensed_changed` websocket events to update the Redux store. Note that this only impacts the mobile app, since the webapp has its own websocket processing logic. (Corresponding changes to the webapp are are forthcoming.)
https://mattermost.atlassian.net/browse/MM-8604
This PR was tested on: iPhone 6 (Simulator)
=> MM-8604: process config/license websocket events

src/actions/general.js
When falling back and attempting to ping the server with APIv3 is making the app crash as the server url for API v3 is not set, this PR fixes it
https://mattermost.atlassian.net/browse/MM-9740
=> MM-9740 Make sure APIv3 has a server url before attempting to ping

src/selectors/entities/channels.js, test/actions/posts.test.js
This fixes the asterisk not showing up for the current channel when the browser/tab isn't focused.
https://mattermost.atlassian.net/browse/MM-9754
=> MM-9754 Include current channel in getUnreads selector

src/utils/theme_utils.js, test/utils/theme_utils.test.js
This is a followup to my last PR to better support different types of colour values. Previously, we just supported hex codes as inputs and rgba values as outputs, but now we'll support a mix of those so you can combine these functions.
I've also made sure to treat the rgb values as integers so that they're compatible with CSS
=>  Updated blendColors and changeOpacity to work with rgba colours

src/actions/websocket.js, src/constants/websocket.js, src/selectors/entities/channels.js, src/utils/channel_utils.js
This is the redux part to sort the muted channels needed with the `mute` feature
[Mute Channel WebApp PR here](https://github.com/mattermost/mattermost-webapp/pull/196)
https://github.com/mattermost/mattermost-server/issues/7617
=> PLT-4340 Sort Muted channels

src/constants/posts.js, src/types/posts.js, test/utils/post_utils.test.js
Add system message type for converting a channel from public to private
Server PR: https://github.com/mattermost/mattermost-server/pull/8501
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/418
Github issue: [GH-7775](https://github.com/mattermost/mattermost-server/issues/7775)
=> [GH-7775] Add system message type for converting a channel from public to private

src/reducers/entities/posts.js, src/selectors/entities/posts.js, src/store/initial_state.js, test/actions/posts.test.js, test/reducers/entities/posts.test.js, test/selectors/posts.test.js
After some profiling with 5000 posts loaded locally, the major bottleneck was in the `formatPostInChannel` function.
We were spending a ton of time in there looping through every single post we had locally to do two things:
* Check if the current user started or replied to the thread of the post in question (needed for notification purposes)
* Count the number of replies in the thread
While debugging, removing this one loop took switching to a channel with 5000 posts from taking ~60 seconds to just ~200ms.
To remove the loop without functionality loss, I added a new reducer `postsInThread`. It is very similar to the existing `postsInChannel` reducer, except instead of tracking posts in channels it was for tracking posts in threads.
Here's some profiling numbers showing the improvements on …
=> MM-9801 Performance improvements for large numbers of posts

src/selectors/entities/channels.js
Selectors to check if the current channel isReadOnly or if a channel isReadOnly, byId or by channel passed. In the current logic only TownSquare can be ReadOnly when `ExperimentalTownSquareIsReadOnly=true`.
NOTE: For the ticket to make TownSquare read only it was recommended to move the isReadOnly logic to redux:
https://github.com/mattermost/mattermost-webapp/pull/831
This PR was tested on: MacOS HighSierra 10.13.3
via @dmeza
=> Add selectors to check if current channel and a channel is ReadOnly.

package.json
As discussed [here](https://pre-release.mattermost.com/core/pl/67at1p6esbbn3xjkogy7gefm9e), this won't fix the problem of Jenkins sometimes using the wrong version of mattermost-redux, but it should mitigate it a bit since flow-copy-source isn't needed for most development work
=> Moved flow-copy-source to a dev depencency and removed it from build

src/utils/file_utils.js, test/utils/file_utils.test.js
Expose `getFileDownloadUrl` for use by the webapp in generating a download link for a file (vs. something that might render within the browser).
https://mattermost.atlassian.net/browse/MM-9941
This PR was tested on: OSX
=> MM-9941: expose getFileDownloadUrl

src/actions/emojis.js
Skip logging 404s on missing custom emoji. This was only an issue if developer mode was enabled.
https://mattermost.atlassian.net/browse/MM-10010
=> MM-10010: skip logging 404s on missing custom emoji

src/reducers/entities/posts.js
Without this fix comment countners get reset on mobile with new redux
\+ the mobile app needs update to middleware & initial_state, but this is not in scope of this PR
This PR was tested on: [Device name(s), OS version(s)] 
galaxy s7, android 7
=> Fix postsInThread being reset to null when getPostsSince(...) returns empty list

src/selectors/entities/users.js, test/selectors/users.test.js
This is in support of a soon-to-be-summited PR to the webapp to remove the use of `getState` within render functions of the admin console.
https://mattermost.atlassian.net/browse/MM-9831
This PR was tested on: unit tests, Chrome
=> MM-9831: expose getProfiles for use in the admin console

src/actions/users.js, src/client/client.js, src/client/client4.js
Replacing hash usage with token for invitations. It depends on the PR mattermost/mattermost-server#8604
[MM-9779](https://mattermost.atlassian.net/browse/MM-9779)
=> Replacing hash usage with token for invitations

src/actions/errors.js, test/actions/errors.test.js
If an error is received that appears to be from the server, don't send it back to the server as a client-side error.
The unit tests for this were a pain. `nock` is very much unhelpful over simply mocking out the client in this case. I'm looking forward to `jest` which I believe makes this much easier.
https://mattermost.atlassian.net/browse/MM-10181
=> MM-10181: don't duplicate server errors

src/actions/posts.js, src/reducers/entities/posts.js, src/selectors/entities/posts.js, test/reducers/entities/posts.test.js, test/selectors/posts.test.js
A long time ago, the webapp managed its own deduplication of retried posts itself by relying on the resolved/rejected promise returned by the client. That was later abstracted away under a dispatch, resulting in the webapp being unable to distinguish success/failure, and effectively allowing the user to mash the "Retry" button and duplicate posts.
This moves that logic into Redux by maintaining a `sendingPostIds` array (analogous to `pendingPostIds`, and ignoring any attempts to `createPost` if it's already sending. Note that this doesn't impact the `createPostImmediately` path -- you can't even retry on iOS, and I'm hesitant to touch that code at present.
I've added unit tests for the selectors and reducers... but cannot for the life of me add a unit test for the action itself without …
=> MM-8528: manage sendingPostIds and avoid double-sending

src/selectors/entities/teams.js, test/selectors/teams.test.js
Make getJoinableTeams returns a sorted array of teams
This is as per comment on webapp - https://github.com/mattermost/mattermost-webapp/pull/1073#discussion_r184318356
none
This PR was tested on: [mobile app on iOS 11.2/iPhone 8 simulator, Chrome/FF on MacOS]
=> Make getJoinableTeams return a sorted array of teams

package.json
npm doesn't automatically convert `npm do-something` into `npm run do-something` like yarn did
=> Fix npm run dev commands

src/actions/posts.js, test/actions/posts.test.js
Some pages (like a GitHub PR with no description set) include an empty OpenGraph description, so this null check prevented the OpenGraph data for those pages from being saved into the store and eventually shown in a preview
https://mattermost.atlassian.net/browse/MM-10360
=> MM-10360 Render OpenGraph previews for pages with an empty description

src/utils/user_utils.js, test/utils/user_utils.test.js
In some cases the display name wasn't showed because it generates an empty
string, now if that happens it use the username as final fallback.
[MM-10464](https://mattermost.atlassian.net/browse/MM-10464)
This PR was tested on: [Firefox, Arch Linux]
=> MM-10464: Handle all cases display username

src/selectors/entities/roles.js, test/selectors/roles.test.js
The team member and channel member objects can be loaded without a `roles` key. This change checks for the key prior to attempting access.
[MM-10432](https://mattermost.atlassian.net/browse/MM-10432)
This PR was tested on: Chrome desktop, macOS
=> MM-10432: Don't access roles before they're loaded.

src/reducers/entities/search.js
Sometimes when flagging a post it can be added twice to the flagged results this PR prevents that from happening
https://mattermost.atlassian.net/browse/MM-10333
=> Prevent duplicate flagged posts

src/actions/roles.js, src/store/initial_state.js
Sets serialization is not supported by the standard `JSON.stringify`, so, to be sure, I removed any "Set" used for roles in the store.
I'm not 100% sure that is fixing the problem.
[MM-10454](https://mattermost.atlassian.net/browse/MM-10454)
=> MM-10454: Removing Set usage in store for roles

src/actions/posts.js, src/constants/posts.js, src/reducers/entities/posts.js, src/selectors/entities/posts.js, src/utils/helpers.js, src/utils/post_utils.js, src/utils/user_utils.js, test/test_helper.js, test/utils/post_utils.test.js
- This PR combine all system messages of type "add/join/leave/remove from channel/team".
- These system messages will be marked as deleted at redux store with `"delete_at: 1, "state": "DELETE"`.
- Those consecutive system messages will combine into a single post with following new/modified fields: 
```
"message": "",
"type": "system_combined_user_activity",
"user_activity_posts": [post1, post2],
"system_post_ids": ["post_id_1", "post_id_2"],
```
- `system_post_ids` is used for deleting system post
- `user_activity_posts` is used for rendering on client side
Note: This will have breaking change on mobile RN since system messages will be deleted and combine post don'e have meaningful `message` value (it's empty). I'll submit separate PR for mobile RN.
Jira ticket: …
=> [MM-3996] Improved (add/join/leave/remove from channel/team) system messages 

src/actions/channels.js, src/actions/teams.js, src/reducers/entities/users.js, test/actions/websocket.test.js
Include "id" to data for UserTypes actions - RECEIVED_PROFILE_(NOT)_IN_TEAM / RECEIVED_PROFILE_(NOT)_IN_CHANNEL
Webapp - https://github.com/mattermost/mattermost-webapp/pull/1214
Mobile RN - https://github.com/mattermost/mattermost-mobile/pull/1676
Jira ticket: [MM-10455](https://mattermost.atlassian.net/browse/MM-10455)
This PR was tested on: [Webapp - MacOS Chrome/FF, Mobile RN - iOS 11.2 iPhone 8 simulator]
=> [MM-10455] Include "id" to data for UserTypes actions - RECEIVED_PROFILE_(NOT)_IN_TEAM / RECEIVED_PROFILE_(NOT)_IN_CHANNEL

src/selectors/entities/users.js
The `profileSet` might reference a user id that is not yet known to the `profiles` -- in that case, filter out the profile and wait for the reducer to update with same.
https://mattermost.atlassian.net/browse/MM-10666
=> MM-10666: ignore unknown profiles in `sortAndInjectProfiles`

src/selectors/entities/users.js, test/selectors/users.test.js
This cherry-picks my changes from the `webapp-4.10` branch to `master`. Oddly, I seem to have failed to include the corresponding unit tests in that PR, so I've recovered them from my reflog and included them here instead.
https://mattermost.atlassian.net/browse/MM-10666
=> MM-10666: ignore unknown profiles in `sortAndInjectProfiles` (#505)

src/constants/permissions.js
Add manage_emojis and manage_others_emojis to the permissions constants.
[MM-8853](https://mattermost.atlassian.net/browse/MM-8853)
=> MM-8853: Add manage_emojis permissions

src/actions/users.js, src/utils/post_utils.js, test/utils/post_utils.test.js
Fix missing username on combined system messages by supporting backward compatibility on `addedUsername` props when user was added to the channel or team.
Jira ticket: [MM-10727](https://mattermost.atlassian.net/browse/MM-10727)
This PR was tested on: [MacOS/Chrome/FF, iOS simjulator and Android emulator]
=> [MM-10727] Fix missing username on combined system messages

src/client/client4.js, src/store/configureStore.dev.js, src/store/configureStore.prod.js
Set's Client4 online status,  when `this.online == false` avoid making fetch calls.
Redux actions will reconcile the error.
This is to avoid the `OutOfMemoryError` caused on Android.
https://mattermost.atlassian.net/browse/MM-10773
=> Disable fetch calls when offline

src/utils/helpers.js
Prevent developer headaches by warning about removing backwards compatibility less often.
None.
=> Warn less often about backwards compatibility

src/store/configureStore.dev.js
We were loading the redux-devtools during tests, and depending on the speed
of the tests, sometimes when the socket get timeout and the scheduler give it a
chance, it prints out the socket error. It was happening in 2 specific
permissions tests because where was two "setTimeout" calls to explicitly wait
until the next cycle.
[MM-10763](https://mattermost.atlassian.net/browse/MM-10763)
[MM-10874](https://mattermost.atlassian.net/browse/MM-10874)
=> MM-10763 and MM-10874: Not load remove-redux-devtools on tests

src/selectors/entities/posts.js, src/utils/post_utils.js, test/utils/post_utils.test.js
This filters out any combined system message that isn't an action performed by the current user or affecting the current user. The client will be responsible for figuring out what part of that combined system message needs to be rendered.
https://mattermost.atlassian.net/browse/MM-10888
=> MM-10888 Filter out combined system messages not mentioning current user

README.md, webpack.config.js
Remove the client.js (version 3) from the webpack.config.js.
=> Fix make bundle command

.eslintignore, build/Jenkinsfile
In order to test I need get this merged :)
jira: https://mattermost.atlassian.net/browse/MM-7495
=> Add initial JenkinsFile for redux

src/selectors/entities/users.js, test/selectors/users.test.js
Add makeGetProfilesByIdsAndUsernames selector to prevent async calls from mobile RN and Webapp
None but was reported on pre-release:
- https://pre-release.mattermost.com/core/pl/ofbk3xz7jp8u38ckm78usbe5ih
- https://pre-release.mattermost.com/core/pl/ck75xrjispd8mdn4h9edzw1y8c
This PR was tested on: [MacOS/Chrome, iOS simulator and Android emulator]
=> Add makeGetProfilesByIdsAndUsernames selector

src/utils/post_utils.js, test/utils/post_utils.test.js
The issue with duplicated user is that it adds both user ID and username.
This fix only consider adding user to a list when addedUserId is available.
Note: (Webapp and mobile RN's redux commit will be updated once this is merged.)
Jira ticket: [MM-10929](https://mattermost.atlassian.net/browse/MM-10929)
This PR was tested on: [MacOS/Chrome/FF, iOS simulator]
=> [MM-10929] Only consider adding user to a list when addedUserId is available

src/actions/websocket.js
Looks like I broke this in 1.9.1 because I didn't understand the return type of the client
https://mattermost.atlassian.net/browse/MM-10996
=> MM-10996 Fixed getting post thread after receiving posts over the websocket (1.9.2)

src/actions/websocket.js
Looks like I broke this in 1.9.1 because I didn't understand the return type of the client
https://mattermost.atlassian.net/browse/MM-10996
=> MM-10996 Fixed getting post thread after receiving posts over the websocket

src/client/websocket_client.js
By preventing the WebSocket to try and connect when the url is malformed we avoid the Signal 6 crashes seen on iOS
=> If the websocket url is malformed do not attempt to connect

src/constants/general.js, src/selectors/entities/channels.js, src/selectors/entities/sidebar.js, src/utils/channel_utils.js, test/selectors/channels.test.js
Adds support for sidebar reorganization.
PR for webapp: https://github.com/mattermost/mattermost-webapp/pull/1374
Selectors have been modified to support 2 changes.
Grouping:
* by_type, never, unreads_at_top, favorites_at_top
Sorting:
* recents, alphabetical order
=> New selectors for sidebar reorganization

src/selectors/entities/channels.js, test/selectors/channels.test.js
Adds new selector to filter post IDs using conditions involving associated channels.
Need as part of [MM-11070](https://mattermost.atlassian.net/browse/MM-11070).
iPhone 6, iOS 11.4 emulator
=> MM-11070: Adds post ID filter selector.

src/actions/websocket.js
Porting the changes made in https://github.com/mattermost/mattermost-webapp/pull/527 to the websocket code used by the mobile app so that the locale is properly updated when the user updates their settings from elsewhere. The displayed locale won't update immediately, but it will now be properly available when the app restarts.
https://mattermost.atlassian.net/browse/MM-11256
=> MM-11256 Properly get current user when user is updated

src/selectors/entities/files.js, src/utils/file_utils.js, test/utils/file_utils.test.js
Sort fileInfos by "create_at" (if not created at the same time) or by "name"
Jira ticket: [MM-10621](https://mattermost.atlassian.net/browse/MM-10621)
This PR was tested on: [Webapp on MacOS/Chrome, RN on iOS simulator/Android simulator]
=> [MM-10621] Sort fileInfos by "create_at" (if not created at the same time) or by "name"

src/actions/channels.js, src/actions/search.js, src/client/client4.js, test/actions/channels.test.js, test/actions/search.test.js
Allow to get channels when are deleted from the getChannelByName and
getchannelByNameForTeamName API endpoints.
[MM-11066](https://mattermost.atlassian.net/browse/MM-11066)
=> MM-11066: Allow to get channels when are deleted

src/utils/post_utils.js, test/utils/post_utils.test.js
Add actor ID to user_activity_props of system_remove_channel combined message to easily filter when hiding/showing join/leave messages of the current user 
Jira ticket: [MM-10918](https://mattermost.atlassian.net/browse/MM-10918)
This PR was tested on: [MacOS/Chrome/FF, iOS simulator / Android emulator]
=> [MM-10918] Add actor ID to props of system_remove_channel combined message

src/reducers/entities/channels.js, test/actions/channels.test.js
When the channel is archived mustn't be delete from the store. Now
archived channels are part of the interface and we will have them in the
store after the archive.
[MM-11530](https://mattermost.atlassian.net/browse/MM-11530)
=> MM-11530: When the channel is archived mustn't be delete from the store

src/selectors/entities/typing.js, src/utils/user_utils.js, test/utils/user_utils.test.js
Adding a new param(useDefaultUserName) to avoid someone string from returning for cases where we need to show loader.
[MM-11051](https://mattermost.atlassian.net/browse/MM-11051)
=> [MM-11051]: Add new param to displayUsername to circumvent defaultName

src/utils/post_utils.js, test/utils/post_utils.test.js
Rearrange postTypePriority of combined system messages which makes the `leave_channel/team` shows first before  `remove_from_channel/team` 
As commented and confirmed here https://github.com/mattermost/mattermost-mobile/pull/1955#discussion_r206662959
Jira ticket: [MM-10918]()
=> [MM-10918] Rearrange postTypePriority of combined system messages

src/actions/channels.js, src/actions/websocket.js, src/reducers/entities/channels.js, test/actions/channels.test.js
* Removes an unnecessary dispatch.
* Fixes a malformed dispatch.
* Updates the `delete_at` value of a channel in the store when it's deleted.
* Stops removing channels membership and channels from my teams from the store when a channel is archived.
[MM-11510](https://mattermost.atlassian.net/browse/MM-11510)
=> MM-11510: Fixes for the handling of channel deletions.

build/.gitignore, build/Jenkinsfile, package-lock.json, package.json, test/mocha-multi-reporters-config.json, test/mocha.opts
Update Jenkinsfile to build inside `node:8` docker container, add support for generating and consuming junit output from Mocha to show up in Jenkins pipeline, and clean up the stage/steps.
This is part of a learning experiment to figure out how to containerize the server builds, but I'm starting with an easy repository. By specifying the docker container here, we can also choose to upgrade to building on a different version of node independently of the underlying Jenkins slave AMI. For now I'm using the `node:8` image which of course will change with minor versions, but we could choose to pin this or even build our own.
When tests pass:
When a test fails:
https://mattermost.atlassian.net/browse/MM-11539
=> Jenkins build improvements

src/selectors/entities/channels.js, test/selectors/channels.test.js
This is a simplified variant of `getDirectChannels` that does does not exclude manually or automatically closed direct and group channels, nor archived channels. The downstream webapp needs the whole set to display the channels in the "Other" section of the channel quick switcher.
Modifying `getDirectChannels` directly was out of scope:
* it is being used by the mobile app, and thus risks changing semantics unexpectedly
* it is extremely difficult to unravel the business logic. This is a candidate for significant refactoring.
https://mattermost.atlassian.net/browse/MM-11556
This PR was tested on: Chrome, OSX
=> MM-11556: introduce a getDirectAndGroupChannels

src/selectors/entities/channels.js
Only return archived channel if it's the current channel. Remove archived channels from unreads.
[MM-11510](https://mattermost.atlassian.net/browse/MM-11510)
iPhone 6, iOS 11.4 (emulator)
=> MM-11510: Only return archived channel if it's the current channel.

src/action_types/posts.js, src/actions/posts.js, src/reducers/entities/posts.js, src/selectors/entities/posts.js, src/store/initial_state.js, src/types/posts.js, src/utils/post_utils.js, test/actions/posts.test.js, test/reducers/entities/posts.test.js, test/utils/post_utils.test.js
Add a way to clear posts of a channel for new unread/permalink views
[MM-11233](https://mattermost.atlassian.net/browse/MM-11223)
=> MM-11223: Add backup, clear and restore logic for postsInChannel

src/selectors/entities/users.js, test/selectors/users.test.js
Redux changes needed to support migrating `activity_log_modal.jsx` to use Redux and be pure. Added a selector to get a user's sessions and wrote a test for it.
https://github.com/mattermost/mattermost-server/issues/9092
https://mattermost.atlassian.net/browse/MM-11280
This PR was tested on: macOS High Sierra, Safari/11.1.2 and Chrome/68.0.3440
=> [MM-11280] Add Selector for User Sessions

src/selectors/entities/users.js, test/selectors/users.test.js
Redux changes needed to support migrating `access_history_modal.jsx` to use Redux and be pure. Added a selector to get a user's audits and wrote a test for it.
https://github.com/mattermost/mattermost-server/issues/9089
https://mattermost.atlassian.net/browse/MM-11279
This PR was tested on: macOS High Sierra, Safari/11.1.2 and Chrome/68.0.3440
=> [MM-11279] Selector for User Audits

src/actions/posts.js
People don't follow the OpenGraph spec, so different pages are missing different fields. Just check a bunch of different fields to see if a URL has valid OpenGraph data
https://mattermost.atlassian.net/browse/MM-11449
=> MM-11449 Show OpenGraph previews for pages with any of the required fields

src/actions/posts.js, test/actions/posts.test.js
Action was failing when doing a request to get the opengraph data returned `null`
=> Fix when opengraph returns null

src/utils/post_utils.js, test/utils/post_utils.test.js
Fix post type (number) comparison by changing `>` to `-`.
When using `>`, only Android failed to render the order correctly while webapp and iOS worked fine as expected.
After changing to `-`, issue on Android is fixed while webapp and iOS still behaved correctly.
Note: Once this is merged, I'll submit PR to RN and also to webapp. (Though for webapp, it's not necessary but just good to update.)
Jira ticket: [MM-11971](https://mattermost.atlassian.net/browse/MM-11971)
This PR was tested on: [webapp, iOS and Android app]
=> [MM-11971] Fix post type comparison

src/actions/general.js, src/reducers/requests/general.js, src/selectors/entities/general.js, src/store/initial_state.js, test/actions/general.test.js
When running on an older server, the action will just return the original URL. I also added some tests and fixed some missing request state. We should really review the request state at some point since it's not particularly useful like we hoped it would be
=> Add fallback for getRedirectLocation on older servers

src/selectors/entities/channels.js, test/selectors/channels.test.js
Added a selector to get a channel by name. Will return the first match if found, or otherwise `null`. This is needed to make `audit_table.jsx` use Redux.
https://github.com/mattermost/mattermost-server/issues/9090
https://mattermost.atlassian.net/browse/MM-11282
This PR was tested on: macOS High Sierra, Safari/11.1.2 and Chrome/68.0.3440
=> [MM-11282] Add selector to get channel by name

src/utils/channel_utils.js
[MM-11974](https://mattermost.atlassian.net/browse/MM-11974)
=> [MM-11974] Change default return string for channel displayname

Makefile, package.json
I've always found the fact that you can't just `npm install mattermost/mattermost-redux` kind of annoying, but moving the build step to `prepublish` or `prepare` (both are very similar, but `prepare` happens after `prepublish`) instead of `prepublishOnly` so that it triggers automatically on `npm install` should fix that.
This also lets us remove the `.npminstall` files on each repo since we can just check if `node_modules` is up to date rather than creating a new file.
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1717
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2135
=> Run babel on 'npm install' and remove .npminstall

package.json
- Remove whitespace from license field
- Correctly link to the github repo
This should fix these things on npm:
- display of the number of issues/prs
- link to the repo
- license info
=> Fix package.json problems

src/selectors/entities/posts.js
Since this selector has parameters, it should either be a selector factory or a plain function. I went for plain function since that's less overhead, and then the calling code can handle any case where it returns undefined
=> Switch getPostIdsInChannel to not be a selector

src/client/client4.js
We no longer need to emit an event when the server version changes in the client4.js
=> Remove unnecessary event emitter when server version changes

src/actions/users.js, src/client/client4.js, test/actions/users.test.js
Add SetDefaultProfileImage client api and action
[MM-12067](https://mattermost.atlassian.net/browse/MM-12067)
=> MM-12067: Add SetDefaultProfileImage client api and action

src/reducers/entities/search.js
With the new mechanism to get more search results we are actually retrieving results that we already have, so this PR will eliminate those duplicates from the reducer.
The best way to fix this is actually make sure that the server does not return duplicates, but this will definitely be an improvement if we ever get duplicate results. 
https://mattermost.atlassian.net/browse/MM-12399
=> Remove duplicates search results

src/actions/preferences.js, src/types/actions.js, src/types/preferences.js, src/types/store.js
Flow type definitions added to preferences
https://mattermost.atlassian.net/browse/MM-11044
https://github.com/mattermost/mattermost-server/issues/9300
This PR was tested on: Ubuntu 18.04.1 LTS
=> MM-11044 Add flow annotations to preferences actions

src/client/client4.js, src/store/configureStore.dev.js, src/store/configureStore.prod.js, src/store/helpers.js, src/store/middleware.js
Somewhere, we're not properly catching the error objects thrown by Client4 which has been causing them to be logged by Sentry for months, but due to how Sentry handles things that are thrown that aren't actual errors, it provides no information about where we're not handling those.
By using a modified version of the thunk middleware on mobile, we'll be able to intercept those events and replace them with more useful logs on Sentry.
https://mattermost.atlassian.net/browse/MM-11477
=>  MM-11477 Changes required to intercept leaked network errors on mobile

src/client/client4.js
Fixes custom emoji returning empty results
If serverVersion is not stored client4 class isMinimumServerVersion utilty returns false. So, adding back version info into the class.
Reverts part of this commit: https://github.com/mattermost/mattermost-redux/commit/2514cbdff6cc3d6e177202b5f5e37049e0a27eb5#diff-6655fe9b9bb92382c9e8084066aa895e
[MM-12521](https://mattermost.atlassian.net/browse/MM-12521)
This PR was tested on: web
=> MM-12521 Fix custom emoji not returning results

.gitignore, src/action_types/teams.js, src/actions/teams.js, src/actions/websocket.js, src/client/client4.js, src/reducers/entities/teams.js, src/reducers/requests/teams.js, src/store/initial_state.js, src/types/requests.js, test/actions/teams.test.js, test/actions/websocket.test.js
Switches the update team action from using the `/api/v4/teams` endpoint to using the `/api/v4/teams/patch` endpoint.
[MM-11880](https://github.com/mattermost/mattermost-server/issues/9358)
- [x ] Ran `make check-style` to check for style errors (required for all pull requests)
- [x ] Ran `make test` to ensure unit tests passed
- [ x] Ran `make flow` to ensure type checking passed
This PR was tested on: [2016 Macbook Pro, OSX 10.13.6]
=> MM-11880 Have Team Settings modal use the patch endpoint instead of the update endpoint

src/selectors/entities/teams.js, test/selectors/teams.test.js
Found myself needing this in a bunch of places while removing the flux stores.
=> Add getRelativeTeamUrl selector

src/utils/post_utils.js, test/utils/post_utils.test.js
Checking permissions regardless of whether user has a license or not.
Basically this just removes the outer `license.IsLicensed === 'true'` conditional which I don't think is necessary since permissions must be verified regardless of license status.
https://mattermost.atlassian.net/browse/MM-12346
iPhone 6, iOS 12.0 (emulator)
=> MM-12346: Checks permissions to edit post regardless of license.

src/actions/search.js
Export `getMissingChannelsFromPosts` action, which is needed in the webapp to fix MM-12135 and MM-12137
https://mattermost.atlassian.net/browse/MM-12137
https://mattermost.atlassian.net/browse/MM-12135
=> MM-12135: Export getMissingChannelsFromPosts action.

src/selectors/entities/channels.js, test/selectors/channels.test.js
Selectors for getting the channels with the user profile.
https://github.com/mattermost/mattermost-server/issues/8347
This PR was tested on: Mac OS Sierra, 10.12.6
=> GH-8347 added the selector for getting channels with user profiles

src/actions/users.js, src/client/client4.js, src/constants/general.js
Add default options for Client4.autocompleteUsers to prevent JS error when accessing this function directly by the client.
Note: Mobile RN is not affected by the previous change of Client4.autocompleteUsers.
Jira ticket: [MM-12809](https://mattermost.atlassian.net/browse/MM-12809)
=> [MM-12809] Add default options for Client4.autocompleteUsers

src/utils/channel_utils.js, src/utils/post_utils.js
Clearly indicate where we are still using config settings that were deprecated by advanced permissions for backwards compatibility purposes and remove any other uses.
Also removed a function that didn't appear to be used in webapp or RN that seemed to rely on deprecated config settings.
https://mattermost.atlassian.net/browse/MM-12815
=> MM-12815: TIdy up usage of advanced permissions deprecated configs.

src/actions/posts.js, src/reducers/entities/emojis.js, src/reducers/entities/files.js, src/reducers/entities/posts.js, src/types/posts.js, src/types/reactions.js, test/actions/posts.test.js, test/reducers/entities/emojis.test.js, test/reducers/entities/files.test.js, test/reducers/entities/posts.test.js
As discussed on Friday, this makes it so that `post.metadata.emojis` and `post.metadata.files` are removed from the post object when it is stored in the redux state, and then they are added to their respective stores.
https://mattermost.atlassian.net/browse/MM-12827
=> MM-12827 Populate emoji and file state from post metadata 

src/reducers/entities/admin.js, test/reducers/entities/admin.test.js
Shallow clone data to avoid state mutation in analytics reducer.
https://mattermost.atlassian.net/browse/MM-12687
=> MM-12687 Shallow clone data to avoid state mutation in analytics reducer

src/client/client4.js, src/reducers/requests/helpers.js, src/utils/sentry.js, test/actions/helpers.test.js, test/test_store.js, test/utils/sentry.test.js
This is another attempt at stopping the "non-error exceptions" that Sentry keeps getting because we're not catching the errors thrown by Client4 correctly, and Sentry doesn't provide any helpful debugging information unless you're throwing an actual Error object.
https://mattermost.atlassian.net/browse/MM-11477
=> MM-11477 Wrap objects thrown by Client4 in a proper error type

src/actions/errors.js, src/types/actions.js, src/types/errors.js
This PR converts the `/src/actions/errors.js` file to use [Flow static type checker](https://flow.org/).
I was doubting myself a little bit on the creation of the new Type that I made (`src/types/errors.js`). If there are additions that you'd like there, let me know! 👍 
[Jira ticket](https://mattermost.atlassian.net/browse/MM-11047) | [GitHub issue #9770](https://github.com/mattermost/mattermost-server/issues/9770)
This PR was tested on: MacBook Pro, macOS Mojave 10.14
=> MM-11047 Migrate errors action file to Flow

src/selectors/entities/i18n.js, src/selectors/entities/teams.js, src/utils/file_utils.js
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).
When filling in a section please remove the help text and the above text.
Currently default language is not loaded correctly. See screenshots in issue link.
https://github.com/mattermost/mattermost-server/issues/9733
This PR was tested on: [Device name(s), OS version(s)] 
This PR is not tested. How I can compile this to inside mattermost-webapp? Usually when building mattermost-webapp I just write `make clean && make build` and then compile mattermost-server …
=> fix default language import

src/actions/channels.js
By having the client calls outside of the try/catch the app was reporting a promise not being handled correctly
=> Fix fetchMyChannelsAndMembers error handler

src/selectors/entities/channels.js, test/selectors/channels.test.js
There are some channels loaded that could not have the profiles in the channel loaded just yet thus iterating over an undefined array was causing a crash
https://mattermost.atlassian.net/browse/MM-13067
=> Fix more DM's modal

src/selectors/entities/channels.js, test/selectors/channels.test.js
Rearrange logic in sorting channels in the sidebar
Jira ticket: [MM-13035](https://mattermost.atlassian.net/browse/MM-13035) & [MM-13068](https://mattermost.atlassian.net/browse/MM-13068)
This PR was tested on: [Chrome/FF, iOS/RN App - to follow]
=> [MM-13035 & MM-13068] Rearrange logic in sorting channels in the sidebar

src/reducers/entities/channels.js, test/selectors/channels.test.js
When you get the channels by autocompleteChannels api, it returns a
generated display name Private channels, because they doesn't have it by
default (normally is the other user username, which depends on caller of
the API).
But when you load channels in any other way, or receive channels updates
from the websocket, this is overriden. This simply do not override it
with an empty value.
=> Keep autocomplete generated display names for DMs

src/constants/index.js, src/constants/preferences.js, src/constants/users.js, src/utils/channel_utils.js, test/utils/channel_utils.test.js
This is needed by this update on the mobile app https://github.com/mattermost/mattermost-mobile/pull/2302
https://github.com/mattermost/mattermost-server/issues/9505
=> [MM-8404] Add an utility function to ignore channel-wide mentions on channels

src/selectors/entities/channels.js, test/selectors/channels.test.js
Only put channels on top of the sorted list for unread channels group.
I added this comment into the function itself:
```javascript
// mapAndSortChannelIds sorts channels, primarily by:
//   1) hasMentionedChannelIds - Only for unread channels group where channels with mention are always sorted first.
//   2) otherChannelIds - All channels not included in hasMentionedChannelIds and mutedChannelIds are sorted next to hasMentionedChannelIds
//   3) mutedChannelIds - Muted channels are always sorted last regardless of channel grouping
// and then secondary by:
//   1) alphabetical ("alpha") or chronological ("recency") order
export const mapAndSortChannelIds = (channels, currentUser, myMembers, lastPosts, sorting, isUnreadChannel = false) => {...}
```
Jira ticket: [MM-13175]()
This PR was …
=> [MM-13175] Only put channels on top of the sorted list for unread channels group

src/selectors/entities/users.js, test/selectors/users.test.js
Expose `makeGetProfilesNotInChannel` to match `makeGetProfilesInChannel`, for immediate use in the webapp.
https://mattermost.atlassian.net/browse/MM-13209
This PR was tested on: Chrome, OSX
=> MM-13209: add makeGetProfilesNotInChannel selector

src/actions/roles.js
This enforces at least call the load roles after the serverVersion
arrive once. This way we can be sure we don't leave the roles not loaded
during the initial page load.
[MM-13195](https://mattermost.atlassian.net/browse/MM-13195)
=> MM-13195: Enforce at least one load of roles for the initial load

src/selectors/entities/channels.js, test/selectors/channels.test.js
Fix sorting of channels at sidebar "unreads" section.
For all sections except "unreads":
a. All other unread channels
b. Muted channels
For "unreads" section:
a. Non-muted channels with mentions
b. Muted channels with mentions
c. Remaining unread channels
And then secondary by alphabetical ("alpha") or chronological ("recency") order
(Note: Will update redux commit of webapp and mobile once this PR is merged.)
Jira ticket: [MM-13398](https://mattermost.atlassian.net/browse/MM-13398)
This PR was tested on: [Chrome/FF, iOS simulator/Android emulator]
=> [MM-13398] Fix sorting of channels at sidebar unreads section

src/actions/admin.js, src/client/client4.js, test/actions/admin.test.js
Added a `force` flag to uploadPlugin action and client methods to facilitate in-place updating of plugins.
https://mattermost.atlassian.net/browse/MM-8662
This PR was tested on: Chrome, Mac OS X
=> MM-8662: Added `force` flag to uploadPlugin methods

src/actions/websocket.js
The event being dispatch to stop showing the user typing was not including the time.
This PR will only affect the mobile apps, another PR is being submitted for the webapp.
https://mattermost.atlassian.net/browse/MM-13077
=> MM-13077 Remove participant is typing as soon as the post arrives

package-lock.json, package.json
serialize-error doesn't support IE 11 in their published npm output.
=> MM-13444 Fix IE11 support.

src/selectors/entities/posts.js, test/selectors/posts.test.js
Improve performance of `ReturnList` in the webapp or `Reactions` in mobile RN, by:
- returning an object of post reactions from store or null for makeGetReactionsForPost selector.
Note: will submit PR to webapp and mobile.
Jira ticket: [MM-13433](https://mattermost.atlassian.net/browse/MM-13433)
This PR was tested on: [Chrome/FF, iOS simulator/Android emulator]
=> [MM-13433] Performance: return an object from store or null for makeGetReactionsForPost selector

src/selectors/entities/teams.js, test/selectors/teams.test.js
Since getJoinableTeams returned an object, the mobile app had to transform the response in mapStateToProps which lead to multiple re-renders when the redux state changed. This pull request includes a change to have getJoinableTeams return an array of teams which the mobile app can consume as is.
[https://github.com/mattermost/mattermost-server/issues/9951](https://github.com/mattermost/mattermost-server/issues/9951)
* Android emulator
* LG K20V running Android 7.0
* iOS emulator
* iPhone 8 running iOS 12.1
=> [MM 13161] Update getJoinableTeams to return array of teams

src/selectors/entities/users.js, test/selectors/users.test.js
Add makeGetDisplayName selector.
We have many implementation in getting display name of a user.  This makes it convenient just by passing state and user ID at the minimum.
This PR aims to eliminate passing of user's object too deep into the child component; part of client performance investigation of Jesse.
Jira ticket: [MM-13434](https://mattermost.atlassian.net/browse/MM-13434)
This PR was tested on: Chrome, RN not affected
=> [MM-13434] Add makeGetDisplayName selector

src/actions/users.js, src/client/client4.js, src/selectors/entities/users.js, test/selectors/users.test.js
Adds the filtering ability to the redux selectors
https://github.com/mattermost/mattermost-server/issues/7494
This PR was tested on: [mac, ubuntu 18]
=> [GH-7494] Added the filters in selectors and get users request

README.md, build/Jenkinsfile, src/actions/admin.test.js, src/actions/channels.test.js, src/actions/files.test.js, src/actions/jobs.test.js, src/actions/posts.test.js, src/actions/users.test.js, src/actions/websocket.test.js, test/actions/groups.test.js, test/test_helper.js
This is a follow-up to a dev decision way back in June to remove all tests related to the old `npm run test-no-mock` target. We've long since stopped running the tests regularly or as part of CI, but I've had a personal action item to go back and clean the code up.
See https://community.mattermost.com/core/pl/qf1ah4e943gmt81c7zgmz53qsr.
Unrelated, but I've updated this PR to also fix the `Jenkinsfile` not to run `make test` but run `npm test` instead. The flow and check style steps are already discrete, so this duplicates the effort, and appears to cause some sporadic build failures.
N/A
=> rip out isLiveServer checks and corresponding tests

package.json
This avoids copying the newly relocated `*.test.js` files into the babel build directories, which then fail to run via `npm test` since they can't find `test_helper.js`. This doesn't reproduce on CI, since we `npm install --ignore-scripts`, but the typical developer who just runs `npm install` will find all their unit tests duplicated but then mysteriously failing.
N/A
=> exclude *.test.js from the babel build process

.flowconfig, src/selectors/entities/posts.js, src/selectors/entities/posts.test.js, src/store/initial_state.js, src/types/posts.js, src/types/search.js, src/types/users.js, src/utils/post_utils.js
Migrate to flow selectors and utils for posts.
This time I'm extensively used the `$ID` utility function to be super explicit about which kind of parameter is passed. I would appreciate comments about this.
=> Migrate to flow selectors and utils for posts

src/utils/user_utils.js, test/utils/user_utils.test.js
Make it so that an "@" at the beginning of a search is ignored.
Make it so that an "@" in the middle of a search can properly match against an email address.
Fix case-insensitive comparisons for nicknames and emails.
Improves the filtering which happens in the frontend when searching for users, such that the "@" symbol is handled as expected.
[GH-9755](https://github.com/mattermost/mattermost-server/issues/9755)
This PR was tested on: Safari 12.0, macOS 10.14
=> Allow searches for users containing "@" to work

src/client/client4.js
This PR implements CSRF protection tokens for additional hardening compared to the currently used custom header. For additional explanation, please check the linked server PR below.
The way the CSRF cookie currently is read appears not idiomatic / ideal to me, I'd appreciate some feedback there in general, also how the initial parsing when the client is initiated / after the login is done is currently implemented. I'll update the tests afterwards accordingly, currently they fail because of the `document` usage.
https://mattermost.atlassian.net/projects/MM/issues/MM-10346
This PR was tested on: Linux, Fedora 29, Google Chrome 71.0.3578.98
=> [MM-10346] CSRF Token Implementation

src/actions/posts.test.js, src/actions/websocket.js, src/actions/websocket.test.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
* Add empty postIds array if posts are empty
This is to have a difference on the store wrt channels with empty posts and
channels user haven't visited.
* Do not add postId to postsInChannel for channel is not initiated
* add posts to posts object as we can be using them for pinned posts search etc
Changes include a ticket from RN as well as it depends on mm-redux socket actions
[MM-13188](https://mattermost.atlassian.net/browse/MM-13188)
[MM-13428](https://mattermost.atlassian.net/browse/MM-13428)
=> MM-13188 Fix for channels with unreads having loading indicator placed above unread messages line

src/actions/posts.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
The current reducers for `posts`, `postsInChannel`, and `postsInThread` are heavily connected, so this separates them to make it easier to make the changes we need to the `postsInChannel` reducer.
There's a lot of refactoring going on here with one big change: it removes combined system messages. That functionality will be re-added later on.
https://mattermost.atlassian.net/browse/MM-13956
=> MM-13956 Separate post reducers 

src/reducers/entities/teams.js
Patches an issue where the message count for a team is evaluated as '1' instead of zero due to another unknown race condition that passes '-1' as the amount, resulting in a positive integer `(0 - (-1))`. Another ticket will be filed to track down and fix that related issue.
https://mattermost.atlassian.net/browse/MM-13940
=> MM-13940: Replying then switching teams results in incorrect unread dot in team sidebar

src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
When a post had reactions and was pinned, we would dispatch RECEIVED_POST with a post that had an empty metadata object which would be interpreted as the post not having reactions. The reactions would get clobbered and the post's reactions would stop rendering.
By checking to see if the reactions array is defined within the post's metadata, we only remove the reactions when they are actually removed from the post.
https://mattermost.atlassian.net/browse/MM-14115
=> MM-14115 Do not clobber reactions when dispatching RECEIVED_POST that has no reactions metadata

src/actions/channels.js, src/actions/posts.js, src/actions/websocket.js, src/constants/general.js, src/utils/post_utils.js
The WebSocket actions between the webapp and the ones in this library are out of sync and I found that the webapp behaves a bit different, this PR will match the actions for:
* handleNew Post
* reconnecting the websocket 
* marking the channel as read
https://mattermost.atlassian.net/browse/MM-13896
=> Match webapp websocket actions

src/actions/posts.js, src/actions/posts.test.js, src/client/client4.js
Added new functions (action, and client method) augmenting doPostAction to
include the "cookie" value. The old functions should no longer be used,
but I wasn't sure if it's safe to deprecate them, thus new additions.
An upcoming mattermost-server PR will have a better write-up on the use-case and the overall flow.
https://mattermost.atlassian.net/browse/MM-10516
=> Added doPostActionWithCookie for MM-10516, actions in ephemeral messages

src/constants/files.js
-adding tiff and tif to image types constant to Mattermost redux
-in addition to the [server PR](https://github.com/mattermost/mattermost-server/pull/10170) and [webapp PR](https://github.com/mattermost/mattermost-webapp/pull/2333)
https://github.com/mattermost/mattermost-server/issues/8092
https://mattermost.atlassian.net/browse/MM-8421
This PR was tested on: [Mac OS Mojave 10.14.2]
=> [MM-8421]  Fix tiff preview - redux

src/action_types/posts.js, src/actions/posts.js, src/actions/posts.test.js, src/actions/search.js, src/actions/websocket.js, src/actions/websocket.test.js, src/reducers/entities/files.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js, src/reducers/entities/search.js, src/reducers/entities/search.test.js, src/selectors/entities/posts.js, src/selectors/entities/posts.test.js, src/store/initial_state.js, src/types/posts.js
This PR is based on top of #762, so until that is merged, you can see changes specific to this PR here: https://github.com/mattermost/mattermost-redux/compare/mm11887-1-split-reducers...mm11887-2-replace-actions
This is the second preparation step for redoing the postsInChannel store. I went through and audited all of the post actions to ensure they behave in a way that will work with the changes to postsInChannel. I've made the following changes to the post actions:
1. RECEIVED_POST and RECEIVED_POSTS are only used to update existing posts now. The only effect those actions have on postsInChannel is to replace pending posts once they've been created.
2. RECEIVED_POSTS_IN_CHANNEL, RECEIVED_POSTS_IN_THREAD, and RECEIVED_POSTS_SINCE are new actions specific to their respective APIs because …
=> MM-13957 Reorganize post actions 

src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
When a user submits a post we dispatch a `RECEIVED_NEW_POST` action and then two things happen:
1. When we get the response we dispatch a `RECEIVED_NEW_POST` that will handle the pending post and remove it from the store while adding the one we got from the response.
2. The post is also received through the WebSocket and here we also dispatch a `RECEIVED_NEW_POST` action [example](https://github.com/mattermost/mattermost-webapp/blob/master/actions/post_utils.js#L60)
Sometimes depending on the network we can receive the WebSocket response before the actual Request, meaning that a second `RECEIVED_NEW_POST` is dispatched thus duplicating the same post in the store for a small period of time.
Here we make sure that no matter what response gets to the client first if we have a pending post in …
=> Handle pending posts when dispatching RECEIVED_NEW_POST

src/action_types/posts.js, src/actions/posts.js, src/actions/posts.test.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js, src/selectors/entities/channels.test.js, src/selectors/entities/posts.js, src/selectors/entities/posts.test.js, src/types/posts.js, src/utils/post_utils.js
So big things to note here are:
1. Instead of `postsInChannel` holding an array of all loaded post IDs in the channel, it will now be broken up into "blocks" containing an ordered, contiguous array of post IDs. When loading more posts, we can either add those posts to an existing block (as with getPostsBefore and getPostsAfter) or create a separate block (as with getPosts and getPostsUnread). getPostsSince is a special case because it doesn't ensure that each post is adjacent to one another, so we have some handling to make it sometimes add those posts to the most recent block (more on that below)
2. One of the blocks for each channel will be designated as the most recent block. It will act similarly to the old version of `postsInChannel` where newly received posts will be added to it. We …
=> MM-13958/MM-13959 Make postsInChannel into a sparse array

src/selectors/entities/teams.js, src/selectors/entities/teams.test.js
Fix undefined site URL when copying permalink.  Happened when the credentials.url is not set for an unknown reason (which I think needs to investigate further).  This change implements with the fallback of using the `config.SiteURL` whenever necessary.
@enahum I didn't include the Client4.getURL(), looks like the config.SiteURL is sufficient enough.
Jira ticket: [MM-14315](https://mattermost.atlassian.net/browse/MM-14315)
This PR was tested on: [Android emulator and iOS simulator, Desktop/Chrome browser]
=> [MM-14315] Fix undefined site URL when copying permalink

src/utils/channel_utils.js, src/utils/channel_utils.test.js
Fix unnecessary sorting of channels recency on reaction to a post
Jira ticket: [MM-13863](https://mattermost.atlassian.net/browse/MM-13863)
This PR was tested on: [iOS simulator, Chrome]
=> [MM-13863] Fix unnecessary sorting of channels recency on reaction to a post

src/actions/posts.js
This was accidentally using the wrong post type, so the mobile app wasn't showing new messages received over the web socket.
=> Properly handle newly received posts

src/reducers/entities/files.js, src/reducers/entities/files.test.js
On receiving a post from the server, the redux actions will strip out the contents of metadata.files, but leave the metadata object intact (and empty). Some actions take that data and re-emit it back to the store, leading to a race condition where code that doesn't properly check metadata.files will conclude there are no files at all.
https://mattermost.atlassian.net/browse/MM-14447
This PR was tested on: Chrome OSX
=> MM-1447: check post?.metadata?.files, not just metadata

package.json, src/types/groups.js, test/actions/groups.test.js
Removes `can_leave` field.
https://mattermost.atlassian.net/browse/MM-14415
=> MM-14415: Removes 'can_leave' field.

src/constants/preferences.js
Add INTERVAL_NOT_SET for email interval preference.  That is to easily determine user's email interval preference, especially whether something has changed in the UI or not.
~~Note: Will ask release triage team if this will go through release.5.9.~~ 
Update: For release-5.9
Jira ticket: [MM-14527](https://mattermost.atlassian.net/browse/MM-14527)
This PR was tested on: [iOS simulator and Android emulator, Desktop/Chrome]
=> [MM-14527] Add INTERVAL_NOT_SET for email interval preference

package.json, src/actions/admin.js, src/actions/admin.test.js, src/client/client4.js, src/types/groups.js
Adds new query param options when getting LDAP groups.
https://mattermost.atlassian.net/browse/MM-12488
=> MM-12488: Adds new query params options when getting LDAP groups.

src/actions/channels.js
We have an optionmization to create the membership in the frontend directly
without calling the server, but this works only if the group channel is brand
new, for a re-created group channel, I have to get the membership from the
server.
[MM-14386](https://mattermost.atlassian.net/browse/MM-14386)
=> MM-14386: Get the membership if the group channel is not new

src/utils/user_utils.js
Replaces the use of `Array.flatMap` with `Array.reduce` to avoid compatibility issues in 5.10
[MM-14881](https://mattermost.atlassian.net/browse/MM-14881)
=> [MM-14881] Replace flatMap with a reducer

src/actions/channels.test.js, src/actions/posts.test.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
Discard posts on leaving a channel (in addition to the existing behaviour of discarding posts when the channel is deleted). This, in turn, suppresses those posts from the flagged and pinned RHS. Note that the postIds will still be present in those data structures (until they are refreshed), but the UI seamlessly handles "missing" posts as such.
https://mattermost.atlassian.net/browse/MM-14729
This PR was tested on: Chrome, OSX
=> MM-14729: discard posts on leaving channel

src/selectors/entities/channels.js, src/selectors/entities/channels.test.js
This fixes a permission issue for the Add User to Channel modal button in the profile popover. The button was not showing up for Team Admins or Channel Admins when toggled in the System Console.
[Github Ticket](https://github.com/mattermost/mattermost-server/issues/9501)
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-12396)
[Webapp PR](https://github.com/mattermost/mattermost-webapp/pull/2435)
This PR was tested on: [Google Chrome 73.0.3683.86, MacOS 10.14.4]
=> [MM-12396] Option to add user to a channel from the profile pop-over (permissions fix)

src/actions/search.js, src/actions/search.test.js, src/selectors/entities/search.js, src/selectors/entities/search.test.js
Two updates here:
* Add a new selector to return the current search for the current team
* Update search to mark we're at the end of results if we return less posts than we asked for
This is to support some changes to the web app for removing scroll pop from the search results loading indicator.
https://mattermost.atlassian.net/browse/MM-14456
=> MM-14456 Minor updates to search

package.json, src/client/client4.js, src/store/configureStore.dev.js, src/store/configureStore.prod.js
Remove Clien4.online and setOnline.  These functions are used in mobile app but not on webapp.
Jira ticket: [MM-14619](https://mattermost.atlassian.net/browse/MM-14619)
This PR was tested on: [Android emulator, iOS simulator and webapp]
=> [MM-14619] Remove Clien4.online and setOnline

src/utils/file_utils.js, src/utils/file_utils.test.js
Ensure the extension is lower case so that the MIME type lookup succeeds for filenames that have an uppercase extension.
https://github.com/mattermost/mattermost-mobile/pull/2715
* iPhone 8, iOS 12.2
* Galaxy S7, Android 7.0
=> Ensure extension is lower case prior to looking up MIME type

package-lock.json, package.json
Reverting serialize-error to version 2.1.0
serialize-error is though for node, and the version 3.0.0 is using ES6 directly, without transpiling anything (added the Node 6 requirement) and it breaks IE11, so... we must stick to 2.1.0 or remove entirely the dependency (is used in one single place, the `logError` action.
[MM-15285](https://mattermost.atlassian.net/browse/MM-15285)
=> Reverting serialize-error to version 2.1.0

src/selectors/entities/channels.js, src/utils/channel_utils.js
The display names for group messages were being generated by splitting the usernames in the display name returned from the server. The problem with this is that the display name stored server-side has a maximum of 64 characters. If the combined usernames are longer than that some are left out. To fix it we need to generate the display names based on the users we know are in the channel.
This will need follow-up PRs for both the web app and mobile.
https://mattermost.atlassian.net/browse/MM-15363
Partially address https://github.com/mattermost/mattermost-server/issues/10698
=> MM-15363 Properly generate GM display name

src/selectors/entities/teams.js, src/selectors/entities/teams.test.js
Crashes on Android have been reported due to `.name` being called on undefined. `currentTeam` is the only object that I wasn't 100% sure could not be null so I added a check for that.
https://mattermost.atlassian.net/browse/MM-15379
=> [MM-15379] Avoid possible reading of .name on undefined

src/actions/users.js, src/client/client4.js
Add "user_actual_role" field to client-side diagnostics to track if a user is a System Adminuser_actual_role", to connect it with 
Whenever a client-side event is sent to Segment, record the user's role and mark it as "system_admin" if the user is a System Admin, otherwise null.
https://mattermost.atlassian.net/browse/MM-14295
=> MM-14295  - Add "user_actual_role" field to client-side diagnostics to track if a user is a System Admin

src/actions/websocket.js
When the websocket received the event of channel_viewed we were looking at the wrong prop in `msg.broadcast`
https://mattermost.atlassian.net/browse/MM-15532
=> MM-15532 properly mark channel as read when reading the channel in another client

src/actions/channels.js, src/actions/websocket.js
There was a PR that introduced a bug when selecting the default channel as it was using the selector getChannelByName instead of the utility of the same name thus it selected the first available channel that matched the name regardless of the team that it actually belonged.
=> Fix select default channel

package-lock.json, package.json, src/actions/websocket.js, src/actions/websocket.test.js
The TeamList component of the main sidebar uses the `getMySortedTeamIds` selector, which itself calls `getTeams` and `getTeamMemberships`, to compute the IDs for the teams the user is a member of, however, if the client's websocket connection is disconnected then any team removals/additions will be missed as `getTeams` and `getTeamMemberships` will not include the updated state. Dispatching `getMyTeams` and `getMyTeamMembers` fixes this and awaiting these actions prior to checking membership prevents crashes due to an unhandled promise rejection in `fetchMyChannelsAndMembers`.
https://mattermost.atlassian.net/browse/MM-15474
* Galaxy S7, Android 7.0
* iPhone 8, iOS 12.2
Note: I was having trouble using [test_store.js](https://github.com/mattermost/mattermost-redux/bl …
=> [MM-15474] Dispatch getMyTeams and getMyTeamMembers on websocket reconnect

src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
When a post was removed from a channel and then we retrieved the posts since the reducer was trying to sort the previously removed post and trying to access a property on an undefined object.
Note: We'll need to update the reference for the webapp and mobile apps
https://mattermost.atlassian.net/browse/MM-15667
=> MM-15667 if post was removed exclude it from postsInChannel

src/actions/users.js
When switching login methods the cookie is still set for some reason (that I did not look into) thus the action to `loadMe` is triggered.
This action assumed that the currentUserId is set and that the user was already loaded into the state causing a crash, this is a defensive check to only set the Client4 values when it actually exists.
https://mattermost.atlassian.net/browse/MM-15904
=> MM-15904 Only set Client user and roles if user is defined

src/actions/posts.js
Removes a batchActions() that was preventing invalid posts from being removed. Added a listener to a new type of error that'll allow plugins to dismiss posts if they want to.
https://github.com/mattermost/mattermost-server/issues/10883
This PR was tested on: Chrome 75
=> #10883 Allow plugins to dismiss posts through the MessageWillBePosted hook

src/actions/posts.js
With the recent changes to the post reducer we check if the `post.update_at` value is more recent than the previous existing post in order to update the object, when the post fails to send the `update_at` was the same one thus no updates to the store happened.
We'll need to apply this fix to both the webapp and the mobile app.
https://mattermost.atlassian.net/browse/MM-16280
This PR was tested on: Web and Android app
=> MM-16280 when create post fails set the update_at field

src/utils/channel_utils.js, src/utils/channel_utils.test.js
It seems that sometimes when sorting channels from a team they include dm channels that have not been displayed so the `display_name` on those channels are `undefined` causing the sorter to throw an exception.
=> Fix channel sorting when display name is not set

src/constants/posts.js, src/utils/post_utils.js, src/utils/post_utils.test.js
- Adds new post type of me posts, which come from the /me command
- Adds new function in post utils to help identify me posts
https://github.com/mattermost/mattermost-server/issues/10902
This PR was tested on: [WIP]
=> MM-2954: Add a separate post type for /me messages and update formatting

src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
There are cases where we can hit missing messages in between but on a subsequent call of `getPostsSince` API we should be inserting any post after oldest post in recent chunk
[MM-16423](https://mattermost.atlassian.net/browse/MM-16423)
This PR was tested on: [MacOS, chrome and safari]
=> MM-16423 Fix missing posts when using since API

src/utils/user_utils.js, src/utils/user_utils.test.js
This commit modifies the `getSuggestionsSplitBy` method to generate
suggestions with the split string prepended, so for example the term
"user-test" that before was generating ["user-test", "test"], now will
generate ["user-test", "-test", "test"] and will be able to match when
autocompleting with `@-test`
https://mattermost.atlassian.net/browse/MM-15942
- [Has Webapp changes](https://github.com/mattermost/mattermost-webapp/pull/2898)
- [Has Enterprise changes](https://github.com/mattermost/enterprise/pull/445)
=> [MM-15942] Adds suggestions prefixed by split string

src/actions/channels.test.js, src/reducers/entities/channels.js, src/reducers/entities/channels.test.js, src/selectors/entities/channels.js, src/selectors/entities/channels.test.js
This bug was happening because users receive `channel_deleted` events for channels that they're not members of, and that caused the reducer for `entities.channels.channels` to an incomplete channel object that only contains a `delete_at` timestamp and nothing else. When passed into `sortChannelsByDisplayName`, this caused it to throw an error because the channel's `name` field was missing.
This fixes the issue by preventing the channels reducer from storing incomplete channels. I also added some additional protection to `getMyFirstChannelForTeams` since it seems to be the only place where we pass channels into `sortChannelsByDisplayName` without indirectly checking if the channel is complete by seeing things like if the current user is a member of it. …
=> MM-16480 Don't store incomplete channels 

babel.config.js, package-lock.json, package.json, src/selectors/entities/groups.js
Adds optional chaining.
n/a
Chrome on macOS
=> Adds optional chaining.

src/actions/users.js, src/actions/users.test.js, src/actions/websocket.js, src/actions/websocket.test.js, src/client/client4.js, src/reducers/index.js, src/reducers/websocket.js, src/reducers/websocket.test.js, src/store/initial_state.js, src/types/store.js
The mobile and web apps can miss changes to other users that happen when the websocket is disconnected. This makes it so that the app will download any modified users after reconnecting to the websocket.
https://mattermost.atlassian.net/browse/MM-16477
Server: https://github.com/mattermost/mattermost-server/pull/11406
Mobile: https://github.com/mattermost/mattermost-mobile/pull/2936
Web: https://github.com/mattermost/mattermost-webapp/pull/3028
API Reference: https://github.com/mattermost/mattermost-api-reference/pull/457
=> MM-16477 Check for modified users on reconnect

src/actions/admin.js, src/constants/stats.js, src/reducers/entities/admin.js, src/reducers/entities/admin.test.js
This PR adds a getBotPostsPerDayAnalytics action for adding analytics to the Site Statistics in the System Console.
https://mattermost.atlassian.net/browse/MM-14720
- Has server changes (https://github.com/mattermost/mattermost-server/pull/11402)
- Has webapp changes(https://github.com/mattermost/mattermost-webapp/pull/3018)
This PR was tested on: MPB OSX
=> [MM-14720] Add bot post counts per day

src/action_types/users.js, src/actions/users.js, src/actions/users.test.js, src/client/client4.js, src/reducers/entities/users.js
While this PR is standalone is part of the work for https://github.com/mattermost/mattermost-server/issues/7811
Requires https://github.com/mattermost/mattermost-server/pull/11200 in order to work
It can already be reviewed, so I hope it's ok to send this part to review while working on the frontend of the issue.
Redux actions and management for revoking all sessions from all users.
Github: #7811
Jira: https://mattermost.atlassian.net/browse/MM-7854
This PR was tested on: Macbook pro, MacOS 10.14.5 (Mojave)
=> [MM-7854] revoke sessions for all users redux

src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
This is to fix a null pointer that seems to occur when the root post of a thread is missing from `state.entities.posts.posts` when it still exists in `state.entities.posts.postsInThread`. I was not able to reproduce the issue, but we're either not loading the root post of the thread or we're just deleting it before the `postsInThread` entry is deleted. 
https://mattermost.atlassian.net/browse/MM-16695
=> MM-16695 Add null check when deleting channel from postsInThread

src/client/client4.js
In order to facilitate an easier experience for plugins and other clients that use Client4, adding automatic handing of the CSRF cookie. It can be overridden by calling the old methods.
Webapp PR forthcoming to use this automatic system.
https://mattermost.atlassian.net/browse/MM-15783
=> MM-15783 Adding automatic CSRF from cookie

src/client/client4.js
An icon_emoji parameter was added to incoming webhook requests, that overrides the profile icon and the icon_url parameter.
Fixes #11194
https://mattermost.atlassian.net/browse/MM-16389
Related PRs:
https://github.com/mattermost/mattermost-server/pull/11586
https://github.com/mattermost/mattermost-webapp/pull/3074
https://github.com/mattermost/mattermost-mobile/pull/2961
https://github.com/mattermost/docs/pull/2832
https://github.com/mattermost/mattermost-developer-documentation/pull/321
=> [MM-16389] Add client function to transform url to absolute

src/actions/posts.js, src/actions/posts.test.js, src/client/client4.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js, src/selectors/entities/posts.js, src/selectors/entities/posts.test.js
* Add getUnreadPostsAction
* Add getUnreadPosts API to client4
* Add selector makeGetPostsChunkAroundPost
* Add util func getPostsChunkInChannelAroundTime
* Mark recent true for chunks when dispatching based on post.next_post_id
for unread API, posts after API
[MM-11504](https://mattermost.atlassian.net/browse/MM-11504)
=> MM-11504: Add unread API actions and selectors for bi-directional scrolling

src/utils/channel_utils.js, src/utils/channel_utils.test.js
channelMemberNotifyProps can be null. See: https://github.com/mattermost/mattermost-mobile/pull/2980
https://mattermost.atlassian.net/browse/MM-17018
=> [MM-17018] Handle null channelMemberNotifyProps

src/client/websocket_client.js
This check was added here at https://mattermost.atlassian.net/browse/MM-9248 but without this change server disconnects the socket for subpaths.
https://mattermost.atlassian.net/browse/MM-16829
- [] Added or updated unit tests (required for all new features)
IOS and android emulators
=> MM-16829 Fix for websocket reconencts for android

src/actions/posts.js, src/actions/posts.test.js
`getPostsAround` needs to dispatch `next_post_id` and `before_post_id`
`next_post_id` is used to mark a channel if it is at the latest message thus not show the loader at the bottom.
Though we don't use `before_post_id` ATM but it still be beneficial if we want to deduce if the channel is at the oldest  
https://mattermost.atlassian.net/browse/MM-16922
=> MM-16922 Opening a permalink from last few messages of a channel has a loading indicator at the bottom

src/selectors/entities/channels.js, src/selectors/entities/channels.test.js
I'm not sure how we're getting undefined values [here](https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/channels.js#L874), but the stack trace in the [Sentry report](https://sentry.io/organizations/mattermost-mr/issues/1075141568/?project=205624) points to that being the issue. Added a check prior to calling `.name`. Once this PR is merged I'll open a PR on the mobile repo.
https://mattermost.atlassian.net/browse/MM-15379
=> [MM-15379] Check for undefined channel

src/selectors/entities/channels.test.js, src/selectors/entities/teams.js, src/selectors/entities/teams.test.js
This PR fixes an issue where memberships to archived teams are shown as available teams to visit. The issue is intermittent, because of how the `entities.teams.myMembers` reducer handles certain actions. This issue affects the webapp and mobile app by showing archived channels in the switch team components.
[Mobile Ticket](https://mattermost.atlassian.net/browse/MM-14697)
[Webapp Ticket](https://mattermost.atlassian.net/browse/MM-17019)
Chrome and Firefox on Ubuntu
Android 8.1.0
This issue is partially dealt with in the reducer for `state.entities.teams.myMembers`. When the reducer receives an action that contains a payload of teams, the reducer filters out archived teams. Actions that only contain data for memberships, and not actual team objects, cannot filter out …
=> [MM-14697] Filter archived teams out of team membership selectors

src/selectors/entities/posts.js, src/selectors/entities/posts.test.js
If there are no recent messages then that means channel does not have any messages because sys admin deleted join/leave messages then return the empty recent chunk
Earlier this worked based of off webapp by making API call everytime when visiting a channel and then decide to show the channel header. As we are Removing the state change decision in webapp we will be returning the empty chunk so webapp can resolve the loader
https://mattermost.atlassian.net/browse/MM-17385
Mac safari and chrome browsers
=> MM-17385 If recent chunk is empty then return it for getUnreadPosts selector

src/selectors/entities/posts.js, src/selectors/entities/posts.test.js
Cherry pick of #891 on release-5.14.
- #891: MM-17385 If recent chunk is empty then return it for
=> Automated cherry pick of #891

package-lock.json, package.json
NetInfo has been moved out of react-native and into react-native-community. The fork of redux-offline has been updated to use the react-native-community version and this PR is to update the redux-offline commit hash.
https://mattermost.atlassian.net/browse/MM-16593
* Emulator running Android 8.1
=> [MM-16593] Use redux-offline which uses @react-native-community/netinfo

package-lock.json, package.json
This is a follow up on https://github.com/mattermost/mattermost-redux/pull/894. I missed a change in redux-offline.
=> Use redux-offline which uses @react-native-community/netinfo, take 2

src/actions/users.js, src/actions/users.test.js, test/test_helper.js
This PR sets the server version as part of the login complete and load me calls. Server version is needed to correctly decide which is the appropiate channel to redirect a guest user either right after login or when the user is logged in and loads the root of the server, therefore the `setServerVersion` action is dispatched as part of those two processes.
https://mattermost.atlassian.net/browse/MM-17198
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/3476)
=> [MM-17198] Send serverVersion to redux store on login and loadMe

src/reducers/entities/general.js
We should be completely replacing the client license when we receive a new version of it, not merging it with the existing one. This was causing problems when the license was removed as some feature flags were still being set.
Part of https://mattermost.atlassian.net/browse/MM-17917
=> MM-17917 Do not merge client license in reducer

src/reducers/entities/posts.js, src/reducers/entities/posts.test.js
* Channel loading state is determined by the chunks length. If there are no chunks then it assumes it is loading causing this issue.
* Instead excluding removal of recent chunk as if recent chunk is empty it is a valid state to store. 
https://mattermost.atlassian.net/browse/MM-17866
This PR was tested on: Chrome on mac os
=> MM-17866 Fix for channel loader when removing the last post in channel

src/actions/posts.js, src/actions/posts.test.js, src/reducers/entities/posts.js, src/reducers/entities/posts.test.js, src/selectors/entities/posts.js, src/selectors/entities/posts.test.js, src/types/posts.js
* If the lastViewedAt is present and is less than the fist post then
this issue arises
* Fixing this by considering oldest block and first post timestamp. 
More details added in the comment of `getUnreadPostsChunk` func
This PR is made on top of https://github.com/matter.most/mattermost-redux/pull/904
Specific changes to this PR are in https://github.com/mattermost/mattermost-redux/commit/7107df62f88a134441717aea4b40ace84f9597c6.
https://mattermost.atlassian.net/browse/MM-17869
Chrome on macOs
=> MM-17869 Making a post in empty channel sometimes shows just loader

src/constants/plugins.js
- Adding gitlab and antivirus to prepackaged list so that they are not removable in the system console.
[MM-17975](https://mattermost.atlassian.net/browse/MM-17975)
This PR was tested on: Chrome, MacOsX
=> [MM-17975] Some Pre-Packaged plugins show as removable in the UI

src/action_types/index.js, src/action_types/plugins.js, src/actions/plugins.js, src/actions/plugins.test.js, src/client/client4.js, src/constants/plugins.js, src/reducers/entities/index.js, src/reducers/entities/plugins.js, src/selectors/entities/plugins.js, test/test_helper.js
Added support for new plugins marketplace endpoint which includes:
- Actions and Reducer to get and store in Redux state all plugins available from `api/v4/plugins/marketplace` endpoint.
- Selector to filter list to only installed plugins.
Does not include support for searching and/or paging parameters - will be part of another PR.
- Server: https://github.com/mattermost/mattermost-server/pull/11977
- Webapp: https://github.com/mattermost/mattermost-webapp/pull/3492
Part of [MM-17152](https://mattermost.atlassian.net/browse/MM-17152)
=> MM-17152 - Added support for plugins marketplace endpoint

src/actions/admin.js, src/actions/admin.test.js, src/client/client4.js
Add `signature_url` param to `installPluginFromUrl` API.
Webapp: https://github.com/mattermost/mattermost-webapp/pull/3600
=> MM-18139 - Add signature_url param when invoking install_from_url api

src/reducers/entities/search.js, src/reducers/entities/search.test.js
Our `editPost()` redux call sends out a `RECEIVED_POST` event, which the pinned reducer uses to add posts to the current pinned list. In the mobile app, this state is read immediately after editing a post in-line, thus showing multiples of the same post when an already pinned post is edited. This PR stops multiples from being added to the pinned state.
https://mattermost.atlassian.net/browse/MM-18182
This PR was tested on: 
iOS Simulator, iPhone XS iOS 12.4
=> [MM-18182] Don't show multiples of the same posts in pinned results

src/utils/integration_utils.js, src/utils/integration_utils.test.js
Add radio type validation in interactive dialog. Related to https://github.com/mattermost/mattermost-mobile/pull/3212
https://github.com/mattermost/mattermost-server/issues/10465
=> MM-14274: Check radio type dialog element for error

src/actions/channels.js, src/actions/channels.test.js, src/client/client4.js
Adds support for `/channels/privacy` API call.
This PR **depends** on these server changes: 
https://github.com/mattermost/mattermost-server/pull/11993
https://mattermost.atlassian.net/browse/MM-16934
=> [MM-16934] Add support for update channel privacy API call

package-lock.json, package.json, src/actions/posts.js, src/client/client4.js
Introduce a `fetchThreads` parameter to determine if the full thread is fetched with post queries, or just the post + root (to update the reply count / show the `Commented on...` prefix.
Fixes https://mattermost.atlassian.net/browse/MM-17468
https://github.com/mattermost/mattermost-server/pull/11980
https://github.com/mattermost/mattermost-webapp/pull/3549
This PR was tested on: [Device name(s), OS version(s)] 
Ubuntu 19.04
=> MM-17468 - Improving performance of fetching threads

src/actions/posts.test.js, src/reducers/entities/posts.js
Fix regression caused by adding reply_count property.
Maintain reply_count on parent post when comments are created/deleted
Fixed: https://mattermost.atlassian.net/browse/MM-18623
This PR was tested on: Mac, Chrome
=> MM-17468 - Fix regression. Maintain reply_count on parent post when comments are created/deleted

src/actions/posts.test.js, src/reducers/entities/posts.js
Cherry pick of #928 on release-5.16.
- #928: Maintain reply_count on parent post when comments are
/cc  @reflog
=> Automated cherry pick of #928

src/actions/posts.js, src/actions/websocket.js, src/actions/websocket.test.js, src/constants/websocket.js, src/reducers/entities/channels.js, src/reducers/entities/teams.js, src/selectors/entities/channels.js
Websocket actions and events to ensure consistency of mark as unread feature across devices
[MM-17068](https://mattermost.atlassian.net/browse/MM-17068)
This PR was tested on: [Mac OS webapp with chrome] 
[MM-17066]: https://mattermost.atlassian.net/browse/MM-17066
=> [MM-17068] add websocket support for mark as unread

src/actions/posts.js
When a new post is created by the current user, the `total_msg_count` field of the channel and `msg_count` field of the channel memberships weren't being updated. Most of the app was not affected by this, since both were updating on channel navigation, but autocomplete was only updating the channels in the redux state, causing MM-17624. This PR ensures the message counts and unreads are in sync when new posts are created by the current user.
https://mattermost.atlassian.net/browse/MM-17624
Wasn't able to create tests due to the complexity of mocking the redux store/the complexity of `redux-offline` and the `createPost()` function.
This PR was tested on: Chrome 76, macOS 10.14.6
=> [MM-17624] Update message count and unread count in redux on createPost

src/actions/preferences.test.js
The test was printing an error message because the url for nock when deleting a preference was incorrect and the http request didn't succeed.
Error:
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "Retrying action DELETED_PREFERENCES with delay 1".
https://mattermost.atlassian.net/browse/MM-19317
This PR was tested on: [macOS 10.14.6]
=> [MM-19317] Fix nock url for delete preferences

src/actions/channels.js, src/actions/channels.test.js, src/selectors/entities/channels.js, src/selectors/entities/channels.test.js, src/utils/channel_utils.js, src/utils/channel_utils.test.js
One of the if statements must've gotten inverted when we were reviewing the original PR for this. The fixed line is here: https://github.com/mattermost/mattermost-redux/pull/944/files#diff-11fe928fa6662326b67b6a3e602b987dR803
The rest of this PR is reordering the arguments of `isManuallyUnread` to match other selectors and then adding some more tests for `viewMyChannel`
https://mattermost.atlassian.net/browse/MM-19481
=> MM-19481 Stop reading marked channel when switching to a different channel

src/reducers/entities/posts.test.js, src/reducers/entities/posts.ts
Added a guard condition to avoid storing reactions in the state for deleted posts.   This was seen in the related bug when switching channels after a message was deleted and the `RECEIVED_POSTS` action was triggering `storeReactionsForPost` for all posts.    
[MM-19507](https://mattermost.atlassian.net/browse/MM-19507)
This PR was tested on: Chrome-Mac
=> MM-19507 - Reactions on Deleted Messages

src/actions/channels.ts, src/actions/emojis.ts, src/actions/posts.test.js, src/actions/posts.ts, src/actions/teams.ts, src/types/actions.ts
Skip the step of `lastPostActions` that marks a channel as read when the user is viewing a channel if they manually marked it as unread.
@reflog Adding you to this since I had to change a couple of the types because I was running into issues with tests because a bunch of actions were async previously.
Web PR: https://github.com/mattermost/mattermost-webapp/pull/4014
https://mattermost.atlassian.net/browse/MM-19493
=> MM-19493 For manually unread channel, don't mark as read on new message

src/action_types/channels.ts, src/reducers/entities/channels.test.js, src/reducers/entities/channels.ts
Adding new action type `REMOVE_MEMBER_FROM_CHANNEL` (used to complete the `LEAVE_TEAM` websocket event handling properly).
Before this change the user code wasn't able to remove a channel membership when a user leave the team.
Needed for mattermost/mattermost-webapp#4022
[MM-19414](https://mattermost.atlassian.net/browse/MM-19414)
=> Adding new action type REMOVE_MEMBER_FROM_CHANNEL

src/reducers/entities/channels.test.js, src/reducers/entities/channels.ts
Before this PR some reducers were tested independently by exporting them from
the channels reducers file, but the export wasn't needed. This changes make the
tests use the exported global reducer.
=> Remove unnecesary exports from reducers

src/actions/websocket.test.js, src/actions/websocket.ts
When the websocket reconnects fetch the user preferences from the server to update the state
https://mattermost.atlassian.net/browse/MM-19448
iPhone X 12.4 (simulator)
=> MM-19448 Get user preferences on WebSocket reconnect

src/store/helpers.ts
The [comment](https://github.com/mattermost/mattermost-redux/blob/e77647700ad23d0b1d0c98aa6b48f3330c425e4f/src/store/helpers.ts#L30-L32) above the `offlineReducer` says that the data property will be used as the new state but `baseState` was always being used. I've set it to used `action.data` and fallback to `baseState`. On the [mobile app](https://github.com/mattermost/mattermost-mobile/pull/3519) I need to be able to pass in a state through `action.data` in order to preserve some needed user preferences when the state is reset.
https://mattermost.atlassian.net/browse/MM-19841
* iOS simulator, 13.1
=> [MM-19841] Use action.data or baseState

src/utils/post_list.ts
As discussed, because we can't properly save that `isManuallyUnread` state between sessions, we're going to remove this special behaviour when using the Mark as Unread feature.
https://mattermost.atlassian.net/browse/MM-19482
Mobile: https://github.com/mattermost/mattermost-mobile/pull/3524
Web: https://github.com/mattermost/mattermost-webapp/pull/4138
=> MM-19482 Stop rendering New Messages line differently for manually unread channels

package-lock.json, package.json
This PR fixes an issue where the library `form-data` was marked as a devDependency in the PR https://github.com/mattermost/mattermost-redux/pull/936 . Importing `mattermost-redux` in a plugin repo causes an error because the `form-data` library is not present.
https://github.com/mattermost/mattermost-redux/blob/740a13cceda725e4ddcc4d8838eb2ba239dfe9e5/package.json#L74
=> Make form-data a regular dependency

src/constants/files.ts, src/utils/file_utils.ts
Sets file type for `.txt` and `.rtf` files to `TEXT`.  
`.txt` was originally set to be of type `CODE`.
Context is [here](https://github.com/mattermost/mattermost-mobile/pull/3511#issuecomment-552617755)
This PR was tested on: iPhone X (simulator)
| Before (.txt as code) | After (.txt as text) |
| --- | --- |
| <img width="332" alt="before" src="https://user-images.githubusercontent.com/887849/68698455-a797d900-055f-11ea-918b-78bb2e1548a6.png"> | <img width="332" alt="after" src="https://user-images.githubusercontent.com/887849/68698507-c4cca780-055f-11ea-97b4-2bd53f946071.png"> |
Mattermost webapp maintains it's own [file type listing](https://github.com/mattermost/mattermost-webapp/blob/master/utils/constants.jsx#L732) and [passes …
=> Treat .txt and .rtf files as "text", instead of as "code"

src/actions/websocket.test.js, src/actions/websocket.ts, src/reducers/entities/channels.ts
This PR allows to sync the channels received with the ones already present in the persist store so channels that are not included in the response are removed from the store.
https://mattermost.atlassian.net/browse/MM-19961
=> MM-19961 Sync persisted channels with server channels on RECEIVED_CHANNELS

src/reducers/entities/files.ts
This field is supposed to be an object which causes the web app to crash after log in when it's using the latest version of mattermost-redux
=> Fix type of filePublicLink state

package-lock.json, src/actions/channels.ts, src/actions/websocket.test.js, src/reducers/entities/channels.ts
Fixes persisted channels sync by adding a flag to the `fetchChannelsAndMembers` action as there are other actions that dispatch `RECEIVED_CHANNELS` that were causing the store to remove every other channel not received in the requests.
NOTE: also update package-lock.json to include some fixes from `npm audit`
=> Fix sync persisted channels

src/types/config.ts
Adding the missing `AsymmetricSigningPublicKey` field to the Config type. Needed to complete some Redux TS migrations.
=> Adding AsymmetricSigningPublicKey to Config type

src/actions/websocket.ts, src/constants/websocket.ts
Adds a dispatch to load new roles when a users roles is changed (from member to system admin or vice versa)
https://mattermost.atlassian.net/browse/MM-20164
=> [MM-20164] Dispatch redux when users role is changed from member to system admin or vice versa

src/utils/post_utils.test.js, src/utils/post_utils.ts
* Adding util func so it can be used in mobile repo
Moving a small piece of code from webapp to redux: https://github.com/mattermost/mattermost-webapp/blob/97fd5cbf82ba9b583d10ec7380d8c31048d3818b/components/post_view/post_body_additional_content/post_body_additional_content.jsx#L51-L55 
https://mattermost.atlassian.net/browse/MM-15719
=> MM-15719 Adding a util func getEmbedFromMetadata

src/actions/websocket.test.js, src/actions/websocket.ts, src/constants/websocket.ts
Added a new websocket event to be emitted in `handleNewPostEvent` when a new post is seen for the current channel. The mobile app will react to this event by incrementing the post visibility of the current channel.
https://mattermost.atlassian.net/browse/MM-18177
=> [MM-18177] Emit INCREASE_POST_VISIBILITY_BY_ONE for current channel

src/utils/notify_props.test.js, src/utils/notify_props.ts
Treating `INTERVAL_NEVER` as `INTERVAL_IMMEDIATE` when `enableEmail` is `true`.
Fixes https://mattermost.atlassian.net/browse/MM-20260
=> MM-20260 - Email notification still sent while disabled in UI

.circleci/config.yml
cherry pick of https://github.com/mattermost/mattermost-redux/pull/1010
Fixes https://mattermost.atlassian.net/browse/MM-20977
=> MM-20743  - CI uses npm ci instead of npm install (#1005)

src/selectors/entities/channels.test.js
Isolate unit tests for selectors and make them more thorough
https://github.com/mattermost/mattermost-server/issues/10200
=> [GH-10200] Isolate unit tests for channels selectors and make them more thorough

src/utils/helpers.ts, src/utils/post_list.test.js
1. Enable skipped unit tests in utils/post_list.test.js
2. On enabling those tests, observed that it's failing on memoization of `makeCombineUserActivityPosts`. Fixed by reverting change [here](https://github.com/mattermost/mattermost-redux/pull/936/files#diff-f813fe557eb39d392c00fb67ecd64d48R9). This is most likely causing some performance issues since recomputation on `createIdsSelector` is always true.
Before:
After:
=> Enable skipped tests and fix memoization of createIdsSelector

src/selectors/entities/channels.test.js, src/selectors/entities/channels.ts, test/test_helper.js
This is to fix a bug where marking a DM channel as unread would incorrectly set the unread count in the browser tab title and in the mobile app badge. The unread count was including the user's own messages because the logic for counting unread mentions in a DM used the channel member's `msg_count` field instead of its `mention_count`.
The actual fix for this PR is the line I commented on below. The rest of this is cleaning up other tests because a bunch of them were broken due to missing fields (like `msg_count` and `notify_props`) in the objects that were being tested.
https://mattermost.atlassian.net/browse/MM-21153
=> MM-21153 Count mentions in DM channels using mention_count 

src/action_types/channels.ts, src/actions/posts.test.js, src/actions/posts.ts, src/actions/websocket.test.js, src/actions/websocket.ts, src/reducers/entities/channels.ts
When  marking as post as unread in the same client the WebSocket event duplicates the values, this PR dismisses the WS event in case it was mark as unread on the same client.
https://mattermost.atlassian.net/browse/MM-21153
=> Dismiss handlePostUnread WebSocket action is marked as unread locally

src/actions/users.ts
On the mobile app, when logging in as user with no teams the joinable team list will be empty because `loadRolesIfNeeded` is not called since `teamMembers` is empty. With this change, `loadRolesIfNeeded` will be called with `data.roles` even if `teamMembers` is empty.
I'm not sure how to test this correctly. I attempted to add something like `assert.ok(state.entities.roles.roles)` after [this line in the login test](https://github.com/mattermost/mattermost-redux/blob/ea2442ea2a4c5a9d9efea3811e4fce151fdadcc5/src/actions/users.test.js#L64), but `state.entities.roles.roles` is empty there. Any guidance would be appreciated!
https://mattermost.atlassian.net/browse/MM-21280
=> [MM-21280] Ensure roles in data.roles are always added

src/constants/plugins.ts, src/reducers/entities/admin.test.js, src/reducers/entities/admin.ts
Removed flag that would label a plugin as prepackaged from a fix list of plugins given that there is no longer any restriction to uninstall from the system console.
[MM-21262](https://mattermost.atlassian.net/browse/MM-21262)
- Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/4560
=> MM-21262 - Removed prepackaged plugin flags

src/selectors/entities/users.test.js, src/selectors/entities/users.ts
Cherry pick of #1024 on release-5.19.
- #1024: MM-21290: Checks for license AND config prior to
/cc  @mkraft
=> Automated cherry pick of #1024

src/action_types/users.ts, src/actions/websocket.test.js, src/actions/websocket.ts, src/reducers/entities/channels.ts, src/reducers/entities/posts.ts, src/reducers/entities/users.ts, src/utils/user_utils.ts
When a member leaves/being removed, and is not sharing any channels/teams with the current guest user - the guest user should not see that member or access it's info.
This PR adds a new event that is fired when this occurs and cleans up the state.
Fixes: https://mattermost.atlassian.net/browse/MM-19978 and https://mattermost.atlassian.net/browse/MM-19976
**Might need additional work on the mobile side to fix offline sync**
=> MM-19976 & MM-19978 - Guest accounts, guest user should not see members that share no channels with them

src/reducers/entities/channels.ts
When you remove channels and leave the channel page and come back to it without a refresh, the correct groups don't show up.
https://mattermost.atlassian.net/browse/MM-21514
=> [MM-21514] Removing groups on channel page and then leaving page and coming back not showing correct groups

src/constants/preferences.ts, src/types/preferences.ts, src/utils/theme_utils.test.js, src/utils/theme_utils.ts
This will be used in an upcoming webapp PR to fix the bug in the ticket. Essentially we need to make sure all the theme properties are set before applying themes.
https://mattermost.atlassian.net/browse/MM-21726
=> MM-21726 Add theme type and function to set theme defaults

src/actions/websocket.test.js, src/actions/websocket.ts, src/reducers/entities/users.ts, src/selectors/entities/users.ts, src/store/initial_state.ts, src/types/users.ts
When a user that has their status manually set to Away, DND or offline and they send a message to another user, the other user sees their status set to Online. This PR tracks that the status was manually set for each user, and if so it does not set their status to Online.
https://mattermost.atlassian.net/browse/MM-20020
=> [MM-20020] Added tracking of manual status set by user and stopped status being set to online when manually set

package-lock.json, package.json
This PR fixes incompatibility between `@types/jest@24.0.xx` (old version) and `@testing-library/jest-dom` [[related issue](https://github.com/jest-community/snapshot-diff/pull/92/files)].
See https://github.com/mattermost/mattermost-webapp/pull/4713#issuecomment-577338466 for more info.
QA review not required.  Will test change on corresponding webapp PR.
Jira ticket - https://mattermost.atlassian.net/browse/MM-21977
=> MM-21977 Upgrade @types/jest to 24.9.0

src/types/users.ts
Missing `is_bot` and `last_picture_update` from UserProfile type
=> Missing is_bot and last_picture_update from UserProfile type

src/constants/permissions.ts
- Adds the new `use_channel_mentions` permissions to constants
https://mattermost.atlassian.net/browse/MM-21919
Related Server PR: https://github.com/mattermost/mattermost-server/pull/13781
=> [MM-21919]  Add channel mentions permission to list of permissions

src/action_types/channels.ts, src/action_types/general.ts, src/action_types/users.ts, src/actions/roles.ts, src/reducers/entities/channels.ts, src/reducers/entities/general.ts, src/reducers/entities/preferences.ts, src/reducers/entities/teams.ts, src/reducers/entities/users.ts, src/types/teams.ts, src/utils/post_list.test.js, src/utils/post_list.ts
To improve the mobile app performance considerably there is a need to set/update multiple reducers while dispatching only one action type.
When adding all the data needed to one action there is only one dispatch, thus the `mapStateToProps` run only once instead of multiple times.
in this PR we add actions for:
* **LOGIN**: includes user data, teams, teams members, team unreads, preferences, config and license. All of this fetched while logging in or loading the current user data.
* **RECEIVED_MY_CHANNELS_WITH_MEMBERS**: Instead of  dispatching one action for the channels and another action for the channel members, we are dispatching only one with  the data needed for both reducers.
* **SET_CONFIG_AND_LICENSE**: as the name describes
* **RECEIVED_BATCHED_PROFILES_IN_CHANNEL**: To load the …
=> Performance improvements for mobile app

src/actions/channels.test.js, src/actions/channels.ts, src/client/client4.ts, src/reducers/entities/channels.test.js, src/reducers/entities/channels.ts
This PR solves the synchronization problems we are facing due to the persistent nature of the RN storage. In order to synchronize the archived channels in the RN applications we need to ask for the archived channels when we ask for the current user channels so we can update the `delete_at` attribute for the stored channel entities
https://mattermost.atlassian.net/browse/MM-22201
https://github.com/mattermost/mattermost-server/pull/13877
=> Synchronize archived channels with storage

src/constants/general.ts
It adds "mattermost://" to the list of hard-coded URL schemes that render as links.
It needs to be added to this list and then we need to update the version of mattermost-redux used by both the web and mobile apps.
Fixes https://mattermost.atlassian.net/browse/MM-14661
=> [MM-14661] - Add "mattermost://" to the list of hard-coded URL schemes

src/reducers/entities/channels.ts
With the recent changes to the mobile performance we need to keep previous channel memberships so whenever you switch teams while being offline the channel list contains all your channels (even when not in sync).
https://mattermost.atlassian.net/browse/MM-22752
=> MM-22752 Preserve other teams channel membership

src/constants/permissions.ts
An accompanying change to https://github.com/mattermost/mattermost-webapp/pull/4883, defining the requisite system permission strings.
https://mattermost.atlassian.net/browse/MM-21707
=> MM-21707: define MANAGE_(OTHERS_)?BOTS

src/constants/permissions.ts
- Adds a the nw use group mentions permission to the constants list
https://mattermost.atlassian.net/browse/MM-23019
=> [MM-23019] Add use group mentions permission

src/actions/websocket.test.js, src/actions/websocket.ts
Only dispatch actions in `handleUserTypingEvent` for the current channel.
https://mattermost.atlassian.net/browse/MM-23235
=> [MM-23235] Handle user typing event only for current channel

src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts, src/selectors/entities/preferences.test.js, src/selectors/entities/preferences.ts, src/utils/channel_utils.ts, test/merge_objects.js
This implements the missing channel selector from my last PR. As discussed, we're just matching the previous behaviour (implemented in `isAutoClosed`), so the code may be a bit difficult to parse.
If it makes it easier to follow, the original code is [here](https://github.com/mattermost/mattermost-redux/blob/fe064495b21157b729761b924771fd64c81f79dd/src/utils/channel_utils.ts#L157) and I also made a flow chart for it [here](https://drive.google.com/file/d/1ReyJR8X8tGMyYtaD_pbTS-MKjyX78cTx/view?usp=sharing)
To ensure that this should be tested correctly (since testing on the original function is light), I've made it so that the tests double check their results against the original function as well.
https://mattermost.atlassian.net/browse/MM-22577
=> MM-22577 Re-add autoclosing DMs for new selectors

src/actions/posts.test.js, src/actions/posts.ts
Fixes a JS error related to marking a system post as unread. There are two types of posts and system posts have an array of posts ID's, which needs to be taken into account in the mattermost-redux action. 
https://mattermost.atlassian.net/browse/MM-23095
- Has webapp changes (https://github.com/mattermost/mattermost-webapp/pull/5042)
=> [MM-23095] - Update action to take into consideration system posts

src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts
I missed implementing this when copying from the old selectors. Just checking for a channel member to exist here is enough to ensure that we're a member of the channel since channel members are one of the few things that we delete entirely when a user leaves a channel.
https://mattermost.atlassian.net/browse/MM-23239
=> MM-23239 Only show the user's channels in the sidebar

src/actions/websocket.ts, src/constants/websocket.ts
Adds a websocket event to dispatch `getMyChannelMember` when a channel_scheme is either created or deleted to update the list of roles tied to that channel.
Related Server PR: https://github.com/mattermost/mattermost-server/pull/14057
Test steps: 
1.  Login to mobile app and open a channel as regular member
2. Login as sysadmin in different tab and make the channel read only
3. Ensure that the channel changes to read only without reload for the regular member
=> [MM-22212] Add channel scheme updated socket event

src/selectors/entities/preferences.test.js, src/selectors/entities/preferences.ts
I misread [this line](https://github.com/mattermost/mattermost-redux/blob/master/src/utils/channel_utils.ts#L168) of the old channel selectors, so the new channel selectors treated an undefined value for the "autoclose unused DMs" setting as "false" previously. This fixes that, so people that didn't explicitly turn on the setting had their unused DMs reappear with the new sidebar.
https://mattermost.atlassian.net/browse/MM-23513
Webapp PR incoming...
=> MM-23513 Default autoclosing DMs to true with new sidebar

package.json
- Steps to reproduce 
`rm -rf node_modules` 
`rm package-lock.json`
`npm install` 
Observe that the build step fails
- Solution: tie zerollup/ts-transform-paths to latest patch release in order to fix builds
https://mattermost.atlassian.net/browse/MM-23538
=> [MM-23538] Tie zerollup/ts-transform-paths to latest patch release in order to fix builds

src/selectors/entities/channels.ts
- There was a bug on webapp https://github.com/mattermost/mattermost-webapp/pull/5095 that allowed open channels to have a `Preferences` entry of type `group_channel_show` created for them.
- This PR ensures that if there is any bad data (Preferences for open channels marked as group channels) it wont show up in the sidebar direct messages section
https://mattermost.atlassian.net/browse/MM-23427
=> [MM-23427] Filter channels by DM_CHANNEL or GM_CHANNEL when grabbing groups

package-lock.json, package.json
Upgrading TypeScript to 3.7.4 to match the webapp and to allow for the use of optional chaining of variables.
https://mattermost.atlassian.net/browse/MM-23629
=> [MM-23629] Update TypeScript version to 3.7, typescript-eslint to 2.7

src/utils/notify_props.ts
The type of parameter `enableEmailBatching` on `getEmailInterval()` was a `number`, it should be a ` boolean`.
Needed for https://github.com/mattermost/mattermost-webapp/pull/5199.
https://mattermost.atlassian.net/browse/MM-20550
=> [MM-20550] Fixed broken type on getEmailInterval()

src/actions/channels.ts, src/utils/channel_utils.test.js, src/utils/channel_utils.ts
_Note: Merges into `mattermost-mobile` branch._
* Don't re-sort channel sidebar if notification properties haven't actually changed
* Also includes tests for `isChannelMuted`
https://mattermost.atlassian.net/browse/MM-23135
=> [MM-23135] Don't re-sort channel sidebar if notification properties haven't changed

src/constants/permissions.ts
Reverts mattermost/mattermost-redux#1110
The companion PRs for webapp and server are blocked and likely to be cancelled.
=> Revert "MM-23542 new permission for system console access"

src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts
We already check for unread messages when looking for automatically closed DMs/GMs, but we didn't check for it with manually closed DMs/GMs.
https://mattermost.atlassian.net/browse/MM-23756
https://github.com/mattermost/mattermost-webapp/pull/5253
=> MM-23756 Always show unread DMs and GMs in new sidebar

src/client/client4.ts
The original PR was prepared before we started enforcing trailing commas again, so its build passed, but it failed once it was on master.
=> Fix missing trailing comma

test/test_helper.js
Ensure `fakeDMChannel` generates a channel name that matches the semantics of putting the smaller (lexicographically) user id first, avoiding a flaky test failure when comparing against `fakeUserId1`.
Fixes: https://mattermost.atlassian.net/browse/MM-22923
=> fix fakeDmChannel to ensure correct user id order

src/selectors/entities/files.ts, src/selectors/entities/groups.ts, src/selectors/entities/integrations.ts, src/selectors/entities/preferences.ts, src/selectors/entities/roles.ts, src/selectors/entities/roles_helpers.ts, src/selectors/entities/search.ts, src/selectors/entities/teams.ts
The currently exported type defintions breaks CI on the web app. It fails for some reason when the web app's CI manually tries to build mattermost-redux
=> Fix exported type definitions for selectors

src/selectors/entities/teams.ts, src/types/teams.ts
`membersInTeam` was previously typed as any, so I didn't know the correct type when I added it to the selector.
=> Fix missing and incorrect types

src/action_types/channels.ts, src/actions/channels.test.js, src/actions/channels.ts, src/client/client4.ts, src/reducers/entities/channels.test.js, src/reducers/entities/channels.ts, src/selectors/entities/channels.test.js, src/selectors/entities/channels.ts, src/store/initial_state.ts, src/types/channels.ts
- Adds action, reducer and selector for `getChannelMemberCountsByGroup`
https://mattermost.atlassian.net/browse/MM-23264
**Blocked by**
https://github.com/mattermost/mattermost-server/pull/14068
=> [MM-23264] Get channel member counts by group

src/actions/channel_categories.test.js, src/actions/channel_categories.ts, src/actions/channels.test.js, src/actions/channels.ts, src/constants/channel_categories.ts, src/reducers/entities/channel_categories.test.js, src/reducers/entities/channel_categories.ts, src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts, src/selectors/entities/channels.ts, src/selectors/entities/preferences.ts, src/types/channel_categories.ts, tsconfig.json
This adds 3 main things (roughly corresponding to the commits and linked tickets):
1. Instead of determining the channels in each category using the `getUnsortedUnfilteredChannels` selector for the sidebar, the channels in each category are explicitly stored in `ChannelCategory.ChannelIds`. Since we don't have those on the server yet, these are initialized when calling `fetchMyCategories`. There's a followup task to attach this to the server code and remove the fake category generation.
2. Now that we have the channels in each category, we can rearrange channels and move them between categories. This also should handle all of the cases like favouriting a channel adding the corresponding preference for it.
3. Finally, it adds an action to reorder categories. I'd split that into its own PR, …
=> MM-24912/MM-24913/MM-24336 Add redux actions for re-ordering channels and categories

src/actions/channel_categories.test.js, src/actions/channel_categories.ts, src/reducers/entities/channel_categories.ts, src/selectors/entities/channel_categories.ts, src/utils/array_utils.test.ts, src/utils/array_utils.ts
This PR is based on https://github.com/mattermost/mattermost-redux/pull/1144. The changes specific to this PR can be found here: https://github.com/mattermost/mattermost-redux/compare/MM-20895_custom-categories...MM-24916_add-rename-categories
These actions still aren't hooked up to the server, but along with the PR that this is based on, it should allow full testing of custom categories with the proper back-of-webapp infrastructure.
Renaming a category is completely straightforward, but creating a category is more complicated because there are some funny things with how it positions new categories and adding channels to the new category requires removing them from old ones as well.
https://mattermost.atlassian.net/browse/MM-24916
https://mattermost.atlassian.net/browse/MM-20895
=> MM-24916 Add redux actions to create/rename custom categories

src/client/client4.ts
As correctly mentioned in the ticket - the createPost function sent the tracking before the post was saved, thus it didn't have the proper IDs.
Now the order of operations in changed and IDs are sent correctly.
https://mattermost.atlassian.net/browse/MM-24967
=> MM-24967 - Fix new post analytics

src/action_types/groups.ts, src/actions/groups.ts, src/client/client4.ts, src/reducers/entities/groups.ts, src/selectors/entities/groups.test.js, src/selectors/entities/groups.ts, src/selectors/entities/search.test.js, src/store/initial_state.ts, src/types/groups.ts
This ticket addressed the issue of all groups getting highlighted for all users regardless. Now groups only get highlighted yellow ONLY if that user is apart of that group.
https://mattermost.atlassian.net/browse/MM-24695
=> [MM-24695] Only highlight groups you are apart of yellow

src/utils/post_utils.test.js, src/utils/post_utils.ts
When a user is added to a channel on another team, they are not immediately shown an unread badge that they have been added. Until the web app reconnects with the server (it periodically syncs every 15 mins), the channel and team remains as read.
The web client receives the post via the websocket but currently ignores it as it ignores all system messages. This change makes an exception to allow the "system_add_to_team" post type through and increment the unread count.
https://mattermost.atlassian.net/browse/MM-24376
=> [MM-24376] Show channel (and team) as unread if system message is adding current user to channel

src/actions/channel_categories.test.js, src/actions/channel_categories.ts, src/constants/channel_categories.ts, src/reducers/entities/channel_categories.ts, src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts, src/types/channel_categories.ts
The most important part of this is that it adds support for separate "default" and "manual" sorting methods in case we ever need to change what the default is. This isn't strictly necessary, but we've run into enough cases in the past where being able to differentiate between set and unset settings values has really helped us.
This also does a couple other things at the same time:
1. I also realized that TypeScript has proper support for enums, so I also took the opportunity to use that for the CategorySorting type to remove the separate Sorting map of constants.
2. I updated the values of the CategorySorting enum to match the ones used on the server.
https://mattermost.atlassian.net/browse/MM-25126
https://github.com/mattermost/mattermost-server/pull/14575 …
=> MM-25126 Add separate Default sorting method

src/selectors/entities/users.test.js, src/selectors/entities/users.ts
- Adds a filter to the get profiles redux actions to "skip inactive" users
- https://mattermost.atlassian.net/browse/MM-25771
Related Web PR: https://github.com/mattermost/mattermost-webapp/pull/5662
=> [MM-25771] Add filter for selecting profiles that are not deleted

src/reducers/entities/channels.test.js, src/reducers/entities/channels.ts, src/types/config.ts
This PR updates the value of `last_post_at` in channel object. This will be used for determining if delay is needed when prefetching posts. If `last_post_at` is within the last minute then a jitter is added before prefetching posts so all clients don't start requesting at the same time.
https://mattermost.atlassian.net/browse/MM-24924
Related PR: https://github.com/mattermost/mattermost-webapp/pull/5547
=> MM-24917 Update channel object last_post_at when new message is received

src/constants/preferences.ts
New constant for user preference to store status for the "What's New" modal for Channel Sidebar Phase 2.
https://mattermost.atlassian.net/browse/MM-24708
=> [MM-24708] Added new preference constant for What's New modal

src/client/client4.ts, src/reducers/entities/admin.ts, src/reducers/entities/general.ts, src/selectors/entities/channels.ts, src/store/initial_state.ts, src/types/admin.ts, src/types/config.ts, src/types/plugins.ts
The `admin` portion of the redux `GlobalState` was missing types. This PR adds them.
I'm going to make a follow-up PR to clean-up `mattermost-webapp` for some of the migrations that added these types ad-hoc.
https://mattermost.atlassian.net/browse/MM-25325
=> [MM-25325] Add AdminState types to redux

src/types/users.ts
Fields were missing from the `UserProfile` type, needed as part of this PR: https://github.com/mattermost/mattermost-webapp/pull/5545
https://mattermost.atlassian.net/browse/MM-25960
=> Add missing fields to UserProfile

src/actions/channel_categories.test.js, src/actions/channel_categories.ts, src/actions/channels.test.js, src/actions/channels.ts, src/client/client4.ts, src/constants/channel_categories.ts, src/reducers/entities/channel_categories.test.js, src/reducers/entities/channel_categories.ts, src/selectors/entities/channel_categories.ts, src/types/channel_categories.ts, test/test_helper.js
Here's the big PR to link the server logic for custom categories to the redux. I originally thought that adding server calls would allow us to remove almost all the client-side logic here, but it turns out that that doesn't work because the API responses from the server don't reflect all the side effects of the APIs (for example, deleting a custom category changes the channels in the Channels category even though the API response is only about the deleted category).
https://mattermost.atlassian.net/browse/MM-24914
=> MM-24914 Attach sidebar logic to server

src/utils/post_utils.test.js, src/utils/post_utils.ts
Changes the `canEditPost` logic to allow the `edit_others_posts` permission to function independently of `edit_own_posts`.
https://mattermost.atlassian.net/browse/MM-11713
* https://github.com/mattermost/mattermost-mobile/pull/4406
* https://github.com/mattermost/mattermost-server/pull/14787
=> MM-11713: Allows edit others posts to function without edit own posts.

package-lock.json, package.json, src/client/client4.ts, src/client/index.ts, src/client/rudder.ts
Changes to use rudder npm package instead of a global object. Exporting rudder so we can use this dependency for webapp as well. Exporting was a suggestion from Rudder docs https://github.com/rudderlabs/rudder-sdk-js#step-1-install-rudderstack-using-the-code-snippet   
https://mattermost.atlassian.net/browse/MM-26066.
=> MM-26066 Changes to use rudder npm package

package-lock.json, src/client/client4.ts, src/types/client4.ts
- Allow the same autocomplete data as is included in plugin command handlers (CommandArgs) to be encoded into the url params of the dynamic autocomplete call
- Needed for the webapp and server PRs coming up soon
- https://mattermost.atlassian.net/browse/MM-26339
- Webapp: https://github.com/mattermost/mattermost-webapp/pull/5816
- Server: https://github.com/mattermost/mattermost-server/pull/14940
=> MM-26339 - Add context and CommandArgs to dynamic autocomplete calls

src/actions/channel_categories.ts
Sometimes channels get added to two categories when we create a custom category because addChannelToInitialCategory is always ran. This fixes the issue by checking if the channel has a category assigned already. 
https://mattermost.atlassian.net/browse/MM-26323
=> [MM-26363] - Check if channel belong to category before dispatching addChannelToInitialCategory

src/client/client4.test.js, src/client/client4.ts
Adding a variable to client for disabling emit of client rudder events 
https://mattermost.atlassian.net/browse/MM-26685
=> MM-26685 Add a variable for client to disable sending events on rudder

src/selectors/entities/channels.ts
Cherry pick of #1193 on release-5.26.
- #1193: Added Helper function in channels to retrieve all direct
/cc  @Vars-07
=> Automated cherry pick of #1193

src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts
This worked previously, but it broke accidentally when I added separate Default sorting method for categories. Now, the default Channels category and alphabetical option for the DMs category will sort muted channels to the bottom like how the old sidebar did.
https://mattermost.atlassian.net/browse/MM-26801
=> MM-26801 Sort muted channels to the bottom when using alphabetical sorting

src/actions/channels.test.js, src/actions/channels.ts, src/client/client4.ts, src/types/channels.ts
* Add filters for getProfilesInChannel and getProfilesInTeam
* Add filtered user stats endpoint
* Add tests for applyRolesFilters
* Add include bots to filter opts
* Remove unneeded package change
* Review fixes and create a reducer for filtered users stats
* Make filtered stats optional in state
* Build filterRoles better
* Optional chaining
* Add ChannelSearchOpts refactor searchAllChannels
- Manual cherry-pick
=> [MM-26824] [MM-25990] Add channel filters to searchAllChannels (#1192)

src/actions/channel_categories.test.js, src/actions/channel_categories.ts
When making requests to the server, the client that made those requests also receives the corresponding websocket events which often leads to us duplicating logic for handling the websocket event and the HTTP response. I'm going to bring this up at the dev meeting next week, but it might make sense to just handle everything in response to the websocket event to avoid duplicating effort and making the code much more complicated and difficult to follow.
Unfortunately, this does make it harder to test these, but thankfully we have the new E2E tests for that 😄
https://mattermost.atlassian.net/browse/MM-26023
https://github.com/mattermost/mattermost-webapp/pull/5924
=> MM-26023 Move handling of sidebar API responses to the websocket

src/utils/channel_utils.test.js, src/utils/channel_utils.ts
- Function to sort channels by supplied channel type list. 
- I didn't want to update `sortChannelsByTypeAndDisplayName` since that would repercussions in many places, so I made a new function.  
- https://mattermost.atlassian.net/browse/MM-26958
- Parent https://mattermost.atlassian.net/browse/MM-15477
=> [MM-26958] function to sort channels by supplied channel type list

src/actions/channel_categories.test.js, src/actions/channel_categories.ts
* Check if the channel exists in another category before adding it to DM category in a team, If it does not then add it to DM category
https://mattermost.atlassian.net/browse/MM-26971
=> MM-26971 Fix GM duplicates when created and already exists in a category

src/actions/teams.test.js, src/reducers/entities/teams.ts
We need to update the team state using the returning patch data from the regenerate_invite_id endpoint
https://mattermost.atlassian.net/browse/MM-27371
=> [MM-27371] Include regenerate team invite id to update state

src/actions/groups.test.js, src/actions/groups.ts, src/client/client4.ts
- Allows pagination props to be passed for getGroups action
https://mattermost.atlassian.net/browse/MM-26972
=> [MM-26972] Allow pagination props for getGroups

src/selectors/entities/channels.test.js, src/selectors/entities/channels.ts
To get all the recent channel Ids and this will be used to display recent channels in channel switcher. 
This PR is related to an issue in the web app.
https://github.com/mattermost/mattermost-server/issues/14633
=> Add Selectors to get all the recent channel Ids

src/utils/post_list.ts
The new message indicator has a special case for messages posted by the
current user. Currently, webhook messages are attributed to its creator,
which breaks the new message indicator.
https://github.com/mattermost/mattermost-server/issues/14612
=> Fix new message indicator not showing for webhook messages to webhook owner

src/client/client4.ts
Neglected to check for rudder key before executing `page()`
https://mattermost.atlassian.net/browse/MM-27865
=> [MM-27685] Check for rudder key before sending page() command

src/actions/users.ts, src/client/client4.ts
This PR enables `getProfilesInChannel` API to receive additional options. 
https://github.com/mattermost/mattermost-webapp/pull/6372
https://github.com/mattermost/mattermost-server/pull/15390
https://mattermost.atlassian.net/browse/MM-28210
=> [MM-28210] actions/users: add options to get profiles in channel

src/actions/channels.test.js, src/actions/channels.ts, src/reducers/entities/channels.ts
When fixing https://mattermost.atlassian.net/browse/MM-26730, I made it so that `markChannelAsUnread` isn't dispatched when you're first added to a channel because the `ChannelMember` object has already been updated with the correct unread counts by that point. Doing that broke the unread count on the `TeamMember` object though, so instead, we need to dispatch `markChannelAsUnread`, but we need to make sure it only updates the `TeamMember` in that case.
https://mattermost.atlassian.net/browse/MM-28290
https://github.com/mattermost/mattermost-webapp/pull/6500
=> MM-28290 Add option to not increment channel member counts on new post

src/actions/search.test.js, src/actions/search.ts
We've had problems when a post gets returned by a search engine but it's marked as deleted or absent in the database, the search endpoint returns 19 instead of 20 (for example) returns, and the frontend marks the search as ended, having more results in the following pages.
This PR and it's webapp counterpart only mark the search as ended when no more results are returned by the search endpoint, to fix this bug.
https://mattermost.atlassian.net/browse/MM-28944
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/6577)
=> [MM-28944] Mark the search as ended only when no more results returned

src/selectors/entities/posts.ts, src/types/posts.ts
Define OpenGraphMetadata
This is needed to convert 'components/post_view/post_attachment_opengraph' module to TypeScript (issue https://github.com/mattermost/mattermost-server/issues/15447)
Regards,
Nicolas
=> Define OpenGraphMetadata

src/reducers/entities/admin.ts, src/types/admin.ts
At some point `userAccessTokensByUser` was renamed to `userAccessTokensForUser`, but just an alias was changed. This PR changes the name back to `userAccessTokensByUser` and fixes the type for a TS migration.
https://mattermost.atlassian.net/browse/MM-20586
=> Rename userAccessTokensForUser to userAccessTokensByUser and fix the type

src/selectors/entities/emojis.test.js, src/selectors/entities/emojis.ts
When custom emojis are disabled, a new empty object is returned each call causing any components using this to re-render constantly.
https://mattermost.atlassian.net/browse/MM-29679
=> MM-29679 Add memoization to getCustomEmojis

src/types/posts.ts
This Pull Request adds an additional field `filenames` in `Posts` types which is required in the below GitHub issue. With this addition, we will be able to remove compilation error in the `post_body.tsx` (migration from jsx to tsx).
https://github.com/mattermost/mattermost-server/issues/15440
=> Addition of filenames field in Posts types

src/client/client4.ts
* Add telemetry event notice_seen_NOTICEID
https://mattermost.atlassian.net/browse/MM-29998
=> MM-29998 Add telemetry for in product notices

src/selectors/entities/channels.test.js, src/selectors/entities/channels.ts
As I mentioned earlier this week, `getChannel` is problematic because its a selector that takes an argument without being behind a factory function, so if you have two or more components both using it, they'll constantly be overwriting each others' results, leading to those components re-rendering constantly. The main reason that this causes problems is that `getChannel` returns a new object each time for DMs and GMs because it adds on some additional derived fields such as the dynamic display_name for DM and GM channels. On the current version of master, this leads to things like parts of the new sidebar and all of the RHS re-rendering constantly.
I changed `getChannel` to bea plain function that doesn't compute any data so that it can be re-used easily wherever we don't need the …
=> MM-28833 Remove computed details from getChannel selector

src/types/posts.ts
Add missing 'link' PostEmbed type
This is needed to finalize PR https://github.com/mattermost/mattermost-webapp/pull/6668
Server corresponding definition https://github.com/mattermost/mattermost-server/blob/a63684fcb5e3ba7b7522b35c29a4cb27779ba823/model/post_embed.go#L10
Fixes part of mattermost/mattermost-server#15460
JIRA: https://mattermost.atlassian.net/browse/MM-20481
=> [MM-20481] Add 'link' as a possible PostEmbedType

src/actions/groups.ts
Method signature was expected a final argument that was only `false`. This changes it to be optional and take a `boolean` that defaults to be `false`.
Needed for this PR: https://github.com/mattermost/mattermost-webapp/pull/6924
https://mattermost.atlassian.net/browse/MM-20581
=> [MM-20581] Update method signature for getGroupsAssociatedToChannel

src/selectors/entities/general.test.js, src/selectors/entities/general.ts, src/types/config.ts
Due to some changes in 5.28 around the internal/external link handling in the web app, we broke the newly added [Desktop Managed Resources](https://docs.mattermost.com/install/desktop-managed-resources.html) feature which basically lets non-MM services host stuff at certain routes under the MM server.
Since most paths in the server could be a team URL, the new link handling is correct for anyone not using that feature, so instead of reverting the link handling changes, we're adding a way to the server to manually specify these paths that should not be handled by the web app.
https://mattermost.atlassian.net/browse/MM-30090
https://github.com/mattermost/mattermost-server/pull/16213
https://github.com/mattermost/mattermost-webapp/pull/7024
=> MM-30090 Add ManagedResourcePaths setting

src/types/channels.ts
Make ChannelModeration to be consistent with ChannelModerationRoles : add 'admins' key. 
Needed for https://github.com/mattermost/mattermost-webapp/pull/6924 to avoid error : 
```
TS7053: Element implicitly has an 'any' type because expression of type 'ChannelModerationRoles' can't be used to index type '{ guests?: { value: boolean; enabled: boolean; } | undefined; members: { value: boolean; enabled: boolean; }; }'.   Property 'admins' does not exist on type '{ guests?: { value: boolean; enabled: boolean; } | undefined; members: { value: boolean; enabled: boolean; }; }'.
```
=> Fix ChannelModeration to be consistent with ChannelModerationRoles

src/actions/channel_categories.test.js, src/actions/channel_categories.ts, src/utils/array_utils.test.ts, src/utils/array_utils.ts
For multi-select drag and drop, we needed a reliable way of moving an arbitrary selection of channels from n categories to a single index in a category. I've leveraged the existing code and modified it to work with multiple and the re-arranging necessary to do so. Luckily the back-end already supports this!
https://mattermost.atlassian.net/browse/MM-30158
=> [MM-30158] Added method for moving multiple channels from any number of categories to one category.

src/action_types/channels.ts, src/actions/channel_categories.test.js, src/actions/channel_categories.ts, src/actions/channels.test.js, src/actions/channels.ts, src/constants/channels.ts, src/constants/general.ts, src/reducers/entities/channels.ts, src/selectors/entities/channel_categories.test.js, src/types/channel_categories.ts, src/utils/channel_utils.ts
A new sidebar feature is muting entire categories at once. Muting a category mutes all channels in it and makes it so that channels moved into it get automatically muted.
Nothing super special to note here, but I went back on just relying on the websocket events to update categories because it caused a weird pop-in where each channel in a category muted one-by-one because different websocket events were muting each channel.
https://mattermost.atlassian.net/browse/MM-20897
https://github.com/mattermost/mattermost-server/pull/16225
https://github.com/mattermost/mattermost-webapp/pull/7033
=> MM-20897 Add category muting

src/types/apps.ts
The description field of a form field should be optional.  This is the value for text below each field in the modal.
Personally, I don't think the user should be required to show this text
n/a
=> Allow description field of form field to be optional

src/client/client4.ts, src/constants/apps.ts, src/reducers/entities/apps.ts, src/selectors/entities/apps.ts, src/types/apps.ts, src/types/integrations.ts
This PR moves some constants from `types/apps.ts` to `types/constants.ts`, so JS files can use the constants.
There is also a change in `selectors/apps.ts` to support multiple apps. The backend is returning the bindings like:
```json
[
{
"app_id": "hello",
"location": "/command",
"bindings": [
{
"app_id": "hello",
"label": "message",
"hint": "[--user] message",
"description": "send a message to a user",
"call": {
"url": "https://mickmister.ngrok.io/plugins/com.mattermost.apps/hello/send"
}
}
]
},
{
"app_id": "hello2",
"location": "/command",
"bindings": [
{
"app_id": "hello2",
"label": "message",
"hint": "[--user] message",
"description": "send a message to a user",
"call": {
"url": "https://mickmister.ngrok.io/plugins/com.mattermost.apps/hello/send"
}
}
]
}
]
```
The selector function …
=> Updates for App Commands

.editorconfig
Add trim trailing whitespace to `.editorconfig` like mattermost-webapp. Helps with `eslint(no-trailing-spaces)`.
=> editor config trim trailing whitespace

src/constants/preferences.ts, src/selectors/entities/channel_categories.test.js, src/selectors/entities/channel_categories.ts
This reverts commit aa69940023b71b8ddc91fc0386078ab2d987d105.
Reverts PR #1300 as it needs also the change in webapp (https://github.com/mattermost/mattermost-webapp/pull/7068) which is not yet merged. this is causing new dms in community-daily to not appear in the sidebar.
Jira Ticket: https://mattermost.atlassian.net/browse/MM-31197
=> [MM-31197] Revert "[MM-27927] - Add user preference for limit on dms and gms

src/actions/channel_categories.ts
When changing category order, we were waiting for the websocket event from the server to update the category order in redux. This PR changes the action to update optimistically, and reset if we encounter an error.
https://mattermost.atlassian.net/browse/MM-31053
=> [MM-31053] Optimistically update category order

src/types/posts.ts
Missing a field from `Post` type in redux. Adding for https://github.com/mattermost/mattermost-webapp/pull/7189
=> Add `message_source` field to `Post` type

src/constants/preferences.ts, src/selectors/entities/preferences.test.js, src/selectors/entities/preferences.ts
I went through a few versions of this trying to get the backwards compatibility correct, particularly when I was trying to make it cover both the old and new sidebars. I finally ended up removing the old sidebar from the selector since we're not going to change the old sidebar to use the new selector anyway.
For the new preference, we're using the `show_unread_section` preference which was previously used a long time ago in the earliest version of the sidebar revamp. Since we're going to be prioritizing that over the preference that was used in the mean time, there's a small chance that someone will have the original preference turned on but the current preference turned off, but I don't think that'll be a problem.
https://mattermost.atlassian.net/browse/MM-30443 …
=> MM-30443 Add shouldShowUnreadsCategory selector for new sidebar

src/selectors/entities/preferences.ts
The explicit type was removed from `getTheme` when it was being changed to not be `(GlobalState) => any`. I'm on board with typing it properly, but it breaks the library when imported into the web app.
=> Add exported type to getTheme

src/types/config.ts, src/types/posts.ts
The TypeScript compiler is failing to type check the web app with the current master. There are two things causing problems currently:
1. There are a couple circular references, one caused by types importing constants and vice versa and the other caused by two type files importing each other. I resolved the first one, but I wasn't able to resolve the second, so I just turned it to an `any` temporarily.
2. Some unit tests in the web app are failing because the `Post.participants` field was previously mandatory. This can be reverted if necessary.
=> Temporarily fix typing issues

src/actions/channel_categories.test.js, src/actions/channel_categories.ts
Previously, we'd set the category to manual sorting whenever something was dragged and dropped into it, but we don't need that if the user is specifically using alphabetical or recency sorting.
https://mattermost.atlassian.net/browse/MM-32099
https://github.com/mattermost/mattermost-webapp/pull/7342
=> MM-32099 Don't change category sorting method to manual when dragging and dropping

src/constants/apps.ts
This PR corrects the expand_levels for typescript.
Added two new fields to match the existing fields in mattermost-plugin-apps/server/api/expand.go. 
Change values to lowercase 
N/A
=> Update Typescript Expand Levels keys and values to match latest form mm-plugin-apps

src/types/channels.ts, src/types/users.ts
Adds the `channel.shared` and `user.remote_id` properties to the corresponding types.
https://mattermost.atlassian.net/browse/MM-31996
=> [MM-31996] Add shared and remote_id to user and channel types

src/actions/integrations.ts, src/client/client4.ts, src/types/integrations.ts
`executeCommand` should have a proper typing with `CommandArgs` as the second argument
https://mattermost.atlassian.net/browse/MM-32594
=> Correctly type signature of executeCommand

src/types/config.ts
Add's shared channels and remote_cluster_service types on the configuration.
https://mattermost.atlassian.net/browse/MM-29027
https://mattermost.atlassian.net/browse/MM-30838
This waits on the [shared channels branch](https://github.com/mattermost/mattermost-server/compare/MM-27493_shared_channels) to be merged first
=> Add shared channels to license

package-lock.json, package.json
The Selenium tests that QA use run on Firefox 54, and the new version of serialize-error fails to load on there because it uses slightly newer syntax (https://caniuse.com/mdn-javascript_statements_try_catch_optional_catch_binding, supported in Firefox 58+). Selenium will be upgraded or removed at some point, but this will fix it in the meantime.
https://mattermost.atlassian.net/browse/MM-33209
https://github.com/mattermost/mattermost-webapp/pull/7586
=> MM-33209 Downgrade serialize-error

NOTICE.txt, package-lock.json, package.json, src/store/configureStore.dev.ts, src/store/configureStore.prod.ts, src/store/middleware.ts, src/types/module.d.ts
This is a precursor to removing redux-offline altogether, by noting first that redux-action-buffer is only used when `enableBuffer` is left unset or passed as `true`, but the webapp unconditionally passes it as `false`:
https://github.com/mattermost/mattermost-webapp/blob/8676ca150396b1eed898d7a114264bfa4278e884/store/index.js#L215
Relates-to: https://mattermost.atlassian.net/browse/MM-24009
=> MM-24009: remove redux-action-buffer

src/types/channels.ts
* Adds optional prop type in the same syntax as `posts.ts`, `integrations.ts` and `sessions.ts` so that the channel_info_moda l(mattermost webapp) can correctly use the channel type when converted to typescript.
https://github.com/mattermost/mattermost-server/issues/16739
=> [GH-16739] Add optional props attribute to channel type

src/constants/permissions.ts
Currently, we are determining the ancillary permissions required on the front-end. This should be done on the backend.
This will allow us to eliminate having to keep a copy of ancillary permissions on the front-end.
https://mattermost.atlassian.net/browse/MM-33501
=> [MM-35501] Remove Determining Ancillary Permissions from Frontend to Backend

src/client/client4.ts, src/types/apps.ts, src/types/integrations.ts
Now instead of using the call type, we add the type to the path at redux level.
I also included here the AppCall/AppCallRequest needed changes.
https://mattermost.atlassian.net/browse/MM-33178
Webapp: https://github.com/mattermost/mattermost-webapp/pull/7679
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5221
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/99
=> Use call type on the path
