mattermost/mattermost-redux

Makefile
test/actions/general.test.js

Fix some tests and add install to Makefile

Fix some tests and add install to Makefile

---

Makefile
test/actions/general.test.js

Fix some tests and add install to Makefile for 3.7

---

src/actions/posts.js
src/actions/preferences.js
src/constants/index.js
src/utils/post_utils.js
test/actions/posts.test.js

This PR adds the actions to flag and unflag posts
https://mattermost.atlassian.net/browse/PLT-5511
This PR was tested on: IOS 10.2.1 iPhone 6s, Android 6.0.1 Samsung J5

PLT-5511 Ability to flag and unflag posts (master)

---

src/selectors/entities/users.js

https://mattermost.atlassian.net/browse/PLT-5494

PLT-5494 Added getUsersByUsername selector

---

src/actions/preferences.js
src/actions/users.js
src/actions/websocket.js
src/constants/constants.js
src/constants/index.js
src/selectors/entities/channels.js
src/utils/channel_utils.js

Includes GM channels to the list and sort favorites excluding the type of channel
https://mattermost.atlassian.net/browse/PLT-5721
https://mattermost.atlassian.net/browse/PLT-5888
This PR was tested on: IOS 10.2.1 iPhone 6s, Android 6.0.1 Samsung J5

Modify channel utils to include group messages

---

src/action_types/users.js
src/actions/channels.js
src/actions/files.js
src/actions/general.js
src/actions/helpers.js
src/actions/posts.js
src/actions/preferences.js
src/actions/teams.js
src/actions/users.js
src/actions/websocket.js
src/client/client4.js
src/client/index.js
src/reducers/requests/users.js
test/actions/channels.test.js
test/actions/files.test.js
test/actions/general.test.js
test/actions/posts.test.js
test/actions/preferences.test.js
test/actions/teams.test.js
test/actions/users.test.js
test/actions/websocket.test.js
test/test_helper.js

Getting the v4 driver all setup and added a createUser action to test it.

Setup v4 driver and add action for user creation

---

NOTICE.txt
package.json
src/actions/files.js
src/actions/posts.js
src/client/client.js
src/constants/files.js
src/constants/request_status.js
src/reducers/entities/files.js
src/reducers/requests/files.js
src/selectors/entities/files.js
src/utils/file_utils.js
test/actions/files.test.js
test/actions/posts.test.js
test/test_helper.js

This PR adds the ability for images to be attached to posts.
https://mattermost.atlassian.net/browse/PLT-5926

PLT-5518 RN: Allow user to upload + send image file attachments

---

src/actions/posts.js
src/actions/preferences.js
src/actions/users.js
src/client/client4.js
src/constants/general.js
src/reducers/entities/users.js
test/actions/channels.test.js
test/actions/files.test.js
test/actions/general.test.js
test/actions/posts.test.js
test/actions/preferences.test.js
test/actions/teams.test.js
test/actions/users.test.js
test/actions/websocket.test.js
test/test_helper.js

Move user actions to use the available v4 endpoints that are in 3.7. Based on #13 
https://mattermost.atlassian.net/browse/PLT-5986

PLT-5896 Move user actions to use the available 3.7 v4 endpoints

---

src/action_types/users.js
src/actions/users.js
src/client/client.js
src/client/client4.js
src/reducers/entities/users.js
src/reducers/requests/users.js
test/actions/users.test.js

- All new/modified APIs include changes to the drivers

Added actions to get a single user by id or username

---

.gitignore
package.json

I still want to get it so that it doesn't need to copy everything into the root folder, but that'll come later

Stopped removing src directory in postinstall

---

package.json

Fix the ability to install the package

add src to package files

---

src/action_types/posts.js
src/actions/posts.js
src/actions/websocket.js
src/client/client4.js
src/reducers/requests/posts.js
test/actions/posts.test.js

Move post actions to use APIv4.

Move post actions to use APIv4

---

src/actions/files.js
src/actions/general.js
src/actions/preferences.js
src/client/client4.js
test/actions/files.test.js

Move some more actions over to v4

Move some more actions over to v4

---

src/actions/users.js
src/constants/users.js
src/reducers/entities/users.js
src/selectors/entities/users.js

This was bothering me so I removed search from the user store and fixed the RN app to use the profiles from the store instead of search

remove search from user store

---

NOTICE.txt
package.json
src/actions/errors.js
src/client/client.js

This PR stringifies client errors and logs them to the server.
https://mattermost.atlassian.net/browse/PLT-5967
@jarredwitt

Log errors to the server

---

src/actions/teams.js
src/actions/users.js
src/client/client4.js
test/actions/users.test.js

Move more user actions over to use v4.

Move more user actions over to use v4

---

src/actions/users.js
src/selectors/entities/users.js

This PR add the options when searching for profiles and set the correct stores

add profile search options

---

src/actions/websocket.js

This will fix fetching the root post when getting a reply in a DM or GM

Fix root post

---

src/actions/channels.js
src/client/websocket_client.js

On Android there is an issue where the WebSocket won't connect if we don't remove the port from the URI if the port is 80 or 443, this will fix the issue.
Also this fixes a weakmap in android when we receive a post and the channel does not exists in the store

Fix android WS connection and weakmap when channel not in the store

---

src/actions/channels.js
src/reducers/entities/channels.js
src/selectors/entities/channels.js
src/selectors/entities/users.js
src/utils/channel_utils.js
test/actions/channels.test.js
test/actions/users.test.js
test/selectors/channels.test.js
test/test_helper.js

Add channelsInTeam entity.
https://mattermost.atlassian.net/browse/PLT-5953

PLT-5953 (part1) Add channelsInTeam entity

---

README.md
src/action_types/emojis.js
src/action_types/index.js
src/actions/emojis.js
src/client/client.js
src/reducers/entities/emojis.js
src/reducers/entities/index.js
src/reducers/requests/emojis.js
src/reducers/requests/index.js
src/selectors/entities/emojis.js
test/actions/emojis.test.js

Add emoji entities and actions.
NOTE: To run the new tests you need to have EnableCustomEmoji set to true in your config.json
https://mattermost.atlassian.net/browse/PLT-5957

PLT-5957 Add emoji entities and actions

---

src/constants/general.js
src/utils/channel_utils.js
src/utils/delayed_action.js
src/utils/post_utils.js
src/utils/user_utils.js

https://mattermost.atlassian.net/browse/PLT-6208

PLT-6208 Follow permission policies set in System Console (master)

---

src/constants/constants.js
src/utils/channel_utils.js
src/utils/delayed_action.js
src/utils/post_utils.js
src/utils/user_utils.js

https://mattermost.atlassian.net/browse/PLT-6208

PLT-6208 Follow permission policies set in System Console (3.7)

---

src/action_types/alerts.js
src/action_types/index.js
src/actions/alerts.js
src/constants/alerts.js
src/constants/index.js
src/reducers/entities/alerts.js
src/reducers/entities/index.js
src/selectors/entities/alerts.js
test/actions/alerts.test.js
test/selectors/alerts.test.js

Add alert store, actions and selectors. Didn't add the ability to ignore alerts since I'm not sure we'll need it.
https://mattermost.atlassian.net/browse/PLT-5959

PLT-5959 Add alert store, actions and selectors

---

src/actions/websocket.js

This sets a flag to follow the reconnection path if the WebSocket was closed manually and also fixes a issue when fetching the posts for a channel when reconnecting

Create flag for WS reconnection and fix loadPostHelper (master)

---

src/actions/websocket.js
src/constants/websocket.js

https://mattermost.atlassian.net/browse/PLT-1384

PLT-1384 Added handling for new preferences updated/deleted events (Master)

---

src/actions/preferences.js
src/actions/users.js
src/actions/websocket.js

* Get preferences when websocket reconnects
* Fetch GM channel if not in the store

Preferences and GM (master)

---

src/actions/preferences.js
src/actions/users.js
src/actions/websocket.js

* Get preferences when websocket reconnects
* Fetch GM channel if not in the store

Preferences and GM (3.7)

---

src/client/client.js
src/client/client4.js

Add a timestamp to ping request to prevent cached responses

Ping timestamp (master)

---

src/actions/users.js
src/actions/websocket.js
src/client/client4.js
src/reducers/entities/users.js

Switch to using v4 endpoint for statuses.

Switch to using v4 endpoint for statuses

---

src/action_types/teams.js
src/actions/teams.js
src/actions/users.js
src/client/client4.js
src/constants/index.js
src/constants/teams.js
src/reducers/entities/teams.js
src/reducers/entities/users.js
src/reducers/requests/teams.js
src/selectors/entities/teams.js
test/actions/teams.test.js
test/selectors/teams.test.js

Add team actions and other changes for webapp. @enahum I think the only change to be known for RN is that the `createTeam` action no longer takes a user id as an argument

Add team actions and other changes for webapp

---

package.json
src/actions/channels.js
src/reducers/entities/channels.js

Updates channel stats whenever a user is added or removed from the channel.
Additional to that updated `redux-batched-actions` to be able to add a string for better debugging the redux store.
Finally modified the `build` and `postinstall` scripts. The `build` script now builds the library in the root folder and `postinstall` won't delete the `src` folder.

Fixes Channel Stats

---

package.json
src/actions/posts.js
src/client/client4.js
src/reducers/entities/posts.js
src/reducers/entities/users.js
src/selectors/entities/posts.js
src/store/helpers.js
test/actions/posts.test.js

This PR allows for posts to be submitted optimistically.
https://mattermost.atlassian.net/browse/RN-52
@jarredwitt

RN-52: RN: Make create post and upload file actions optimistic

---

src/actions/posts.js

I need to call this from the webapp until it is using the websocket client from the redux repo.
https://mattermost.atlassian.net/browse/PLT-4457

PLT-4457 Export getProfilesAndStatusesForPosts

---

src/actions/files.js
src/utils/file_utils.js
test/actions/files.test.js

With this we properly handle when upload a file fails so we can retry the upload before creating the post

Ability to retry failed file uploads

---

src/actions/channels.js

Fix savePreference action invoke

Fix savePreference action invoke

---

src/reducers/entities/posts.js

This PR fixes an issue where posts with replies were not being deleted properly.

RN-132: Deleting a message that has a reply

---

src/selectors/entities/preferences.js
src/selectors/entities/teams.js
src/selectors/entities/users.js
test/selectors/preferences.test.js
test/selectors/teams.test.js
test/selectors/users.test.js

Add selectors for preferences and user admin checks.

Add selectors for preferences and user admin checks

---

src/constants/preferences.js

Add advanced setting preference constant

Add advanced setting preference constant

---

src/actions/channels.js
src/actions/general.js
src/actions/users.js

General fixes/updates I made to the webapp branch. @enahum not sure if the view channel changes will affect RN. If they don't work let me know and I can make it support the old behaviour as well
Note that `loadMe` changed to just use all the actions instead of the client directly. If that's an issue for RN we can chat about it as well

Updates from the webapp branch

---

src/actions/teams.js

We weren't removing the now-deleted channel members when we left a team so they would still show up in the sidebar upon rejoining the team.
https://mattermost.atlassian.net/browse/PLT-6585
This PR was tested on: Chrome on OS X

PLT-6585 Properly leave channels when leaving a team

---

src/actions/teams.js

Only fire leave channel events when current user leaves team

Only fire leave channel events when current user leaves team

---

src/client/client4.js

In order to be able to set a local push notification when the session expires on the RN app we need to be able to get a specific session that contains the `expires_at` property.
https://mattermost.atlassian.net/browse/RN-17

RN-17 Get current session

---

src/selectors/entities/channels.js
src/selectors/entities/users.js
test/selectors/channels.test.js
test/selectors/users.test.js

Add selector getting channel and user by username.

Add selector getting channel and user by username

---

src/actions/channels.js
src/actions/websocket.js
src/selectors/entities/channels.js
src/utils/post_utils.js
test/selectors/channels.test.js

* Make getChannel selector to complete direct channel info
* markChannelAsRead if channel and member are in the store
* Mark channel as unread if post is from webhook

Multiple Fixes

---

src/selectors/entities/channels.js
src/utils/channel_utils.js
test/selectors/channels.test.js
test/test_helper.js

This will build the same list as the one we are using for favorites, public, private and direct messages as the other function but will also include a unreads section
https://mattermost.atlassian.net/browse/RN-117

RN-117 Build channel list with Unreads section

---

src/actions/channels.js
src/reducers/entities/channels.js
test/actions/channels.test.js

Delete channel locally when leaving a private channel.

Delete channel locally when leaving a private channel

---

src/selectors/entities/channels.js
test/selectors/channels.test.js

Add selector to get group message channels

Add selector to get group message channels

---

src/action_types/teams.js
src/actions/channels.js
src/actions/teams.js
src/actions/users.js
src/actions/websocket.js
src/client/client4.js
src/reducers/entities/teams.js
src/reducers/requests/teams.js
test/actions/channels.test.js
test/actions/teams.test.js

Handle messages to mark the team as read or unread
https://mattermost.atlassian.net/browse/RN-137

Include team reads and unreads

---

src/action_types/users.js
src/actions/users.js
src/client/client4.js
src/reducers/requests/users.js
test/actions/users.test.js

Add action to set status

---

src/actions/channels.js
src/actions/teams.js
src/client/client4.js
test/actions/teams.test.js

* Adds a join team action
* Fixes markAsRead if the current channel is a DM or GM

add joinTeam action

---

src/actions/admin.js

Fix config update

---

src/actions/channels.js

Fixes an error where a mutation error is thrown since teamMembers is frozen
@jarredwitt

Fix frozen mutation error

---

src/client/client4.js

Add cluster ID to js client

---

src/actions/admin.js
src/client/client4.js
test/actions/admin.test.js

Add config argument to test email action.

Add config argument to test email action

---

src/utils/post_utils.js

https://mattermost.atlassian.net/browse/RN-160

RN-160 Fix isPostEphemeral util

---

src/actions/websocket.js

This PR fixes the `USER_REMOVED` WebSocket event, where the `LEAVE_CHANNEL` object being dispatched didn't have the correct data and now in the event that the channel is visible in other devices it will change the channel to the default one.

Fix WS leave channel event

---

src/selectors/entities/posts.js
src/utils/post_utils.js
test/selectors/posts.test.js

Some times according to the preferences we want to filter some posts, in this case this filters the join/leave messages

Filter posts in selector

---

src/action_types/users.js
src/actions/users.js
src/client/client4.js
src/reducers/requests/users.js
test/actions/users.test.js

Add some user actions. @enahum note I also added the form boundary to upload profile and brand image. I think that should take care of it for RN as well

User actions

---

src/actions/channels.js
src/actions/posts.js
src/actions/websocket.js
src/reducers/entities/channels.js
src/utils/channel_utils.js

When getting all the channels and members from the server we're going to remove the `myMembers` keys in the **channel** store that we already have just to make sure that those that were deleted aren't kept in the store
https://mattermost.atlassian.net/browse/RN-185

RN-185 Fix left channel and teams while disconnected

---

src/actions/users.js

Dispatch user from login before loading rest. Needed for MFA enforcement.
https://mattermost.atlassian.net/browse/PLT-6820

PLT-6820 Dispatch user from login before loading rest

---

src/selectors/entities/users.js
test/selectors/users.test.js

Needed for https://github.com/mattermost/platform/pull/6310

Added getUserByEmail selector

---

src/client/client4.js

Add brand image URL function to client.

Add brand image URL function to client

---

src/actions/users.js

Fix delete at for activating a user.

Fix delete at for activating a user

---

src/action_types/users.js
src/actions/users.js
src/client/client4.js
src/reducers/requests/users.js
test/actions/users.test.js

Add actions for switching login method.

Add actions for switching login method

---

src/actions/users.js

Merge 3.10 release branch

---

src/reducers/entities/posts.js
test/actions/posts.test.js

https://mattermost.atlassian.net/browse/PLT-6773

PLT-6773 Removed reactions for post when that post is deleted

---

src/actions/websocket.js
src/client/client4.js

Add client functions for pinned and flagged posts.

Add client functions for pinned and flagged posts

---

src/client/client4.js

Add client function for searching posts.

Add client function for searching posts

---

src/utils/post_utils.js

This PR adds a util function to check if a post is failed or pending

Adds a util function for checking if a post is failed or pending

---

src/actions/posts.js

Dispatch received post when create post action commits.
https://mattermost.atlassian.net/browse/PLT-6887

Dispatch received post when create post action commits

---

src/selectors/entities/channels.js

Fix null channel set causing JS error.

Fix null channel set causing JS error

---

src/actions/teams.js
src/client/client.js
src/client/client4.js

Use v3 endpoint for join team to be compatible with 3.8.

Use v3 endpoint for join team to be compatible with 3.8

---

src/action_types/teams.js
src/actions/teams.js
src/reducers/requests/teams.js
test/actions/teams.test.js

I need this to display an error on the select teams page in the RN app should one occur
https://mattermost.atlassian.net/browse/RN-204

RN-204 Added separate request state for joining teams

---

src/action_types/errors.js
src/actions/channels.js
src/actions/emojis.js
src/actions/errors.js
src/actions/files.js
src/actions/helpers.js
src/actions/integrations.js
src/actions/posts.js
src/actions/teams.js
src/actions/users.js
src/constants/general.js
src/reducers/errors/index.js

Guys take a look at this, before we weren't doing anything with the errors caught by the actions in terms of logging

Log errors to state and send them to MM

---

src/constants/general.js

https://mattermost.atlassian.net/browse/RN-203

RN-203 Added constants for RestrictDirectMessage setting

---

src/actions/integrations.js
test/actions/integrations.test.js

Add actions to get incoming and outgoing hook.

Add actions to get incoming and outgoing hook

---

src/constants/general.js
src/constants/preferences.js
src/selectors/entities/channels.js
src/selectors/entities/preferences.js
src/selectors/entities/typing.js
src/utils/channel_utils.js
src/utils/user_utils.js
test/selectors/channels.test.js
test/selectors/preferences.test.js

This will break RN until it's updated to support the new signature for displayUsername

Added support for server-side teammate name display setting

---

src/actions/admin.js
src/client/client4.js
test/actions/admin.test.js

Add config parameter to testElasticsearch.
https://mattermost.atlassian.net/browse/PLT-6474

Add config parameter to testElasticsearch.

---

src/selectors/entities/files.js
src/utils/post_utils.js

Change the file selector to receive only the postId and not the whole post.
Fixed post_util for `isSystemMessage` to always return a boolean

fix post util and change file selector

---

src/actions/websocket.js
src/reducers/entities/posts.js
test/actions/websocket.test.js

Adds the websocket events for receive and delete post reactions.

Add needed websocket events for emoji reactions

---

src/actions/general.js
test/actions/general.test.js

* Use apiV3 for ping until we remove APIv3 completely
* fix unit test

Merge RN release 1.0.1 into master

---

src/selectors/entities/integrations.js
src/store/initial_state.js

**Summary:**
Add selector and default state for oauthApps

Add selector and default state for oauthApps

---

src/actions/websocket.js
src/constants/websocket.js
test/actions/websocket.test.js

Adds emoji_added websocket event

Add emoji_added websocket event

---

src/reducers/entities/posts.js

Sort pending and failed posts to start of posts in channel.
https://mattermost.atlassian.net/browse/PLT-7187
This PR was tested on: webapp

PLT-7187 Sort pending and failed posts to start of posts in channel

---

src/reducers/entities/integrations.js
test/actions/channels.test.js

Delete webhooks when channel gets deleted to match server behavior.
https://mattermost.atlassian.net/browse/PLT-7255

PLT-7255 Delete webhooks when channel gets deleted

---

src/selectors/entities/channels.js
src/utils/channel_utils.js

Merge webapp-4.0 to master and fix conflicts

Merge webapp-4.0 to master and fix conflicts

---

src/client/client4.js

The RN library for segment is a little bit different that is why we need to include this changes in order to be able to track the same api calls.
https://mattermost.atlassian.net/browse/RN-288

RN-288 Add segment analytics for RN

---

src/actions/posts.js
src/reducers/entities/posts.js
test/actions/posts.test.js

Merge webapp-4.1 branch into master.

Merge webapp-4.1 branch into master

---

README.md

Correct 'encourgae' to 'encourage'

Fix trivial typo in README.md

---

src/actions/teams.js
src/client/client4.js
test/actions/teams.test.js

this implements the api/v4/teams/{team_id}/members endpoint, and adds unit tests.
This PR was tested on: [node 8.4.0 against mattermost-preview 4.1.0]

add getTeamMembers to client4 and create action for it.

---

README.md

Update README usage to use try catchs

Update README usage to use try catchs

---

src/actions/errors.js

Ignore failed fetch errors when sending to server.
https://mattermost.atlassian.net/browse/PLT-7418

PLT-7418 Ignore failed fetch errors when sending to server

---

src/client/client4.js

Add client function for getting webapp plugins. No actions added here because this is webapp specific.
Waiting on mattermost/mattermost-server#7445
https://mattermost.atlassian.net/browse/PLT-7622

PLT-7622 Add client function for getting webapp plugins

---

src/actions/channels.js
src/selectors/entities/teams.js
src/selectors/entities/users.js
src/utils/channel_utils.js
test/actions/channels.test.js
test/selectors/teams.test.js
test/selectors/users.test.js

Add various actions, selectors and utils to support channel header.
https://mattermost.atlassian.net/browse/PLT-7544

PLT-7544 Add various actions, selectors and utils to support channel header

---

Makefile
src/actions/websocket.js
src/constants/websocket.js
test/actions/websocket.test.js

Handle channel updated WebSocket events
https://mattermost.atlassian.net/browse/PLT-7677

Add channel_updated websocket action

---

src/actions/integrations.js
src/client/client4.js
src/store/initial_state.js
test/actions/integrations.test.js

Add editOAuthApp action, test and missing initial state for OAuth requests
https://github.com/mattermost/platform/issues/4752
This PR was tested on: [Desktop Ubuntu 16.04 LTS Google Chrome 58.0.3029.110 (64-bit)]

PLT-4752 Add editOAuthApp action

---

src/selectors/entities/posts.js
test/selectors/posts.test.js

Not add ephemeral post to replyCount
Jira ticket: [PLT-7566](https://mattermost.atlassian.net/browse/PLT-7566)
This PR was tested on: [Chrome/FF, Mac OS]

Not add ephemeral post to replyCount

---

src/actions/channels.js
src/client/client4.js

Add/distinguish telemetry for api channels events
- `api_channels_leave`
- `api_channels_join`
- `api_channels_add_member`
- `api_channels_remove_member`
Jira ticket: [PLT-7703](https://mattermost.atlassian.net/browse/PLT-7703)

[PLT-7703] Add/distinguish telemetry for api channels add/join/add/remove member events

---

src/client/client4.js

doPostAction update

---

src/selectors/entities/channels.js
src/selectors/entities/posts.js

https://mattermost.atlassian.net/browse/RN-402

Fix crashes when currentUser is null after offline store purge

---

src/actions/admin.js
src/actions/alerts.js
src/actions/channels.js
src/actions/emojis.js
src/actions/errors.js
src/actions/files.js
src/actions/general.js
src/actions/helpers.js
src/actions/integrations.js
src/actions/posts.js
src/actions/preferences.js
src/actions/search.js
src/actions/teams.js
src/actions/users.js
src/actions/websocket.js
test/actions/admin.test.js
test/actions/channels.test.js
test/actions/emojis.test.js
test/actions/files.test.js
test/actions/integrations.test.js
test/actions/teams.test.js
test/actions/users.test.js

All actions now return `{data, error}`. Please don't merge until the corresponding webapp and RN PRs are ready.
https://mattermost.atlassian.net/browse/PLT-7798
https://mattermost.atlassian.net/browse/PLT-7410

PLT-7798 All actions now return {data, error}

---

src/actions/users.js

Fix enableUserAccessToken typo - it was calling the wrong client method. 😮 
fix for PR #274

fix error in enableUserAccessToken action

---

src/action_types/admin.js
src/actions/admin.js
src/client/client4.js
src/reducers/entities/admin.js
src/reducers/requests/admin.js
test/actions/admin.test.js

Add support for inactive vs active plugins.

Add support for inactive vs active plugins

---

src/actions/channels.js
src/actions/users.js
src/constants/preferences.js
src/selectors/entities/channels.js
src/selectors/entities/posts.js
src/utils/channel_utils.js
test/selectors/channels.test.js
test/utils/channel_utils.test.js

Auto-closes DM/GM channels after 7 days with no new messages.
https://mattermost.atlassian.net/browse/PLT-7984
This PR was tested on: Chrome, MacOS

Auto-close dm / gm channels

---

README.md
package.json

Final updates for 1.0

---

src/store/initial_state.js

Fix a couple of unused state variables in the initial state.

Fix intitial state to match reducers state.

---

src/reducers/entities/admin.js
src/reducers/entities/users.js
test/actions/users.test.js

This got accidentally missed in the original PR.

Add enable/disable action handling in user access token reducers

---

src/selectors/entities/preferences.js
test/selectors/preferences.test.js

https://mattermost.atlassian.net/browse/RN-492

RN-492 Added fallback to default theme colours when missing from custom theme

---

src/utils/channel_utils.js

Changes`isFavoriteChannel` to not modify channel object and return boolean.

Change isFavoriteChannel to not modify channel object

---

src/store/configureStore.dev.js
src/store/initial_state.js

Add initial state for dev environment.

Add initial state for dev env

---

src/selectors/entities/channels.js

This PR should also be cherry picked for the RN dot release 1.4.1
https://mattermost.atlassian.net/browse/RN-470

Make sure the channel exists for getSortedDirectChannelIds

---

src/reducers/entities/teams.js

This PR will be cherry-picked for RN dot release 1.4.1

Keep previous member mention and msg count

---

package.json
src/selectors/entities/channels.js
src/store/configureStore.dev.js
src/utils/channel_utils.js

Ensure that closed DM's are not shown in favorites
via @jarredwitt

Is favorite fix

---

package.json

Changing eslint to use .gitignore for ignoring paths.

Change eslint to use .gitignore file for ignoring paths.

---

src/selectors/entities/posts.js
test/selectors/posts.test.js

Selector for the latest post to reply.
This PR was tested on: [Mac, Seirra]

Add new selector getLatestReplyablePost

---

.eslintrc.json
src/selectors/entities/posts.js
test/actions/channels.test.js
test/actions/integrations.test.js
test/test_store.js

Add rule to eslint for callExpression to have one argument a line

Fix eslint config for callExpression indentaion.

---

src/selectors/entities/posts.js
test/selectors/posts.test.js

Add getCurrentUsersLatestPost selector

Add getCurrentUsersLatestPost selector

---

src/actions/websocket.js

Handle user updated event for profile image change for current user. Same as mattermost/mattermost-webapp#323
https://mattermost.atlassian.net/browse/PLT-8103

PLT-8103 Handle user updated event for profile image change for current user

---

package.json

This is a proposal based on this conversation: https://pre-release.mattermost.com/core/pl/ke489sx953f89jsmupittcwgrw

Add source maps generation to build/dev/dev:watch

---

src/selectors/entities/preferences.js
test/selectors/preferences.test.js

Backwards compatible fix for theme.mentionBg typo.
https://mattermost.atlassian.net/browse/PLT-8142

PLT-8142 Backwards compatible fix for theme.mentionBg typo

---

src/utils/channel_utils.js

There was a bug in the sort, it shouldn't compare what the "types" are, only what the "order types" are. Caused by #305 
https://mattermost.atlassian.net/browse/PLT-8262

Fix GM/DM sidebar ordering

---

src/selectors/entities/alerts.js
src/selectors/entities/channels.js
src/selectors/entities/common.js
src/selectors/entities/integrations.js
src/selectors/entities/posts.js
src/selectors/entities/teams.js
src/selectors/entities/typing.js
src/selectors/entities/users.js

I was going to go through all the files and refactor out the simple selector functions at the top since they're most commonly imported by other files, but that seemed like a lot of unnecessary work, so I just fixed the problem ones. I also turned something back into a selector that would've otherwise caused a loop.

 Refactored some selectors to remove circular dependencies

---

src/actions/posts.js

This createPost action is to bypass redux-offline

Create immediate post action

---

src/actions/emojis.js
src/client/client4.js
src/constants/emoji.js
src/constants/index.js
test/actions/emojis.test.js

* Add sorting for get custom emojis actions
* Add actions for searching and autocompleting custom emojis
DO NOT MERGE UNTIL AFTER mattermost/mattermost-server#8125
Part of https://mattermost.atlassian.net/browse/ABC-96

ABC-96 Add new functionality for custom emojis

---

src/actions/emojis.js

Add optional profile loading to get custom emojis action. Based on #367 
Part of https://mattermost.atlassian.net/browse/ABC-96

ABC-96  Add optional profile loading to get custom emojis action

---

src/action_types/teams.js
src/actions/channels.js
src/actions/teams.js
src/actions/users.js
src/client/client4.js
src/reducers/requests/teams.js
test/actions/channels.test.js
test/actions/teams.test.js
test/actions/users.test.js

Below Functionalities are in Mattermost API v4 but missing in client4.js:
- patchUser (this partially update an user so that developers don't have specify every field in the user object)
- getTeamByName (this would be very helpful when team id is unknown)
- getChannelByNameAndTeamName (this would be very helpful when only team name and channel name are given)
- deleteTeam
I really hope these features to be included in the driver and benefit the future users.

Add more functionalities to client4.js

---

src/actions/teams.js
src/reducers/entities/teams.js

This fixes the action for deleteTeam and adds the necessary reducers to clean up the data in the store.

Fix deleteTeam action and add missing reducers

---

src/action_types/emojis.js
src/actions/emojis.js
src/client/client4.js
src/reducers/requests/emojis.js
test/actions/emojis.test.js

Add actions for getting custom emoji by name and id.
PLEASE DO NOT MERGE UNTIL AFTER mattermost/mattermost-server#8142
Part of https://mattermost.atlassian.net/browse/ABC-92

ABC-92 Add actions for getting custom emoji by name and id

---

src/utils/file_utils.js

Re : https://github.com/mattermost/mattermost-mobile/pull/1383
removing redux util that is no longer used.

ICU-573 removed util no longer used.

---

src/actions/emojis.js
src/actions/posts.js
src/actions/websocket.js
src/utils/emoji_utils.js
test/actions/emojis.test.js

Also adds handling for loading custom emojis for reactions.
https://mattermost.atlassian.net/browse/ABC-122

ABC-122 Split out custom emoji text parsing and add action to get custom emoji in text

---

src/actions/emojis.js
src/actions/users.js
src/utils/helpers.js
test/actions/emojis.test.js
test/utils/helpers.test.js

Emoji backwards compatibility with pre 4.7 servers.

Emoji backwards compatibility with pre 4.7 servers

---

src/selectors/entities/posts.js
src/utils/post_utils.js
test/utils/post_utils.test.js

This is for 4.7 of the web app, so a quick review would be good
https://mattermost.atlassian.net/browse/ICU-653
This PR was tested on: iOS Simulator, Chrome on Windows 10

ICU-653 Stopped filtering out join/leave messages about the current user

---

src/constants/posts.js

Add system team messages such as join, leave, add and remove to ignored post types when receiving new post event, so it will not count as unread message
Jira ticket: [ICU-705](https://mattermost.atlassian.net/browse/ICU-705)
This PR was tested on: [MacOS/Chrome]

[ICU-705] Add system team messages such as join, leave, add and remove to ignored post types

---

src/actions/posts.js
src/actions/websocket.js
test/actions/posts.test.js

Fixes:
* Editing a non-loaded custom emoji into a post
* Receiving a reaction for a non-loaded custom emoji
Thanks to @enahum for finding the first one

Fix two corner cases for emoji loading

---

src/selectors/entities/channels.js
src/selectors/entities/roles.js
src/utils/channel_utils.js
src/utils/post_utils.js
test/selectors/roles.test.js
test/test_helper.js

Rename permissions selectors to change Perm to Permission

Rename permissions selectors to change Perm to Permission

---

src/actions/posts.js
src/reducers/entities/posts.js
src/reducers/entities/search.js

https://mattermost.atlassian.net/browse/MM-9374

Fix reducer for permalink and search

---

src/action_types/teams.js
src/actions/teams.js
src/client/client4.js
src/reducers/requests/teams.js
test/actions/teams.test.js

Integration of team icon upload / notification mechanics.
https://github.com/mattermost/mattermost-server/issues/7616
https://github.com/mattermost/mattermost-server/pull/8284
https://github.com/mattermost/mattermost-webapp/pull/796
https://github.com/mattermost/mattermost-api-reference/pull/334
This PR was tested on: Ubuntu 16.04, Chrome

PLT-7567: Integration of Team Icons

---

src/action_types/admin.js
src/actions/admin.js
src/client/client4.js
src/reducers/requests/admin.js
src/store/initial_state.js
test/actions/admin.test.js

add support for ec2 instance profile authentication
github: https://github.com/mattermost/mattermost-server/issues/7875
server: https://github.com/mattermost/mattermost-server/pull/8243
webapp: https://github.com/mattermost/mattermost-webapp/pull/772
api-reference: https://github.com/mattermost/mattermost-api-reference/pull/336

[PLT-8186] add support for ec2 instance profile authentication

---

src/selectors/entities/preferences.js
src/store/initial_state.js
test/actions/posts.test.js
test/selectors/preferences.test.js

@hmhealey, this is in response to a comment you made on one of my PRs a month or so ago:
https://github.com/mattermost/mattermost-webapp/pull/716#discussion_r166404190
Just now getting back to addressing some cleanup items. This change also contains a separate commit for cleaning up some pre-existing linting failures required to submit -- see separate commits. I'll be leveraging this in a forthcoming webapp PR to complete addressing your feedback.
None.
This PR was tested on: Chrome, OSX

Add preferences getInt selector

---

src/actions/users.js
src/client/client4.js

Added sort='status' to lookups for Users in Channel for listing first 100 users in a channel
https://mattermost.atlassian.net/browse/ICU-668
https://github.com/mattermost/mattermost-server/pull/8181
https://github.com/mattermost/mattermost-api-reference/pull/329
https://github.com/mattermost/mattermost-webapp/pull/747

MM-9274 Added sort=‘status’ to querystring

---

src/selectors/entities/typing.js

Adding typing selector using channelId and postId as options parameter (this
will help to remove the user_typing_store from the frontend).

Add typing selector based on channelId and postId

---

src/constants/posts.js
src/utils/post_utils.js

Add new ephemeral post as EPHEMERAL_ADD_TO_CHANNEL
- This is an ephemeral post at Thread of mobile app (or RHS on webapp) after a user has been added thru at-mention.
Jira ticket: [MM-9516](https://mattermost.atlassian.net/browse/MM-9516)

[MM-9516] Add new ephemeral post as EPHEMERAL_ADD_TO_CHANNEL

---

src/utils/theme_utils.js

I'm going to import these functions from the mobile and web apps instead of each repo containing its own version of them.

Added blendColors and added flow types to theme_utils

---

src/constants/general.js
src/constants/posts.js

Add constants for mobile and webapp support
* OUT_OF_OFFICE = ooo
* SYSTEM_AUTO_RESPONDER = system_auto_response
via @miguelespinoza

Add Out Of Office support

---

src/constants/permissions.js

Server PR: https://github.com/mattermost/mattermost-server/pull/8516

Fix MANAGE_SYSTEM_WIDE_OAUTH permission typo.

---

src/selectors/entities/channels.js
src/selectors/entities/common.js
src/selectors/entities/users.js

Fix for circular dependency.
n/a
This PR was tested on: n/a

Circular dep fix

---

src/actions/channels.js
src/actions/general.js
src/actions/teams.js
src/actions/users.js

Change proposed by elias, use directly dispatch(loadRolesIfNeeded(...)) instead of loadRolesIfNeeded(...)(dispatch, getState)

Changed how loadRolesIfNeeded calls are dispatched

---

src/selectors/entities/posts.js

Encountered error on pre-release after opening the Release Discussion channel

Quick fix for cannot read property "user_id" of undefined

---

src/selectors/entities/channels.js
src/utils/channel_utils.js
test/utils/channel_utils.test.js

Do not auto close DM if it is being viewed.
https://mattermost.atlassian.net/browse/MM-9792

MM-9792 Do not auto close DM if it is being viewed

---

src/actions/channels.js
src/actions/teams.js
src/actions/users.js

Add missing getState on forceLogoutIfNecessary for some calls that didn't included that.

Add missing getState on forceLogoutIfNecessary

---

src/utils/post_utils.js
test/utils/post_utils.test.js

Not allowing to edit others posts in the interface
[MM-10136](https://mattermost.atlassian.net/browse/MM-10136)

MM-10136: Not allowing to edit others posts in the interface

---

src/store/initial_state.js

Adds initial request state for roles.
n/a
This PR was tested on: none.

Adds initial request state to roles.

---

package.json

I realized I forgot this step with the other PR so `npm install` may currently try to update stuff

Added explicit versions to all packages

---

src/actions/channels.js
src/client/client4.js
test/actions/channels.test.js

Add Client4.convertChannelToPrivate
GitHub issue: https://github.com/mattermost/mattermost-server/issues/7775
This PR was tested on: [MacOS/Chrome/FF]

[GH-7775] Add Client4.convertChannelToPrivate

---

src/utils/channel_utils.js

Fix channel deletion and edition permissions check
[MM-10298](https://mattermost.atlassian.net/browse/MM-10298)
This PR was tested on: [Android, 8.0.0]

MM-10298: Fix channel deletion and edition permissions check

---

src/action_types/teams.js
src/actions/teams.js
src/client/client4.js
src/reducers/requests/teams.js
test/actions/teams.test.js

Add request for Client4.removeTeamIcon
Server PR - https://github.com/mattermost/mattermost-server/pull/8684
Jira ticket: [MM-10354](https://mattermost.atlassian.net/browse/MM-10354)

[MM-10354] Add request for Client4.removeTeamIcon

---

src/action_types/index.js
src/action_types/schemes.js
src/actions/schemes.js
src/client/client4.js
src/constants/schemes.js
src/reducers/entities/channels.js
src/reducers/entities/index.js
src/reducers/entities/schemes.js
src/reducers/entities/teams.js
src/reducers/requests/index.js
src/reducers/requests/schemes.js
src/selectors/entities/schemes.js
src/store/initial_state.js
src/types/channels.js
src/types/schemes.js
src/types/store.js
src/types/teams.js
test/actions/roles.test.js
test/actions/schemes.test.js
test/selectors/schemes.test.js
test/test_helper.js

Adds Schemes support.
[MM-8786](https://mattermost.atlassian.net/browse/MM-8786)

MM-8786: Adds Schemes.

---

src/constants/general.js
src/selectors/entities/channels.js
src/selectors/entities/i18n.js
src/selectors/entities/teams.js
src/utils/channel_utils.js
test/selectors/i18n.test.js
test/test_helper.js

Porting this over from the mobile repo so that I can use it in the web app for 4.10.

Added getCurrentUserLocale selector

---

src/actions/posts.js
test/actions/posts.test.js

The previous version didn't work because the OpenGraph library returns an empty description for any valid link
https://mattermost.atlassian.net/browse/MM-10360

MM-10360 Only show link previews if they have a url defined

---

src/constants/preferences.js
src/utils/notify_props.js
test/utils/notify_props.test.js

Add utility function and constant to fix email notification issue on mobile RN
Note: This is not for v4.10 but for mobile RN v1.9
PR for Mobile RN - ~~to follow~~ https://github.com/mattermost/mattermost-mobile/pull/1654
Jira ticket: [MM-10215](https://mattermost.atlassian.net/browse/MM-10215)
This PR was tested on: [MacOS/Chrome/FF, iPhone 8 simulator/Android emulator 6]

[MM-10215] Add utility function and constant to fix email notification issue on mobile RN

---

src/selectors/entities/common.js
src/selectors/entities/general.js
src/utils/i18n_utils.js
src/utils/user_utils.js

Fixed type errors that `npm run flow` raised.
This PR was tested on: [Archlinux]

Fix flow errors raised from `npm run flow`

---

src/actions/alerts.js
src/reducers/entities/alerts.js
src/selectors/entities/alerts.js
src/types/alerts.js
src/types/store.js

Type definitions added to alerts
This PR was tested on: [Archlinux]

Flow type definitions added to alerts

---

src/reducers/entities/admin.js
test/reducers/entities/admin.test.js

This complements some rework required to support the plugin statuses
that correctly handles HA/clusters.
https://mattermost.atlassian.net/browse/MM-8622

MM-8622: s/cluster_discovery/cluster/

---

src/actions/jobs.js
src/reducers/entities/jobs.js
src/selectors/entities/jobs.js

Migrating jobs code to flow
This PR was tested on: [ArchLinux]

Adding jobs flow annotations

---

src/utils/post_utils.js
test/utils/post_utils.test.js

Fix combined posts which ignores custom and other post types
None but posted here - https://pre-release.mattermost.com/core/pl/e7kgqmhjhtr5iyt3qyik5e6qcw
This PR was tested on: [MacOS/Chrome/FF, iOS simulator]

Fix combined posts which ignores custom and other post types

---

src/actions/general.js
src/actions/websocket.js
src/client/websocket_client.js

Enable WS options for CBA and ping to actually show the correct error to the user
https://mattermost.atlassian.net/browse/MM-10127

CBA Support

---

src/action_types/schemes.js
src/actions/schemes.js
src/actions/teams.js
src/client/client4.js
src/constants/schemes.js
src/reducers/entities/schemes.js
src/reducers/requests/schemes.js
src/selectors/entities/schemes.js
src/types/schemes.js
src/types/store.js
test/actions/schemes.test.js
test/selectors/schemes.test.js

Add searchTeams action and client4 call.
[MM-8789](https://mattermost.atlassian.net/browse/MM-8789)

MM-8789: Add search teams endpoint and action

---

src/constants/general.js
src/selectors/entities/general.js
test/selectors/general.test.js

https://mattermost.atlassian.net/browse/MM-9547

MM-9547 Added selector for CustomUrlSchemes setting

---

Makefile
PULL_REQUEST_TEMPLATE.md
src/action_types/roles.js
src/actions/schemes.js
src/client/index.js
src/reducers/entities/index.js
src/reducers/index.js
src/reducers/requests/index.js
src/reducers/requests/roles.js
src/store/index.js
src/types/actions.js
src/types/admin.js
src/types/channels.js
src/types/emojis.js
src/types/files.js
src/types/general.js
src/types/integrations.js
src/types/jobs.js
src/types/posts.js
src/types/requests.js
src/types/schemes.js
src/types/search.js
src/types/store.js
src/types/teams.js
src/types/users.js

Preparing last details to start the flow campaign, including migration of
trivial files (only @flow tag needed), make all objects definitions stricter, add the checks list for check-style,
test and flow, and adding the flow to test execution.

Preparing last details for start the flow campaign

---

src/reducers/entities/typing.js
src/selectors/entities/typing.js
src/types/store.js
src/types/typing.js

Migrate typing to flow

---

src/actions/websocket.js

Fix permission error on channel_converted event (in used by mobile RN).
Jira ticket: [MM-10519](https://mattermost.atlassian.net/browse/MM-10519)
This PR was tested on: [macOS/Chrome/FF, iOS simulator]

[MM-10519] Fix permission error on channel_converted event (in used by mobile RN)

---

src/actions/roles.js
src/store/initial_state.js

Fix for set throwing an error when being instantiated with an object.
n/a
iOS Emulator

Safely trying to instantiate Set.

---

src/actions/roles.js
src/store/initial_state.js
src/utils/helpers.js

Relese5.0 merge master 20180611

---

.eslintrc.json

As per dev decision.
n/a
n/a
n/a

Disables ESLint 'complexity' rule.

---

src/selectors/entities/posts.js
src/store/configureStore.dev.js
src/utils/post_utils.js
test/utils/post_utils.test.js

Daily sync from `release-5.0` branch to `master`

Release 5.0 merge to master 20180614

---

build/Jenkinsfile

@jwilander @lieut-data 
sorry for the changes, I realized that previous one does not work with the directive `when`. so changing the pipeline to be declarative

fix jenkinspipeline

---

src/selectors/entities/users.js
test/selectors/users.test.js

Merge release-5.0 branch to master
- add makeGetProfilesByIdsAndUsernames (#538)

add makeGetProfilesByIdsAndUsernames (#538)

---

src/reducers/entities/search.js
src/selectors/entities/posts.js
test/reducers/entities/search.test.js

Adds the infrastructure used to store and retrieve search matches
https://mattermost.atlassian.net/browse/MM-6988

MM-6988 Added getSearchMatches selector

---

src/store/configureStore.dev.js
src/store/configureStore.prod.js
src/store/helpers.js
src/store/reducer_registry.js
test/store/reducer_registry.test.js

Mainly to be used for plugins but could also be used for code splitting purposes in the future.
https://mattermost.atlassian.net/browse/MM-10902

MM-10902 Add reducer registry to allow dynamically adding reducers

---

src/actions/errors.js
test/actions/errors.test.js

https://mattermost.atlassian.net/browse/MM-10818

Prevent "Invalid or expired session" errors from being added the error store

---

src/types/emojis.js
src/utils/emoji_utils.js

Migrating utils/emojis_utils.js file to flow

Migrating emojis utils to flow

---

src/actions/websocket.js

Cherry-picking the changes made in #545 into master

Silence fetch errors caused by websocket action

---

build/Jenkinsfile

Remove stage that setup and test using a live server. Discussed in the dev meeting.

remove stage with live server tests

---

src/client/websocket_client.js

https://mattermost.atlassian.net/browse/MM-11016

MM-11016 Prevent error when failing to parse websocket origin

---

src/selectors/entities/preferences.js

With recent changes to the mentionBg prop there was a use case missing

Fix theme mentionBg fallback

---

src/types/requests.js
src/types/store.js

Fix flow errors

---

src/utils/helpers.js
test/utils/helpers.test.js

Add email regex so it can be used across clients
This PR was tested on: [mac high sierra]

Add email regex for validation

---

src/actions/roles.js
src/types/roles.js
src/types/store.js

Added flow types to role.js
[#8994](https://github.com/mattermost/mattermost-server/issues/8994)

GH-8994 added flow assertions to roles js

---

src/actions/files.js

added flow types to files.js
https://github.com/mattermost/mattermost-server/issues/8993

GH-8993 added flow types to files js

---

src/client/websocket_client.js

Daily Merge from `release-5.1` to `master`

Release 5.1 daily merge 20180710

---

src/actions/timezone.js

Migrating timezone code to flow
[#8995](https://github.com/mattermost/mattermost-server/issues/8995)

GH-8995 added the flow types for timezone js

---

README.md

Test PR please ignore

---

src/actions/helpers.js
src/types/errors.js

Add flow typing to actions/helpers.js
[MM-11041](https://mattermost.atlassian.net/browse/MM-11041)
https://github.com/mattermost/mattermost-server/issues/8997
This PR was tested on: [Mac OS High Sierra, 10.13.5]

Migrate actions/helpers.js to flow

---

src/reducers/entities/admin.js

Update config in redux state when enabling/disabling plugins.
https://mattermost.atlassian.net/browse/MM-11362

MM-11362 Update config in redux state when enabling/disabling plugins

---

src/action_types/posts.js
src/actions/posts.js
src/client/client4.js
src/reducers/requests/posts.js
src/store/initial_state.js
src/types/requests.js
test/actions/posts.test.js

* Add getUnreadPostsAction
* Add getUnreadPosts initial state
* Add getUnreadPosts API to client4
https://mattermost.atlassian.net/browse/MM-11310
This PR was tested on: [mac Highsierra]

MM-11310: Add getUnreadPosts

---

src/actions/general.js
src/actions/helpers.js
src/actions/roles.js
src/types/actions.js
src/types/client4.js
src/utils/key_mirror.js

Add flow types to actions/general.js
https://github.com/mattermost/mattermost-server/issues/8996
This PR was tested on: [macOS High sierra, 10.13.5]

Add types to actions/general.js

---

src/selectors/entities/channels.js

Add check for undefined channel objects
[MM-11484](https://mattermost.atlassian.net/browse/MM-11484)

MM-11484 Add check for undefined channel objects

---

src/actions/channels.js
test/actions/channels.test.js

Fixed join to archived channel by clicking link
[MM-11576](https://mattermost.atlassian.net/browse/MM-11576)
This PR was tested on: Arch Linux

MM-11576: Fixed join to archived channel by clicking link

---

src/actions/channels.js
src/selectors/entities/channels.js
test/actions/channels.test.js
test/selectors/channels.test.js

Merge from `release-5.2` to `master`

Release 5.2 daily merge 20180810

---

build/.gitignore
build/Jenkinsfile
package-lock.json
package.json
src/client/client4.js
src/selectors/entities/channels.js
test/mocha-multi-reporters-config.json
test/mocha.opts

Some changes already included in mattermost-mobile are in master, out of
release-5.2 branch. I need to include every change included in
mattermost-mobile in the branch release-5.2 to be sure is properly
tagged and released.

Merging master into release-5.2 (For include last changes on mobile)

---

src/selectors/entities/channels.js
test/selectors/channels.test.js
test/test_helper.js

**NOTE:** This PR is a rebase of this other PR #597
Fixes unread for deleted users
[MM-11170](https://mattermost.atlassian.net/browse/MM-11170)

[MM-11170] Fix unreads for deleted users

---

src/selectors/entities/channels.js
test/selectors/channels.test.js
test/test_helper.js

Merge from `release-5.2` to `master`

Merge release-5.2-20180816094050

---

src/actions/posts.js
src/client/client4.js
test/actions/posts.test.js

Added changes to accept userId as param to reflect API change
[MM-11528](https://mattermost.atlassian.net/browse/MM-11528)

MM-11528 Change unreads API to accept userID as param

---

src/action_types/general.js
src/actions/general.js
src/client/client4.js
test/actions/general.test.js

Adds client method and action to `getRedirectLocation` for newly added API endpoint.
[MM-11786](https://mattermost.atlassian.net/browse/MM-11786)
Chrome browser, macOS.

MM-11786: Adds getRedirectLocation.

---

src/actions/channels.js
test/actions/channels.test.js

Factor out marking GMs open to a separate action so it can be called by the web app when needed.
https://mattermost.atlassian.net/browse/MM-11696

MM-11696 Factor out marking GMs open to a separate action

---

src/actions/admin.js
src/actions/channels.js
src/actions/emojis.js
src/actions/files.js
src/actions/general.js
src/actions/helpers.js
src/actions/integrations.js
src/actions/posts.js
src/actions/schemes.js
src/actions/search.js
src/actions/teams.js
src/actions/users.js

Fixes dispatching of logErrors
[MM-11533](https://mattermost.atlassian.net/browse/MM-11533)

MM-11533 Fixes Redux dispatching undefined for dispatching results of logError

---

src/selectors/entities/channels.js
test/selectors/channels.test.js
test/test_helper.js

Exclude deleted users from the favourites list
[MM-11717](https://mattermost.atlassian.net/browse/MM-11717)
Mac os high sierra

[MM-11717] Exclude deleted users from favourites list

---

src/selectors/entities/channels.js
test/selectors/channels.test.js
test/test_helper.js

Merge from `release-5.3` to `master`

Merge release-5.3-20180903124818

---

src/actions/emojis.js
test/actions/emojis.test.js

Needed to load the proper users on the web app when searching on the custom emoji management page.
https://mattermost.atlassian.net/browse/MM-11706

MM-11706 Split out profile loading for emojis into new function and add it to search

---

src/actions/posts.js
src/selectors/entities/posts.js
src/utils/emoji_utils.js
src/utils/post_utils.js
test/actions/posts.test.js
test/selectors/posts.test.js
test/utils/post_utils.test.js

Merge from `release-5.3` to `master`

Merge release-5.3-20180910141323

---

src/actions/channels.js
src/client/client4.js
test/actions/channels.test.js

Adding new search_autocomplete channels api to the client and to the
actions.
[MM-11725](https://mattermost.atlassian.net/browse/11725)

MM-11725: Adding new search_autocomplete channels api

---

src/actions/general.js
src/reducers/requests/general.js
src/selectors/entities/general.js
src/store/initial_state.js
test/actions/general.test.js

Merge from `release-5.3` to `master`

Merge release-5.3-20180912130737

---

package.json

For this time i will publish manually to npm.
for the subsequent releases the release pipeline will do that and this will be the steps
1 if we have a successful build and it is an official release (not an rc)
1.1 bump the package version in package.json
1.2 push the bump change to redux github
1.3 push the package to npm
cc @enahum

bump package version to 5.3.1

---

src/actions/channels.js
src/actions/websocket.js

Do not redirect to default channel on delete if archived channels are enabled
[MM-11577](https://mattermost.atlassian.net/browse/MM-11577)

MM-11577: Do not redirect to default channel on delete if archived channels are enabled

---

src/constants/preferences.js

Add Preferences constants of ADVANCED_SEND_ON_CTRL_ENTER and ADVANCED_CODE_BLOCK_ON_CTRL_ENTER
Jira ticket: [MM-11959](https://mattermost.atlassian.net/browse/MM-11959)

[MM-11959] Add Preferences constants of ADVANCED_SEND_ON_CTRL_ENTER and ADVANCED_CODE_BLOCK_ON_CTRL_ENTER

---

src/actions/admin.js
src/actions/general.js
src/selectors/entities/general.js
src/types/actions.js
src/types/requests.js

Fixing flow errors

---

test/actions/channels.test.js
test/selectors/channels.test.js

Fix test on node version 10.
This change is also tested on lower versions like version 8 and 9 and it's also passing all tests.
Jira ticket: [MM-12490](https://mattermost.atlassian.net/browse/MM-12490)

[MM-12490] Fix test on node version 10

---

src/actions/helpers.js
src/actions/roles.js
src/actions/users.js

Migrate to Flow file src/actions/users.js in mattermost-redux
- [Jira Ticket](https://mattermost.atlassian.net/browse/MM-11042)
- [GitHub Issue](https://github.com/mattermost/mattermost-server/issues/9302)
- ~~Ran `make test` to ensure unit tests passed~~
- ~~Added or updated unit tests (required for all new features)~~
- ~~All new/modified APIs include changes to the drivers~~

MM-11042: Migrate to Flow file src/actions/users.js in mattermost-redux

---

src/selectors/entities/channels.js
test/selectors/channels.test.js

Need to get channels for arbitrary teams.
https://mattermost.atlassian.net/browse/MM-12792

MM-12792 Add channel map selectors for arbirtrary teams

---

src/reducers/entities/posts.js
test/reducers/entities/posts.test.js

The changes for this PR are only in [this commit](https://github.com/mattermost/mattermost-redux/commit/39a817bf9d003f6fb09701e3e43a29894fc15e44) since it's based off of https://github.com/mattermost/mattermost-redux/pull/689
https://mattermost.atlassian.net/browse/MM-12827
https://mattermost.atlassian.net/browse/MM-12828

MM-12827/MM-12828 Populate reactions from post metadata

---

src/selectors/entities/channels.js
test/selectors/channels.test.js

Sorting for unreads with muted channels should follow this order
1. If muted channels have unreads mentions they should be sorted to be at the end of mention channels
2. If multiple muted channels have mentions they should be sorted alphabetically at the bottom of mention channels list 
[MM-12841](https://mattermost.atlassian.net/browse/MM-12841)
[MM-12841](https://mattermost.atlassian.net/browse/MM-12638)

MM-12841 Fix for mention channel ordering with unread channels

---

src/reducers/entities/posts.js
test/reducers/entities/posts.test.js

https://mattermost.atlassian.net/browse/MM-12874

MM-12874 Store OpenGraph metadata in correct part of store

---

src/actions/channels.js
src/types/channels.js

Migrate to Flow file src/actions/channels.js in mattermost-redux
https://mattermost.atlassian.net/browse/MM-11048
This PR was tested on: Macbook Pro, MacOS High Sierra 10.13.6
This completes this issue https://github.com/mattermost/mattermost-server/issues/9766

Adding channels flow annotations

---

src/actions/admin.js

Remove redux hack to separate create terms of service from admin config
https://mattermost.atlassian.net/browse/MM-12414
This PR was tested on: `Chrome on Ubuntu 18.04`

MM-12414 Remove redux hack

---

src/client/client4.js
test/client/client4.test.js

https://mattermost.atlassian.net/browse/MM-13020

MM-13020 Make ClientError.message enumerable

---

src/selectors/entities/posts.js
src/utils/post_utils.js
test/selectors/posts.test.js
test/utils/post_utils.test.js

Adds a new selector to check if a post should have a highlighted bar based on user pref
[MM-12755](https://mattermost.atlassian.net/browse/MM-12755)

MM-12755 Add selector for isCommentMention

---

src/actions/websocket.js
src/client/websocket_client.js
test/actions/websocket.test.js

I was looking to get posts as soon as the WS reconnects and fixing up a bit the reconnect logic, and I ended up modifying a bit of code to make the WebSocket actions a bit better.
https://mattermost.atlassian.net/browse/MM-12832
https://mattermost.atlassian.net/browse/MM-13039

WebSocket actions improvement

---

src/client/client4.js

In order to reduce our segment usage, temporarily only collect 1 client side telemetry event.
https://mattermost.atlassian.net/browse/MM-13062

MM-13062: Only collect 1 telemetry event temporarily.

---

src/actions/channels.js
src/actions/websocket.js
src/reducers/entities/posts.js
test/actions/websocket.test.js
test/reducers/entities/posts.test.js

Remove archived channels posts from search results when needed
[MM-12839](https://mattermost.atlassian.net/browse/MM-12839)
This PR was tested on: [Arch linux]

MM-12839: Remove archived channels posts from search results when needed

---

src/actions/users.js

Make API request only when terms are enabled.
https://mattermost.atlassian.net/browse/MM-12400
This PR was tested on Ubuntu 18.04 / Chrome

MM-12400:  Call get my terms of service only if the terms of service feature is enabled

---

src/client/client4.js

Track events for interactive messages and dialogs.
https://mattermost.atlassian.net/browse/MM-12574

MM-12574 Track events for interactive messages and dialogs

---

src/actions/websocket.js

https://mattermost.atlassian.net/browse/MM-13252

Fix handleNewPostEvent for replies

---

package-lock.json
package.json
test/actions/websocket.test.js

Update dev dependency mock-socket to 8.0.5 (latest stable version)
Jira ticket: [MM-13323](https://mattermost.atlassian.net/browse/MM-13323)

[MM-13323] Update dev dependency mock-socket to 8.0.5

---

src/types/integrations.js
src/types/users.js
src/utils/file_utils.js
src/utils/gfycat_sdk.js
src/utils/helpers.js
src/utils/integration_utils.js
src/utils/notify_props.js
src/utils/timezone_utils.js

Migrate to some utils files to use flow

Migrate to some utils files to use flow

---

src/actions/channels.js
src/reducers/entities/emojis.js
src/reducers/entities/jobs.js
src/selectors/entities/channels.js
src/selectors/entities/common.js
src/selectors/entities/emojis.js
src/selectors/entities/jobs.js
src/selectors/entities/typing.js
src/types/channels.js
src/types/integrations.js
src/types/jobs.js
src/types/posts.js
src/types/users.js
src/types/utilities.js
src/utils/channel_utils.js
src/utils/team_utils.js
src/utils/user_utils.js

Migrating channel selectors to flow

Migrating channel selectors to flow

---

src/selectors/entities/channels.js
test/selectors/channels.test.js

* Update unreadCount selector to take into account other teams count values
[MM-13627](https://mattermost.atlassian.net/browse/MM-13627)

MM-13627 Fix DM and GM mention counts missing from browser tab

---

build/Jenkinsfile

Applying the same we did for Server (https://github.com/mattermost/mattermost-server/pull/10180)

add timeout for jenkins job

---

.flowconfig
package.json
src/selectors/entities/users.js
src/types/users.js
src/types/utilities.js
src/utils/user_utils.js

Migrate to flow selectors and utils for users.

Migrate to flow selectors of users

---

src/actions/general.js
src/reducers/entities/posts.js
src/reducers/entities/posts.test.js
src/selectors/entities/posts.js
src/selectors/entities/posts.test.js
src/store/initial_state.js
src/types/posts.js

This is the redux-part of [issue #2507 on mattermost-moblie](https://github.com/mattermost/mattermost-mobile/issues/2507) and [pr #2538](https://github.com/mattermost/mattermost-mobile/pull/2538)
https://github.com/mattermost/mattermost-mobile/issues/2507
This PR was tested on: Huawei P20 Lite, Android 8.0.0

Store expanded URLs

---

src/selectors/entities/posts.js
src/types/posts.js

Fixes the flow type for a post's reactions.
https://mattermost.atlassian.net/browse/MM-13954
* Samsung Galaxy S7, Android 7.0

[MM-13954] Fix flow type for post reactions

---

src/utils/channel_utils.js

Need it for use in the web app.

Export isUnreadChannel from channel_utils

---

package-lock.json
src/action_types/bots.js
src/action_types/index.js
src/actions/bots.js
src/actions/bots.test.js
src/client/client4.js
src/reducers/entities/bots.js
src/reducers/entities/index.js
src/selectors/entities/bots.js
test/test_helper.js

Added for bot accounts:
- Client4 methods
- Reducers
- Actions
- Selectors
https://mattermost.atlassian.net/browse/MM-13620
https://mattermost.atlassian.net/browse/MM-13622
This PR was tested on: ArchLinux

MM-13622 MM-13620 Adding client4 methods, reducers, actions, and selectors for bot accounts.

---

README.md

If someone were to use promise, it would be clearer to write their code this way, doing so they would take advantage of the promises.
There is no ticket for that tell me if I need to create one (in which case I will strongly reconsider contributing this piece of doc since it would mean creating an account on a third party site and all ...)
This PR was not tested at all. The mentionned code was tested in a console on chrome

[Documentation] simplified the "Promise" example

---

src/action_types/users.js
src/actions/users.js
src/actions/users.test.js
src/client/client4.js
src/reducers/entities/users.js
src/selectors/entities/users.js
src/selectors/entities/users.test.js
src/store/initial_state.js
src/types/users.js

Embedded user TOS data into the user object itself.
This PR was tested on: Mozilla Firefox on MacOS Mojave. Pending testing on mattermost desktop app and mobile apps.

Used user TOS data embedded in user object itself

---

src/actions/teams.js
src/client/client4.js

Allow to invalidate email invites
[MM-14748](https://mattermost.atlassian.net/browse/MM-14748)

MM-14748: Allow to invalidate email invites

---

src/types/channels.js
src/types/teams.js
src/utils/channel_utils.js

Adds new field to Team and Channel types.
https://mattermost.atlassian.net/browse/MM-14642
Chrome 73 on macOS.

MM-14642: Adds new field to Team and Channel types.

---

src/constants/permissions.js

Adding VIEW_MEMBERS permissions to permissions constants
[MM-14138](https://mattermost.atlassian.net/browse/MM-14138)

Adding VIEW_MEMBERS permissions to permissions constants

---

src/actions/channels.js
src/actions/websocket.js
src/actions/websocket.test.js
src/selectors/entities/channels.js
src/selectors/entities/channels.test.js

Change the concept of DEFAULT_CHANNEL to RedirectChannel
[MM-14639](https://mattermost.atlassian.net/browse/MM-14639)

Creating the concept of RedirectChannel and use it before the DefaultChannel when we are redirecting the user

---

src/actions/preferences.js
src/actions/preferences.test.js

This is a migration PR for https://github.com/mattermost/mattermost-webapp/pull/2679

Add actions to save/delete theme preference

---

CONTRIBUTING.md

Follow up on https://github.com/mattermost/mattermost-server/pull/10749

Remove outdated information from contributing file

---

src/utils/post_list.js
src/utils/post_list.test.js

Add getLastPostIndex, per https://github.com/mattermost/mattermost-mobile/pull/2719#discussion_r281170424
Jira ticket: [MM-13955](https://mattermost.atlassian.net/browse/MM-13955)
This PR was tested on: [Android emulator]

[MM-13955] Add getLastPostIndex

---

package.json
src/actions/channels.js
src/client/client4.js

Adds params for channels page API endpoint.
https://mattermost.atlassian.net/browse/MM-15422
Chrome browser v74, macOS
* https://github.com/mattermost/mattermost-server/pull/10903

MM-15422: Adds params for channels page API endpoint.

---

src/constants/plugins.js

Update prepackaged plugins list for 5.12
[MM-16143](https://mattermost.atlassian.net/browse/MM-16143)

[MM-16143] update prepackaged plugins list for 5.12

---

package.json
src/action_types/teams.js
src/actions/teams.js
src/actions/teams.test.js
src/client/client4.js

Adds client and action for new API endpoint.
https://mattermost.atlassian.net/browse/MM-16258
Chrome in macOS.
https://github.com/mattermost/mattermost-server/pull/11176

MM-16258: Add client and action for new API endpoint.

---

package-lock.json
package.json
src/selectors/entities/timezone.js
src/utils/post_list.js

With the changes of the post list and by moving the logic to get the list to redux we omitted the fact that a user can have a timezone set causing the date separators in the post list to reflect the wrong date when the timezone is set manually.
A follow up PR will be submitted against the webapp and mobile to include this redux changes.
https://mattermost.atlassian.net/browse/MM-16387

Set post list date separators based on the user timezone if available

---

package.json
src/action_types/channels.js
src/actions/channels.js
src/actions/channels.test.js
src/client/client4.js

Adds client and action for new API endpoint.
Channel version of https://github.com/mattermost/mattermost-redux/pull/853.
https://mattermost.atlassian.net/browse/MM-16224
Chrome in macOS.
https://github.com/mattermost/mattermost-server/pull/11186

MM-16224: Add client and action for new API endpoint.

---

src/actions/channels.js
src/actions/users.js
src/client/client4.js
src/constants/general.js

https://mattermost.atlassian.net/browse/MM-13500

[MM-13500] Add search group channels method to client

---

src/actions/groups.test.js
src/reducers/entities/channels.js
src/reducers/entities/teams.js
src/selectors/entities/groups.js
src/selectors/entities/groups.test.js

Add total count to the groups associated to teams and channels.
https://mattermost.atlassian.net/browse/MM-16504
Chrome on macOS.

MM-16504: Adds total count of groups associated to teams and channels.

---

src/action_types/teams.js
src/actions/teams.js
src/actions/teams.test.js
src/client/client4.js
src/reducers/entities/teams.js
src/store/initial_state.js
src/types/teams.js

Adds total count of teams to state.
https://mattermost.atlassian.net/browse/MM-16500
Chrome browser, macOS
* https://github.com/mattermost/mattermost-server/pull/11325

MM-16500: Adds total team count to state.

---

PULL_REQUEST_TEMPLATE.md

Unclarity from community on what this particular checklist item means https://community-release.mattermost.com/core/pl/cif78mhk1fn7ib71yiazobjper
cc: @hanzei eventually we may want to apply the new PR templates from webapp/server repos to others such as redux

Add a link to the JS driver in PR template

---

src/actions/teams.js
src/actions/users.js
src/client/client4.js
src/constants/general.js
src/constants/permissions.js
src/selectors/entities/channels.js

Cherry pick of #882 on release-5.14.
- #882: Adding guest permissions (#834)
/cc  @jespino

Automated cherry pick of #882

---

src/actions/teams.js
src/actions/users.js
src/client/client4.js
src/constants/general.js
src/constants/permissions.js
src/selectors/entities/channels.js

This reverts commit 4cbb61620ddcf0fcdbf4e40105457e146d6c4a05.
Revert Guest accounts feature

Revert Guest accounts feature

---

src/actions/posts.js
src/actions/posts.test.js

Cherry pick of #878 on release-5.14.
- #878: MM-16922 Opening a permalink from last few messages of a

Automated cherry pick of #878

---

src/selectors/entities/channels.js
src/selectors/entities/channels.test.js

Cherry pick of #887 on release-5.14.
- #887: Check for null channel
/cc  @migbot

Automated cherry pick of #887

---

src/selectors/entities/channels.test.js
src/selectors/entities/teams.js
src/selectors/entities/teams.test.js

Cherry pick of #888 on release-5.14.
- #888: filter archived teams out of my team membership selectors
/cc  @mickmister

Automated cherry pick of #888

---

src/constants/posts.js

https://mattermost.atlassian.net/browse/MM-17200
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/3366)
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/11803)

[MM-17200] Adds constants for new system posts for guests

---

src/reducers/entities/posts.js
src/reducers/entities/posts.test.js

Cherry pick of #901 on release-5.15.
- #901: MM-17866 Fix for channel loader when removing the last post

Automated cherry pick of #901

---

src/actions/posts.js
src/actions/posts.test.js
src/reducers/entities/posts.js
src/reducers/entities/posts.test.js
src/selectors/entities/posts.js
src/selectors/entities/posts.test.js
src/types/posts.js

Cherry pick of #908 on release-5.15.
- #908: MM-17643 Add the ability of keeping an oldest flag for

Automated cherry pick of #908

---

src/actions/posts.js
src/actions/posts.test.js

Cherry pick of #904 on release-5.15.
- #904: MM-17643 Add the ability of keeping an oldest flag for

Automated cherry pick of #904

---

src/action_types/admin.js
src/actions/admin.js
src/actions/admin.test.js
src/client/client4.js
src/reducers/requests/admin.js
src/store/initial_state.js
src/types/requests.js

Adds access to the new endpoint (added [here](https://github.com/mattermost/mattermost-server/pull/11944)).
https://mattermost.atlassian.net/browse/MM-14521
This PR was tested on: Macbook Pro running Ubuntu 19.04

[MM-14521] Added access to the new endpoint to test Site URLs

---

src/client/client4.js

Added marketplace diagnostics tracking events to the whilelist in the `trackEvent` method.
[MM-18103](https://mattermost.atlassian.net/browse/MM-18103)
- Webapp: https://github.com/mattermost/mattermost-webapp/pull/3611

MM-18103 - Added telemetry events for plugin marketplace

---

src/actions/admin.js
src/actions/admin.test.js
src/client/client4.js

Reverts mattermost/mattermost-redux#917

Revert "MM-18139 - Add signature_url param when invoking install_from_url api"

---

src/actions/users.js
src/client/client4.js

Add support for options in get profiles in and without team. No tests because they wouldn't be meaningful.
Part of https://mattermost.atlassian.net/browse/MM-18512
https://github.com/mattermost/mattermost-server/pull/12200

MM-18512 Add support for options in get profiles in and without team

---

src/actions/teams.js
src/actions/teams.test.js

This stops an issue where joining a new team after having no teams marks the previously viewed channel as read
https://mattermost.atlassian.net/browse/MM-16399

MM-16399 Clear current channel when leaving a team

---

src/actions/teams.js
src/actions/teams.test.js

Cherry pick of #931 on release-5.16.
- #931: MM-16399 Clear current channel when leaving a team
/cc  @hmhealey

Automated cherry pick of #931

---

src/actions/posts.js
src/actions/posts.test.js
src/client/client4.js
src/reducers/entities/posts.js

A companion PR to https://github.com/mattermost/mattermost-server/pull/12364
https://mattermost.atlassian.net/browse/MM-18623
This PR was tested on: Windows, Arch Linux, Chrome

MM-18623 - Handle reply-count in getPostThread code path

---

src/actions/posts.js
src/actions/posts.test.js
src/client/client4.js
src/reducers/entities/posts.js

Cherry pick of #933 on release-5.16.
- #933: refactored into two separate components. cleaned up css
/cc  @reflog

Automated cherry pick of #933

---

package-lock.json
src/actions/posts.js
src/actions/posts.test.js
src/client/client4.js

This reverts commits b514b8dcc81c98aabc5c811d86538557a203a4fb and ae457c33ea6f9171c4c87ef0b953bc3e402e159e.
https://mattermost.atlassian.net/browse/MM-18624
https://github.com/mattermost/mattermost-server/pull/12387
https://github.com/mattermost/mattermost-webapp/pull/3789
https://github.com/mattermost/mattermost-redux/pull/935

MM-18624: revert fetch threads support

---

src/actions/posts.js

Cherry pick of #930 on release-5.16.
- #930: Update message count and unread count in redux on

Automated cherry pick of #930

---

src/client/client4.js

Whitelisting `api_install_marketplace_plugin` event in redux.
Ticket: https://mattermost.atlassian.net/browse/MM-19318

MM-19318 - Update tracking events when marketplace plugin is installed

---

Makefile
babel.config.js
jest.config.js
src/reducers/entities/posts.ts

This PR fixes issues with Jest that were causing failing tests on some setups (reported by @hmhealey) and problems with Makefile no cleaning the folder properly

Typescript build fix

---

src/reducers/entities/posts.js
src/reducers/entities/posts.test.js

Cherry pick of #946 on release-5.17.
- #946: Added guard condition to not store reactions for deleted
/cc  @marianunez

Automated cherry pick of #946

---

src/action_types/channels.js
src/reducers/entities/channels.js
src/reducers/entities/channels.test.js

Cherry pick of #951 on release-5.17.
- #951: Adding new action type REMOVE_MEMBER_FROM_CHANNEL
/cc  @jespino

Automated cherry pick of #951

---

src/actions/websocket.js
src/actions/websocket.test.js

Tests were failing after the cherry pick, so did revert and cherry pick again.

Revert Cherry Pick of #956

---

src/store/helpers.js

Cherry pick of #965 on release-5.17.
- #965: Use action.data or baseState
/cc  @migbot

Automated cherry pick of #965

---

src/reducers/entities/teams.ts
src/selectors/entities/teams.ts

Removing implicit anys from team selectors and reducers

Removing implicit anys from team selectors and reducers

---

src/utils/post_list.ts

Removing some of the implicit anys to used in the source code (the objective is
to remove all of them and enable `noImplicitAny` setting in the
`tsconfig.json`)

Removing some implicit anys

---

src/actions/users.ts
src/client/client4.ts
src/client/fetch_etag.ts
src/types/client4.ts

Removing implicit anys from client4.ts

Removing implicit anys from client4.ts

---

src/actions/channels.ts
src/reducers/entities/channels.test.js
src/reducers/entities/channels.ts

- Prevents the active channel from being removed from the channels list. 
- Fixes and issue where fetching of channels on focus change would cause your view of an archived channel to crash.

MM-20272 Prevent channel reducers from deleting the active channel.

---

package-lock.json
src/actions/posts.test.js
src/actions/posts.ts
src/client/client4.ts
src/reducers/entities/posts.ts

Revert on the changes that improved performance loading threads
[MM-20725](https://mattermost.atlassian.net/browse/MM-20725)
This PR was tested on: [mac os x 10.14.6 + firefox]

 [MM-20725] Revert threads performance change on 5.18

---

src/actions/websocket.ts
src/constants/websocket.ts

Cherry pick of #998 on release-5.18.
- #998: add updating roles in redux
/cc  @hahmadia

Automated cherry pick of #998

---

.circleci/config.yml
src/reducers/entities/posts.ts

Switched to using `npm ci` on CI instead of `npm install`
https://mattermost.atlassian.net/browse/MM-20743

MM-20743  - CI uses npm ci instead of npm install

---

src/selectors/entities/channels.test.js
src/selectors/entities/channels.ts
test/test_helper.js

Cherry pick of #1013 on release-5.18.
- #1013: MM-21153 Fix channel selector tests involving unreads
/cc  @hmhealey

Automated cherry pick of #1013

---

src/actions/users.ts

Cherry pick of #1016 on release-5.18.
- #1016: Ensure roles in data.roles are always added
/cc  @migbot

Automated cherry pick of #1016

---

src/utils/notify_props.test.js
src/utils/notify_props.ts

Cherry pick of #997 on release-5.19.
- #997: MM-20260 - Email notification still sent while disabled in UI
/cc  @ali-farooq0

Automated cherry pick of #997

---

src/actions/websocket.test.js
src/actions/websocket.ts

Update websocket actions to dispatch roles when channel member role is changed
https://mattermost.atlassian.net/browse/MM-10858
Awaiting https://github.com/mattermost/mattermost-server/pull/13305

[MM-10858] Update websocket actions

---

src/client/client4.ts

Added `local_only` parameter to `GetMarketplacePlugins` to support displaying local plugins in the webApp when the remote marketplace server is unavailable.
[MM-19614](https://mattermost.atlassian.net/browse/MM-19614)
WebApp: WIP
Server PR: https://github.com/mattermost/mattermost-server/pull/13250

MM-19614 - Added local_only parameter to GetMarketplacePlugins

---

src/actions/posts.test.js
src/actions/posts.ts
src/client/client4.ts
src/reducers/entities/posts.ts

Thread fetching revert

---

SECURITY.md

Copied over some additional wording changes from the server repo.
https://mattermost.atlassian.net/browse/MM-20627

MM-20627: Update wording in SECURITY.md

---

src/constants/preferences.ts
src/types/preferences.ts
src/utils/theme_utils.test.js
src/utils/theme_utils.ts

Cherry pick of #1035 on release-5.20.
- #1035: Add theme type and function to set theme defaults
/cc  @jwilander

Automated cherry pick of #1035

---

Makefile
PULL_REQUEST_TEMPLATE.md

Updating the PR template to reflect the use of TypeScript.

Update PR template for TypeScript and added makefile command

---

src/actions/teams.ts
src/client/client4.ts

Added sendEmailInvitesToTeamGracefully/sendEmailGuestInvitesToChannelsGracefully to allow mixing bad/good users in invite
Fixes https://mattermost.atlassian.net/browse/MM-20977
Previous redux PR: https://github.com/mattermost/mattermost-redux/pull/1025
Server: https://github.com/mattermost/mattermost-server/pull/13372
Webapp: https://github.com/mattermost/mattermost-webapp/pull/4495

MM-20977 - Inviting multiple users with valid/allowed and invalid emails causes the invites for the valid users not to be sent

---

src/actions/teams.ts
src/client/client4.ts

Cherry pick of #1034 on release-5.20.
- #1034: added graceful invites
/cc  @reflog

Automated cherry pick of #1034

---

src/actions/websocket.test.js
src/actions/websocket.ts
src/reducers/entities/users.ts
src/selectors/entities/users.ts
src/store/initial_state.ts
src/types/users.ts

Cherry pick of #1038 on release-5.20.
- #1038: Added tracking of manual status set by user

Automated cherry pick of #1038

---

package-lock.json
package.json

Cherry pick of #1037 on release-5.20.
- #1037: updade @types/jest to 24.9.0
/cc  @saturninoabril

Automated cherry pick of #1037

---

src/action_types/channels.ts
src/action_types/general.ts
src/action_types/users.ts
src/actions/roles.ts
src/reducers/entities/channels.ts
src/reducers/entities/general.ts
src/reducers/entities/preferences.ts
src/reducers/entities/teams.ts
src/reducers/entities/users.ts
src/types/teams.ts
src/utils/post_list.test.js
src/utils/post_list.ts

Cherry pick of #1049 on release-5.21.
- #1049: Batch login actions and profiles in channel
/cc  @enahum

Automated cherry pick of #1049

---

src/actions/channels.test.js
src/actions/channels.ts
src/client/client4.ts
src/reducers/entities/channels.test.js
src/reducers/entities/channels.ts

Cherry pick of #1051 on release-5.21.
#1051: Synchronize archived channels with storage

Manual cherry pick for #1051

---

src/types/emojis.ts
src/utils/emoji_utils.ts

Moved some utils and fixed type definitions during working on the emoji picker.

Fix the type definition for emoji

---

src/reducers/entities/channels.ts

Cherry pick of #1063 on release-5.21.
- #1063: MM-22752 Preserve other teams channel membership
/cc  @enahum

Automated cherry pick of #1063

---

src/constants/index.ts
src/constants/roles.ts
src/types/roles.ts

This ticket is a part of https://github.com/mattermost/mattermost-webapp/pull/4881 where it was suggested to create a constants for roles.

[MM-22276] Add roles constants

---

src/actions/websocket.test.js
src/actions/websocket.ts

When a channel was archived the WebSocket handler did not set the `delete_at` property leaving it `undefined` and it was using the wrong `team_id` so that one was also `undefined` thus the channel was not being set as archived.
Also as part of the WS reconnect logic we determine if the user is no longer a member of the current channel by inspecting the response of `getMyChannels`. In servers prior to 5.21 or for those with the `ExperimentalViewArchivedChannels` config set to true, the request does not include the channel so the user was being redirected to Town-Square if for some reason their were sitting at an archived channel.
This PR ensures that the right values for `delete_at` and `team_id` are set when a channel gets archived and that if the user is viewing an archive channel ad the …

MM-22975|MM-22934 Fix mobile archive channel on action and WS reconnect

---

src/client/client4.ts

Add diagnostics_disabled event to whitelist.
https://mattermost.atlassian.net/browse/MM-22185

Add diagnostics_disabled event to whitelist.

---

src/client/client4.ts

This a PR to support changes in webapp in: https://github.com/mattermost/mattermost-webapp/pull/5047
https://mattermost.atlassian.net/browse/MM-23091

MM-23091  - whitelist new events to support onboarding analytics

---

src/client/client4.ts

Whitelisted event category for admin section. Needed for PR: https://github.com/mattermost/mattermost-webapp/pull/5049
https://mattermost.atlassian.net/browse/MM-23092

MM-23092 - Implement Server Setup telemetry - system console events

---

src/actions/websocket.test.js
src/actions/websocket.ts
src/selectors/entities/channels.test.js
src/selectors/entities/channels.ts

Cherry pick of #1072 on release-5.22.
- #1072: Removing not visible users from the store on leave
/cc  @jespino

Automated cherry pick of #1072

---

src/action_types/channels.ts
src/actions/posts.test.js
src/actions/posts.ts
src/reducers/entities/channels.ts
src/types/channels.ts

This PR updates the count of the pinned posts if the post is pinned or unpinned by the user.
JIRA: https://mattermost.atlassian.net/browse/MM-10272
https://github.com/mattermost/mattermost-server/issues/13817

MM-10272: Handle pinned post count when a post is pinned ot unpinned.

---

src/selectors/entities/preferences.test.js
src/selectors/entities/preferences.ts

Cherry pick of #1093 on release-5.22.
- #1093: MM-23513 Default autoclosing DMs to true with new sidebar
/cc  @hmhealey

Automated cherry pick of #1093

---

src/selectors/entities/channels.ts

Cherry pick of #1092 on release-5.22.
- #1092: Filter channels by DM_CHANNEL or GM_CHANNEL when grabbing
/cc  @fm2munsh

Automated cherry pick of #1092

---

src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts

https://mattermost.atlassian.net/browse/MM-23554
https://github.com/mattermost/mattermost-webapp/pull/5165

MM-23554 Sort muted channels to the bottom of the new sidebar

---

src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts

Cherry pick of #1098 on release-5.22.
- #1098: MM-23554 Sort muted channels to the bottom of the new sidebar
/cc  @hmhealey

Automated cherry pick of #1098

---

src/store/initial_state.ts
src/types/search.ts

Adding missing types from search global state
[MM-23649](https://mattermost.atlassian.net/browse/MM-23649)

Adding missing types from search global state

---

NOTICE.txt

Cherry pick of #1099 on release-5.22.
- #1099: Update NOTICE.txt
/cc  @amyblais

Automated cherry pick of #1099

---

src/actions/teams.ts
src/client/client4.ts
src/constants/teams.ts
src/types/teams.ts

The backend will accept parameters for how to sort the team members and if to exclude deleted users or not.
https://mattermost.atlassian.net/browse/MM-21517
The backend PR which implements this is https://github.com/mattermost/mattermost-server/pull/14043

[MM-21517] Add new options parameter to getTeamMembers to fix users not having their roles updated

---

src/types/search.ts

Fixes the import path of Dictionary patch to allow us to update to latest redux on web-app without server ci build failures

[No-Ticket] Fix import path causing Server CI build failures

---

src/constants/permissions.ts

This PR adds a new permission ACCESS_SYSTEM_CONSOLE which determines if the System Console menu item should be displayed for the user in webapp.
Permission added to server via https://github.com/mattermost/mattermost-server/pull/14190
Redux changes:  https://github.com/mattermost/mattermost-webapp/pull/5234
https://mattermost.atlassian.net/browse/MM-23542

MM-23542 new permission for system console access

---

src/client/client4.ts

Fix getChannelByNameAndTeamName.

Fix getChannelByNameAndTeamName.

---

src/client/client4.ts

Cherry pick of #1119 on release-5.22.
- #1119: Fix getChannelByNameAndTeamName.
/cc  @grundleborg

Automated cherry pick of #1119

---

src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts

Cherry pick of #1114 on release-5.22.
- #1114: MM-23756 Always show unread DMs and GMs
/cc  @hmhealey

Automated cherry pick of #1114

---

src/client/client4.ts

Fix typo. Not sure how this affects analytics reporting, but I suspect no issue.

Update client4.ts: fix typo 

---

package.json
src/selectors/entities/channels.ts

- Cherry pick of https://github.com/mattermost/mattermost-redux/pull/1092 into 5.19
https://mattermost.atlassian.net/browse/MM-23427

[MM-23427] cherry pick to release 5.19

---

src/client/client4.ts

This PR will add support of the autocomplete suggestions
Fixes https://mattermost.atlassian.net/browse/MM-21494
server - https://github.com/mattermost/mattermost-server/pull/14259
webapp -https://github.com/mattermost/mattermost-webapp/pull/5289
demo-plugin - https://github.com/mattermost/mattermost-plugin-demo/pull/99

[MM-21494] Add support of the autocomplete suggestions

---

src/client/client4.ts

Cherry pick of #1105 on release-5.23.
- #1105: MM-23569: Add rudder to diagnostics feature.
/cc  @grundleborg

Automated cherry pick of #1105

---

src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts

Cherry pick of #1115 on release-5.23.
- #1115: MM-23251 Always show the current channel, even if it has been
/cc  @hmhealey

Automated cherry pick of #1115

---

src/actions/teams.ts
src/client/client4.ts
src/constants/teams.ts
src/types/teams.ts

Cherry Pick of https://github.com/mattermost/mattermost-redux/pull/1091#event-3246214171

Cherry Pick of https://github.com/mattermost/mattermost-redux/pull/1091

---

src/utils/user_utils.ts

Add support for searching by position in user lists
https://mattermost.atlassian.net/browse/MM-5881

[MM-5881] Add support for searching by position in user lists

---

src/client/client4.ts

added additional analytics fields
https://mattermost.atlassian.net/browse/MM-22471

MM-22471 -  Implement Product Analytics to measure threads, posts and replies

---

src/client/client4.ts

Cherry pick of #1139 on release-5.23.
- #1139: added additional analytics fields
/cc  @reflog

Automated cherry pick of #1139

---

src/selectors/entities/groups.test.js
src/selectors/entities/groups.ts

- Adds a selector to get groups by name in order to check against potential mentions
- https://mattermost.atlassian.net/browse/MM-24632

[MM-24632] Add selector to get groups by name

---

src/client/client4.ts

Related PR: https://github.com/mattermost/mattermost-redux/pull/1148

Cherry pick MM-24967 release 5.23

---

src/client/client4.ts

Remove Segment.
QA will occur on the accompanying Web App PR once this is merged.
https://mattermost.atlassian.net/browse/MM-23573

MM-23573: Remove Segment.

---

src/selectors/entities/users.test.js
src/selectors/entities/users.ts

Cherry pick of #1169 on release-5.24.
- #1169: MM-25771 Add skipInactive filter for getting and
/cc  @fmunshi

Automated cherry pick of #1169

---

src/reducers/entities/admin.ts
src/types/admin.ts

Missed typing environmentConfig on AdminState on https://github.com/mattermost/mattermost-redux/pull/1172
https://mattermost.atlassian.net/browse/MM-25325

[MM-25325] Missed typing environmentConfig on AdminState

---

src/actions/admin.test.js
src/reducers/entities/admin.ts
src/types/admin.ts
src/types/groups.ts

Missed LDAP group typing in the reducer
https://mattermost.atlassian.net/browse/MM-25325

[MM-25325] Missed LDAP group typing in the reducer

---

src/actions/users.ts
src/client/client4.ts

This PR adds redirect query parameter to createUser endpoint. This is required for the change in https://github.com/mattermost/mattermost-webapp/pull/5841
https://mattermost.atlassian.net/browse/MM-26533

[MM-26533] Add redirect query parameter to create user request link

---

src/types/config.ts

Add a config EnableAskCommunityLink type definition
https://mattermost.atlassian.net/browse/MM-26620
Related PR: https://github.com/mattermost/mattermost-server/pull/14985

MM-26620 Add EnableAskCommunityLink type def

---

src/actions/teams.test.js
src/reducers/entities/teams.ts

Cherry pick of #1209 on release-5.26.
/cc  @ethervoid

Automated cherry pick of #1209

---

NOTICE.txt

Cherry pick of #1205 on release-5.26.
/cc  @amyblais

Automated cherry pick of #1205

---

src/actions/groups.test.js
src/actions/groups.ts
src/client/client4.ts

Cherry pick of #1212 on release-5.26.
/cc  @fmunshi

Automated cherry pick of #1212

---

src/types/config.ts

Adds new license feature for cloud.
Redux: https://github.com/mattermost/mattermost-redux/pull/1218
License Generator: https://github.com/mattermost/license-generator/pull/6
[MM-27930](https://mattermost.atlassian.net/browse/MM-27930)

MM-27930 - Cloud license feature

---

src/selectors/entities/bots.test.ts
src/selectors/entities/bots.ts

Hides internal bots from UX
https://mattermost.atlassian.net/browse/MM-27635
https://github.com/mattermost/mattermost-webapp/pull/6169

MM-27635: Hide internal bots from UX

---

src/selectors/entities/bots.test.ts
src/selectors/entities/bots.ts

Cherry pick of #1216 on release-5.27.
/cc  @catalintomai

Automated cherry pick of #1216

---

src/types/config.ts

Expose new configuration to flatmapped clientconfig
https://mattermost.atlassian.net/browse/MM-27535

[MM-27535] Adding new configuration for user limits

---

src/selectors/entities/users.ts

Cherry pick of #1220 on release-5.27.
/cc  @catalintomai

Automated cherry pick of #1220

---

src/selectors/entities/groups.test.js
src/selectors/entities/groups.ts
src/selectors/entities/search.ts

Cherry pick of #1214 on release-5.27.
/cc  @fmunshi

Automated cherry pick of #1214

---

src/constants/permissions.ts
src/constants/permissions_sysconsole.ts

Permissions constants for Billing and Account section of Admin Console (for Cloud Billing)
https://mattermost.atlassian.net/browse/MM-28200

[MM-28200] Permission constants for new Billing and Account sections of Admin Console

---

src/constants/permissions.ts

- Adds convert public channel permission and convert private channel to permissions list
- https://mattermost.atlassian.net/browse/MM-27274

[MM-27274] Add `convert_public_channel` permission

---

src/client/client4.ts

I was asked to try using the `page()` method of rudder to track page visits. So I've added it into redux.
https://mattermost.atlassian.net/browse/MM-27864

[MM-27864] Added page() method from rudder as pageVisited

---

src/reducers/entities/users.ts
src/store/initial_state.ts
src/types/users.ts

Added a missing field to `UsersState`, needed for https://github.com/mattermost/mattermost-webapp/pull/6432
https://mattermost.atlassian.net/browse/MM-20548

[MM-20548] Add missing type for `myUserAccessTokens` reducer

---

src/types/config.ts

Adds LdapPictureAttributeSet to config.
https://mattermost.atlassian.net/browse/MM-28005
https://github.com/mattermost/mattermost-webapp/pull/6258

MM-28005: Add config setting for LdapPictureAttributeSet

---

src/actions/teams.ts
src/client/client4.ts
src/types/product_notices.ts
src/types/websocket.ts

Cherry pick of #1234 on release-5.28.

Automated cherry pick of #1234

---

src/actions/channels.test.js
src/actions/channels.ts
src/reducers/entities/channels.ts

Cherry pick of #1240 on release-5.28.
/cc  @hmhealey

Automated cherry pick of #1240

---

src/constants/general.ts
src/selectors/entities/preferences.ts

Add `always_on` constant and option for new sidebar to be forced on
https://mattermost.atlassian.net/browse/MM-28972

[MM-28972] Add `always_on` constant and option for new sidebar to be forced on

---

src/constants/general.ts
src/selectors/entities/preferences.ts

[MM-28972] Add `always_on` constant and option for new sidebar to be forced on (#1243) - Cherry-pick

---

src/client/client4.ts
src/types/cloud.ts
src/types/config.ts

Added initial client methods for new `/cloud` endpoints required for in-app purchase. 
[MM-27144](https://mattermost.atlassian.net/browse/MM-27144)
Webapp: WIP
Server: https://github.com/mattermost/mattermost-server/pull/15428

MM-27144 - Cloud purchase endpoints

---

src/types/files.ts

Add `post_id` for FileInfo type

Add post_id for FileInfo type

---

src/action_types/cloud.ts
src/action_types/index.ts
src/actions/cloud.ts
src/actions/index.ts
src/client/client4.ts
src/reducers/entities/cloud.ts
src/reducers/entities/index.ts
src/store/initial_state.ts
src/types/cloud.ts
src/types/store.ts

Redux state to hold Cloud-specific data, starting with the customer data.
https://mattermost.atlassian.net/browse/MM-28217
Server: https://github.com/mattermost/mattermost-server/pull/15646
Webapp: https://github.com/mattermost/mattermost-webapp/pull/6580

[MM-28217] Added CloudState entity and state to hold cloud customer

---

src/types/cloud.ts

This was changed in mattermost-server but the change was not made here.
https://mattermost.atlassian.net/browse/MM-28197

[MM-27142] Change dollar_per_seat to price_per_seat

---

src/types/cloud.ts

This new field will be returned by the server and needed in the webapp for checks throughout.
https://mattermost.atlassian.net/browse/MM-28714

[MM-28714] Add is_paid_tier to Subscription type

---

src/types/cloud.ts

Cherry pick of #1253 on cloud-ga.
/cc  @nickmisasi

Automated cherry pick of #1253

---

src/types/config.ts

Added `CWSUrl` to the client config to create the url for Cloud contact us. 
Server: https://github.com/mattermost/mattermost-server/pull/15916
Webapp: https://github.com/mattermost/mattermost-webapp/pull/6731
Needed for [MM-27454 - Cloud Contact Us](https://mattermost.atlassian.net/browse/MM-27454)

MM-27454 - Added CWSUrl to client config

---

src/types/config.ts

Cherry pick of #1255 on cloud-ga.
/cc  @marianunez

Automated cherry pick of #1255

---

src/actions/cloud.ts
src/client/client4.ts
src/types/cloud.ts

Redux hooks for updating company info and address
https://mattermost.atlassian.net/browse/MM-28218

[MM-28218] Redux hooks for updating company info and address

---

src/client/client4.ts

Included user data under `user_actual_id`/`user_actual_role` to rudder page event. 
https://mattermost.atlassian.net/browse/MM-29799

Added user_actual_id to rudder page event

---

src/client/client4.ts

Cherry pick of #1264 on cloud-ga.
/cc  @marianunez

Automated cherry pick of #1264

---

src/actions/cloud.ts
src/client/client4.ts
src/types/cloud.ts

Cherry pick of #1259 on cloud-ga.

Automated cherry pick of #1259

---

src/action_types/cloud.ts
src/actions/cloud.ts
src/client/client4.ts
src/reducers/entities/cloud.ts
src/types/cloud.ts

Cherry pick of #1266 on cloud-ga.

Automated cherry pick of #1266

---

src/types/cloud.ts

Added a few additional fields to simplify the invoices on the front-end.
https://mattermost.atlassian.net/browse/MM-28214

[MM-28214] Additional fields on the invoices

---

src/types/cloud.ts

Cherry pick of #1271 on cloud-ga.

Automated cherry pick of #1271

---

src/constants/permissions.ts

Adding the required constant to add the permission
https://mattermost.atlassian.net/browse/MM-27909

MM-27909: Add shared channel permission

---

src/selectors/entities/users.test.js
src/selectors/entities/users.ts
src/utils/channel_utils.ts
src/utils/user_utils.test.js
src/utils/user_utils.ts

* Change existing searchprofiles selector to be searchProfilesStartingWithTerm
* Add a new selector searchProfileMatchingWithTerm for substring matches
https://mattermost.atlassian.net/browse/MM-22854

MM-22845 Fix quick switcher results

---

src/selectors/entities/users.test.js
src/selectors/entities/users.ts
src/utils/channel_utils.ts
src/utils/user_utils.test.js
src/utils/user_utils.ts

Cherry pick of #1270 on release-5.29.

Automated cherry pick of #1270

---

src/types/config.ts

Feature flags type. 
https://mattermost.atlassian.net/browse/MM-28860

MM-28843 Add feature flags to the admin config struct.

---

src/client/client4.ts

Cherry pick of #1277 on release-5.29.

Automated cherry pick of #1277

---

src/selectors/entities/general.test.js
src/selectors/entities/general.ts
src/types/config.ts

Cherry pick of #1282 on release-5.29.
/cc  @hmhealey

Automated cherry pick of #1282

---

src/constants/permissions.ts
src/constants/permissions_sysconsole.ts

Redux changes for https://github.com/mattermost/mattermost-webapp/pull/6529

[MM-27556] UI For new system roles

---

src/types/apps.ts
src/types/integrations.ts

https://mattermost.atlassian.net/browse/MM-30040
https://github.com/mattermost/mattermost-webapp/pull/7055
https://github.com/mattermost/mattermost-plugin-apps/pull/36

Updates for app modals

---

src/constants/permissions.ts

Add `MANAGE_REMOTE_CLUSTERS` to constants.
https://mattermost.atlassian.net/browse/MM-30317

[MM-30317] add MANAGE_REMOTE_CLUSTERS permission

---

src/constants/apps.ts
src/selectors/entities/apps.ts
src/types/apps.ts
src/types/integrations.ts

Matches https://github.com/mattermost/mattermost-plugin-apps/pull/32

Updated apps types to reflect server changes

---

src/reducers/entities/apps.ts
src/selectors/entities/apps.ts
src/types/apps.ts

Some fixes to sync with lev-clenaup branch on apps
None
https://github.com/mattermost/mattermost-plugin-apps/pull/34

Some fixes to sync with lev-clenaup branch on apps

---

src/types/config.ts
src/types/plugins.ts

- Add `IsDefaultMarketplace` to `ClientConfig`
- Add `MarketplaceLabel`
- Update `MarketplacePlugin`
https://mattermost.atlassian.net/browse/MM-20400

[MM-20400] Add IsDefaultMarketplace to ClientConfig

---

src/types/plugins.ts

Redux part of https://github.com/mattermost/mattermost-server/pull/16438
https://mattermost.atlassian.net/browse/MM-30981

[MM-30981] Require Plugin name in manifest

---

src/actions/admin.ts
src/client/client4.ts

The `mattermost-server` [POST `/compliance/reports`] (https://github.com/mattermost/mattermost-server/blob/v5.28.1/api4/compliance.go#L23) API expects a [Compliance](https://github.com/mattermost/mattermost-server/blob/v5.28.1/model/compliance.go#L24) (see [ComplianceFromJson()](https://github.com/mattermost/mattermost-server/blob/v5.28.1/model/compliance.go#L101)), but the `mattermost-redux` [createComplianceReport()](https://github.com/mattermost/mattermost-redux/pull/1289/files#diff-4858c6eaa6b8141168b93baf130f295640fa0a66fdf3d6174dba2e4315cb707dL133) action takes in a [Job](https://github.com/mattermost/mattermost-redux/blob/b928ae9d0bed614138a020b405f4bffd5143d54c/src/types/jobs.ts#L6) instead of a [Compliance](https://github.com/mattermost/mattermost-redux/blob/b928ae9d0bed614138a020 …

Fix createComplianceReport action parameter type

---

src/action_types/threads.ts
src/actions/threads.ts
src/client/client4.ts
src/constants/preferences.ts
src/reducers/entities/threads.test.js
src/reducers/entities/threads.ts
src/selectors/entities/preferences.ts
src/selectors/entities/threads.ts
src/store/initial_state.ts
src/types/config.ts
src/types/threads.ts

MM-31126 Collapsed threads support, additional

---

src/constants/permissions.ts

Redux changes required for https://github.com/mattermost/mattermost-server/pull/16569

[MM-28000] Fix system manager can download export files without right permissions

---

src/types/integrations.ts

Added types to master, to make it easier to merge master into apps branch.
https://mattermost.atlassian.net/browse/MM-31667
https://github.com/mattermost/mattermost-webapp/pull/7297

Add types for command autocomplete and interactive dialog

---

.gitlab-ci.yml

Enable gitlab ci for release-5.29

---

.github/workflows/codeql-analysis.yml

Added step to run automated CodeQL checks. Once this file is merged, the codeql checks will automatically be performed on new pull requests to master branch.
https://mattermost.atlassian.net/browse/MM-31882

MM-31882 - Add CodeQL check 

---

src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts

The last_viewed_at timestamp for channel members is only ever updated on the server to the time of the most recent post in the channel, so when the user refreshes, the priority for showing DM channels might change.
The old autohiding solved that by using some other timestamps which I'd like to remove eventually if we can make last_viewed_at work better, but in the mean time, we can still make use of them to get a better idea of when the user actually last viewed the channel.
https://mattermost.atlassian.net/browse/MM-32197
https://github.com/mattermost/mattermost-webapp/pull/7367

MM-32197 Use other timestamps when autohiding DMs/GMs

---

src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts

Cherry pick of #1339 on cloud.
/cc  @hmhealey

Automated cherry pick of #1339

---

src/client/client4.ts

Exposes the new renewal link endpoint - hook up license renewal button in banner
https://mattermost.atlassian.net/browse/MM-31914
* has a related PR with mattermost-webapp [PR7355](https://github.com/mattermost/mattermost-webapp/pull/7355)

MM-31914 - expose the new renewal link

---

.github/workflows/codeql-analysis.yml
src/action_types/cloud.ts
src/actions/cloud.ts
src/client/client4.ts
src/reducers/entities/cloud.ts
src/selectors/entities/channel_categories.test.js
src/selectors/entities/channel_categories.ts
src/types/cloud.ts
src/types/config.ts

The cloud release branch for 2021-02-10
https://mattermost.atlassian.net/browse/MM-32488

[MM-32488] Cloud release 2021-02-10

---

jest.config.js
src/actions/threads.test.js
src/actions/threads.ts
src/client/client4.ts
src/reducers/entities/threads.test.js
src/reducers/entities/threads.ts
src/selectors/entities/general.test.js
src/selectors/entities/general.ts
src/selectors/entities/threads.ts
src/types/config.ts
src/types/threads.ts

cursor support, unreads, extended, total_unread_threads
https://mattermost.atlassian.net/browse/MM-32310

MM-32310 Update redux with collapsed thread related changes

---

src/selectors/entities/general.ts

Adds the selector for the subscriptionStats used in https://github.com/mattermost/mattermost-webapp/pull/7468
[MM-31503](https://mattermost.atlassian.net/browse/MM-31503)

MM-31503 - create new restrict screens 4 users

---

src/action_types/threads.ts
src/actions/threads.ts
src/client/client4.ts
src/reducers/entities/threads.test.js
src/reducers/entities/threads.ts
src/types/threads.ts

https://mattermost.atlassian.net/browse/MM-32525

MM-32525 added unread_mentions_per_channel

---

src/reducers/entities/cloud.ts

Make sure the SubscriptionStats defaults to null in redux state
[MM-31497](https://mattermost.atlassian.net/browse/MM-31497?atlOrigin=eyJpIjoiMDJhMDQwOWM1ODZhNDMzM2IyNDE5ZjAxNDM1OTg4Y2UiLCJwIjoiaiJ9)
[Comment](https://github.com/mattermost/mattermost-webapp/pull/7408#discussion_r570703269)

[MM-31497] - Default SubscriptionStats to null

---

src/client/client4.ts

This PR adds a link where users can notify admin about free tier over limit
[MM-31502](https://mattermost.atlassian.net/secure/RapidBoard.jspa?rapidView=79&projectKey=MM&modal=detail&selectedIssue=MM-31502&quickFilter=382)

[MM-31502] - Add Notify Admin link to invitation modal

---

src/actions/preferences.ts
src/actions/users.ts
src/client/client4.ts
src/constants/preferences.ts
src/types/config.ts
src/types/users.ts

- Add types and actions to set and unset custom status.
- https://github.com/mattermost/mattermost-server/pull/16835
- Specs: https://mattermost.atlassian.net/wiki/spaces/CS/pages/983302547/User+Experience+and+Functional+Notes

Custom status feature

---

src/actions/preferences.ts
src/actions/users.ts
src/client/client4.ts
src/constants/preferences.ts
src/types/config.ts
src/types/users.ts

Cherry pick of #1349 on cloud.
/cc  @chetanyakan

Automated cherry pick of #1349

---

package-lock.json
package.json

Cherry pick of #1372 on cloud.
/cc  @hmhealey

Automated cherry pick of #1372

---

src/client/client4.ts

This PR adds client4 method to call new endpoint ```/cloud/subscription/limitreached/join```
[MM-32691](https://mattermost.atlassian.net/browse/MM-32691?atlOrigin=eyJpIjoiYmU1ZjdiMWJlZDRiNGE5ZmJjNGNjYjA2Y2VjZjA5YTEiLCJwIjoiaiJ9)

[MM-32691] - Send email when the users are not able to join a workspace

---

src/types/apps.ts
src/utils/marketplace.ts

The latest merge from `master` caused some linter errors. Please double check that the fixes are correct.
None

Fix linter errors on feature/cloud-apps

---

src/client/client4.ts
src/types/apps.ts

Add User Agent to call context.
None
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/82
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5193

Add User Agent to call context

---

src/action_types/apps.ts
src/actions/apps.ts
src/client/client4.ts
src/constants/apps.ts
src/reducers/entities/apps.ts
src/selectors/entities/apps.ts
src/types/apps.ts
src/types/marketplace.ts
src/utils/marketplace.ts

Add warnings into code about using apps related code, due to possible breaking changes in the future.
https://mattermost.atlassian.net/browse/MM-32447

Add warning into code about using apps related code

---

src/client/client4.ts

Change user agent property in get bindings query to make it more intention revealing
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/82
Mobile: https://github.com/mattermost/mattermost-redux/pull/1388

Change user agent property in get bindings query

---

NOTICE.txt

Cherry pick of #1385 on release-5.33.
/cc  @amyblais

Automated cherry pick of #1385

---

src/types/apps.ts

https://mattermost.atlassian.net/browse/MM-33511

[MM-33511] Apps might not have a RootURL

---

src/constants/apps.ts

Fixes https://mattermost.atlassian.net/browse/MM-31981

Change call type submit and call response ok to not be empty strings

---

src/selectors/entities/admin.ts

This PR creates a new selector for easily and descriptively retrieve the analytics information
https://mattermost.atlassian.net/browse/MM-32642
https://github.com/mattermost/mattermost-webapp/pull/7645

MM-32642 - increase invite other visibility

---

src/actions/admin.test.js
src/actions/bots.test.js
src/actions/channel_categories.test.js
src/actions/channels.test.js
src/actions/emojis.test.js
src/actions/errors.test.js
src/actions/files.test.js
src/actions/general.test.js
src/actions/groups.test.js
src/actions/helpers.test.js
src/actions/integrations.test.js
src/actions/jobs.test.js
src/actions/posts.test.js
src/actions/preferences.test.js
src/actions/roles.test.js
src/actions/schemes.test.js
src/actions/search.test.js
src/actions/teams.test.js
src/actions/threads.test.js
src/actions/users.test.js
src/selectors/entities/preferences.test.js
src/store/reducer_registry.test.js
src/utils/theme_utils.test.js
test/test_helper.js
test/test_store.js

async/await and this mocking seemed to cause issues after this was moved into the web app. I'm not 100% sure that these will solve those issues, but they seem decent enough to clean up anyway.

Remove async/await and some mocks from tests

---

src/types/cloud.ts
src/types/config.ts

Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>
It changes the name of the SubscriptionStats in camelcase as it was written in bad mannered and added a property which is used in the react web app.
Fixes: https://mattermost.atlassian.net/browse/MM-20389

[GH_16717/MM_20389] Migrate 'components/signup/signup_controller' module and associated tests to TypeScript
